fix(ui5-input): properly change numeric input value using the arrow keys
SAP/ui5-webcomponents pull request #10018
Opened 2024-10-14 21:23 UTC by Okiana

Downport #9616

Fire input event when user uses the arrow keys to increase or decrease the value of a numeric input

Fixes [#9785](https://github.com/SAP/ui5-webcomponents/issues/9785)

2024-10-16 09:37 UTC, nikoletavnv approved these changes

2024-10-16 12:20 UTC, nnaydenow requested changes

2024-10-16 12:20 UTC, nnaydenow commented on packages/main/test/specs/Input.spec.js
> +		await input.keys("ArrowUp");
browser.keys

2024-10-18 06:49 UTC, nnaydenow approved these changes

2024-10-18 07:00 UTC, merged