feat(ui5-color-picker): add simplified display mode
SAP/ui5-webcomponents pull request #10153
Opened 2024-11-06 17:49 UTC by didip1000

Introducing a new property `displayMode` for the `ui5-color-picker` allowing users to select between the `default` (classic) color picker or the new `simplified` color picker. 

The simplified picker does not include the RGB inputs and alpha slider.

You can create a color picker in simplified mode as follows: 

```html
<ui5-color-picker display-mode="Simplified"></ui5-color-picker>
```

Which will look as follows:

<img width="183" alt="image" src="https://github.com/user-attachments/assets/0c78fef9-e0d3-4b30-aee9-84e7fbae4ec6">

Fixes: #9979

2024-11-07 11:24 UTC, BorisDafov approved these changes

2024-11-07 12:59 UTC, hinzzx reviewed
Just few minor comments, after they are being addressed the change looks good to me.

2024-11-07 12:59 UTC, hinzzx commented on packages/main/src/ColorPicker.hbs
> +    {{#if _displayFullPicker}}
we can name the getter `_isFullPicker()` or `_isDefaultPickerMode()`

2024-11-07 12:59 UTC, hinzzx commented on packages/main/src/ColorPicker.ts
> +	 *
redunant empty row, do it after the description, before the `@default` tag maybe

2024-11-11 10:23 UTC, hinzzx approved these changes

2024-11-13 07:18 UTC, tsanislavgatev requested changes

2024-11-13 07:18 UTC, tsanislavgatev commented on packages/main/test/specs/ColorPicker.spec.js
> +	it("should not display color channel inputs and alpha slider in simplified mode", async () => {
Please write the test in cypress, not wdio.

2024-11-14 07:22 UTC, tsanislavgatev approved these changes

2024-11-14 07:51 UTC, merged