feat(ui5-step-input): add input event
SAP/ui5-webcomponents pull request #10294
Opened 2024-12-03 14:18 UTC by tsanislavgatev

fixes: https://github.com/SAP/ui5-webcomponents/issues/5177

2024-12-05 07:42 UTC, unazko approved these changes
Works as expected.

2024-12-06 11:24 UTC, vladitasev requested changes

2024-12-06 11:24 UTC, vladitasev commented on packages/main/src/StepInput.ts
> + * and when a suggestion item has been selected.
This is not relevant for step input

2024-12-06 11:24 UTC, vladitasev commented on packages/main/src/StepInput.ts
> + * @since 2.5.0
this becomes 2.6.0 now

2024-12-06 11:24 UTC, vladitasev commented on packages/main/src/StepInput.ts
> +	_onInput(e: InputEvent) {
`InputEvent` is wrong here - this is the event type that will be fired by the native input (so in Input.ts it's normal that the event listener of this type) - here you need the correct `InputEventDeatil` from the `Input.ts` event types.

2024-12-06 11:24 UTC, vladitasev commented on packages/main/src/StepInput.ts
> +		input: void
I think the `inputType` event detail that exists on `InputEventDetail` is relevant for the user, so it must also be proxied.

2024-12-06 11:24 UTC, vladitasev commented on packages/main/src/StepInput.ts
> +		const prevented = !this.fireDecoratorEvent("input");
Fire with parameters (see my comment above in `eventDetails`

2024-12-06 11:48 UTC, vladitasev approved these changes

2024-12-06 12:36 UTC, merged