feat(ui5-flexible-column-layout): add arrow icon functionality
SAP/ui5-webcomponents pull request #10362
Opened 2024-12-11 13:55 UTC by NakataCode

- Added the icon in the FCL hbs (positioned in the first separator)
 - Added basic styling for the icon
 - Added functionality for the icon, so we can toggle the first column `toggleStartColumnVisibility`
 - Added `arrowIconName` to conditionally display the icon
 - Added two new layouts `ThreeColumnsBeginHiddenMidExpanded` and `ThreeColumnsBeginHiddenEndExpanded`
 - Added a new variable to check if the FCL is or was set to the new layouts `_hasBeenInIconVisibleLayout` so we can have the icon to specific layouts
 - Added keyboard handling for the icon (When `Enter` or `Space` is pressed on the icon, the icon is toggled)
 - Added new sample in the test page
 - Added tests

2025-01-09 09:03 UTC, NakataCode commented on packages/fiori/src/FlexibleColumnLayout.ts
> +		}) && newColumnWidths.start >= 25) {
Done

2025-01-09 09:06 UTC, NakataCode commented on packages/fiori/src/FlexibleColumnLayoutTemplate.tsx
> +			{ this.arrowIconName && (
Understood, I'll update it to use this.showStartSeparatorArrow and add arrowStart as a separate function alongside gripStart for clarity.

2025-01-09 09:07 UTC, NakataCode commented on packages/fiori/src/fcl-utils/FCLLayout.ts
> +					{ visible: true, gripVisible: true },
Agreed. Consolidating arrow visibility and direction into the LayoutConfiguration ensures that layout details remain centralized. I'll add arrowVisible and arrowDirection to the separators array in the LayoutConfiguration type, as suggested.

2025-01-09 09:08 UTC, NakataCode commented on packages/fiori/src/FlexibleColumnLayout.ts
> +	toggleStartColumnVisibility() {
Agreed, renaming to switchLayoutOnArrowPress makes the method more generic and aligned with its purpose. I'll update the listener and implement the suggested switchLayoutOnArrowPress logic to ensure better decoupling and reusability.

2025-01-09 09:10 UTC, NakataCode commented on packages/fiori/src/themes/FlexibleColumnLayout.css
>  }
I tested this, but it misaligns the grip:before in my case. Additional adjustments may be needed for alignment across all scenarios.

2025-01-20 15:24 UTC, kineticjs requested changes
also noticed accidentally that `onSeparatorPress `is triggered when we press an arrow. Did not seem like a big issue but we can add e.g:
```javascript
if (e.target as HTMLElement === this.startArrowDOM) {
	return;
}
```
to the beginning of `onSeparatorPress` to prevent it starting an obsolete `separatorMovementSession` upon arrow-click

2025-01-20 15:24 UTC, kineticjs commented on packages/fiori/src/FlexibleColumnLayout.ts
>  	async _onkeydown(e: KeyboardEvent) {
this is correct, but I'd suggest to split the function into two for simplicity.:

1) add new `_onArrowKeyDown` function e.g.:
```javascript
_onArrowKeydown(e: KeyboardEvent) {
  if (isEnter(e) || isSpace(e)) {
	  e.preventDefault();
	  const focusedElement = e.target as HTMLElement;
	  if (focusedElement === this.startArrowDOM) {
		  this.switchLayoutOnArrowPress();
	  }
  }
}
```
and
2) we can e.g. directly register this new function as a handler for the onKeyDown of the arrow button
and
3) we can rename the existing `_onkeydown` function to `_onSeparatorKeyDown` and just add code in the beginning to ensure it is executed only if an entire separator is focused, e.g::

```javascript
async _onSeparatorKeydown(e: KeyboardEvent) {
  const separator = e.target as HTMLElement;
  if (!separator.classList.contains("ui5-fcl-separator")) {
	  return;
  }
---
```

(or keep the old `_onkeydown` and only forward to either `_onArrowKeydown` or `_onSeparatorKeydown` depending on the event target: arrow or entire separator)

This [splitting onto two handlers] is a minor reorganization that should make the code appear simpler IMO.

2025-01-20 15:24 UTC, kineticjs commented on packages/fiori/src/themes/FlexibleColumnLayout.css
> +/*only if the arrow is present the lines will be shorten*/
again, this is totally correct, but I would suggest splitting into two as that way IMO  it looks a bit simpler e.g:

1) original selector for `hover` remains as is:
```css
.ui5-fcl-separator:hover .ui5-fcl-grip:before,
.ui5-fcl-separator:hover .ui5-fcl-grip:after {
	height: calc(50% - 1rem);
}
```
but add a second selector with your original comment:
```css
/*only if the arrow is present the lines will be shorter*/
.ui5-fcl-separator:hover .ui5-fcl-arrow + .ui5-fcl-grip::before  {
	height: calc(40% - 1rem);
}
```

2025-01-20 18:03 UTC, kineticjs commented on packages/fiori/test/pages/FCL.html
> +		<ui5-flexible-column-layout id="fcl10" layout="ThreeColumnsBeginHiddenMidExpanded">
"ThreeColumnsStartHiddenMidExpanded"

2025-01-22 07:36 UTC, NakataCode commented on packages/fiori/src/themes/FlexibleColumnLayout.css
> +/*only if the arrow is present the lines will be shorten*/
Thanks for the suggestions! I implemented it with a slight modification. Since we always render the arrow in the DOM and control its visibility via display: none, I opted for this approach:
```css
.ui5-fcl-separator:hover .ui5-fcl-arrow:not([style*="display: none"]) + .ui5-fcl-grip::before {
    height: calc(40% - 1rem);
}
```

2025-01-22 11:01 UTC, kineticjs commented on packages/fiori/src/FlexibleColumnLayout.ts
> +		if (!this.startColumnVisible && e.target === this.startSeparatorDOM && isLeft(e)) {
all other additions to `_onSeparatorKeydown` are redundant in my testing because
- moveSeparator already checks if the requested move is allowed
- we already return early when the target is an arrow

2025-01-22 15:41 UTC, kineticjs approved these changes

2025-01-22 15:41 UTC, merged