refactor(ui5-li-notification, ui5-li-notification-group): migrate templates from HBS to JSX
SAP/ui5-webcomponents pull request #10429
Opened 2024-12-20 11:57 UTC by dimovpetar

2024-12-30 15:08 UTC, ilhan007 commented on packages/fiori/src/NotificationListGroupItemTemplate.tsx
> +						role="list"
Can't we use `accessibleRole`, inherited in NotificationListGroupList from List, not just `role`.
Also, `accessibleRole` is "list" by default.

2025-01-06 09:25 UTC, dimovpetar commented on packages/fiori/src/NotificationListGroupItemTemplate.tsx
> +						role="list"
You are right. Done

2025-01-06 11:45 UTC, TeodorTaushanov requested changes

2025-01-06 11:45 UTC, TeodorTaushanov commented on packages/fiori/src/themes/NotificationListGroupItem.css
> +	margin-bottom: var(--_ui5-notification_group_header-margin-expanded)
missing `;`

2025-01-06 12:16 UTC, dimovpetar commented on packages/fiori/src/themes/NotificationListGroupItem.css
> +	margin-bottom: var(--_ui5-notification_group_header-margin-expanded)
Done

2025-01-06 13:33 UTC, TeodorTaushanov approved these changes

2025-01-06 14:21 UTC, ilhan007 approved these changes

2025-01-06 14:24 UTC, merged