feat(ui5-tab-container): implement overflo-button slot
SAP/ui5-webcomponents pull request #2192
Opened 2020-09-08 10:06 UTC by fifoosid

Fixes #2184

2020-09-10 06:02 UTC, vladitasev requested changes
The custom button is always there, no matter if an overflow menu is needed or not:
![image](https://user-images.githubusercontent.com/15844574/92687491-50f85880-f344-11ea-9dec-06aeaede0d59.png)

The normal button hides/appears properly

2020-09-10 12:44 UTC, fifoosid commented on packages/main/src/TabContainer.js
> +			invalidateParent: true,
It was used in the initial implementation, but now it is not necessary

2020-09-10 12:45 UTC, fifoosid commented on packages/main/src/TabContainer.js
> +		if (this.responsivePopover.opened) {
Yes, this is the intended behaviour which was not implemented until now.

2020-09-10 12:45 UTC, fifoosid commented on packages/main/src/TabContainer.js
> +		 * Defines the buttons which is shown when there are overflowed items. If nothing is provided to this slot, the default button will be used.
Done

2020-09-14 06:51 UTC, vladitasev approved these changes

2020-09-14 07:27 UTC, merged