feat(ui5-li, ui5-li-tree, ui5-li-custom, ui5-upload-collection-item):  implement role property
SAP/ui5-webcomponents pull request #2236
Opened 2020-09-23 09:34 UTC by fifoosid

Part of #2231

2020-09-25 12:56 UTC, mastanshaikk reviewed
Looks good

2020-09-28 08:16 UTC, ilhan007 requested changes

2020-09-28 08:16 UTC, ilhan007 commented on packages/main/src/ListItem.js
> +			role: this.role || "option",
this.role is by default  "option", I guess we don't need the "||" statement

2020-09-28 11:08 UTC, ilhan007 approved these changes

2020-09-28 11:09 UTC, merged