feat(ui5-popover): implement hide-block-layer property
SAP/ui5-webcomponents pull request #2413
Opened 2020-10-28 10:15 UTC by fifoosid

Fixes #2406

2020-10-28 14:08 UTC, ilhan007 requested changes
It's worth adding a test, moreover soon  the components will be handed over and it is good if they have decent code coverage

2020-10-28 14:08 UTC, ilhan007 commented on packages/main/src/Popover.js
> +		 * @type {Boolean}
boolean

2020-11-03 06:45 UTC, vladitasev requested changes
Please rename "block layer" to "backdrop" **only in the public API** as this is what most people would understand. The hide/showBlockLayer functions are already used in third-party popups so don't rename them

2020-11-19 07:18 UTC, ilhan007 approved these changes

2020-11-19 07:20 UTC, ilhan007 commented
It is fine to m,  @vladitasev  could you check if everything is ok, I removed your review as outdated

2020-11-19 08:15 UTC, merged