fix(ui5-select): remove aria-roledescription
SAP/ui5-webcomponents pull request #2463
Opened 2020-11-11 21:24 UTC by kineticjs

The reledescription prevents its role button to be read by JAWS
so it is now removed following consultation with ACC expert.

Fixes #2358

2020-11-12 05:17 UTC, ilhan007 requested changes
Thanks for this change, there is one lint error causing the build failure

 `27:2  error  'SELECT_ROLE_DESCRIPTION' is defined but never used  no-unused-vars`

2020-11-16 14:42 UTC, kineticjs commented
Thanks for the hint! I updated the change...
Please comment if you think a test should also be added. I didn't add so far as the change is small..

2020-11-17 09:21 UTC, fifoosid reviewed
I think it would be a good idea if @dobrinyonkov takes a look at the PR and say if it covers the whole issue.

Technically, the change looks good to me and I can approve.

2020-11-18 09:14 UTC, dobrinyonkov reviewed
Looks good to me!

2020-11-18 09:17 UTC, ilhan007 approved these changes

2020-11-18 09:17 UTC, merged