feat(ui5-side-navigation): introduce alignItems property
SAP/ui5-webcomponents pull request #2521
Opened 2020-11-26 15:20 UTC by ilhan007

First of all, the change fixes the default alignment of the items in the SideNavigation. After the change the items are aligned by their text, which means in case we have a mixture of items with and without icons, the ones without an icon will be indented. This makes the component aligned with its openui5 equivalent and Fiori 3.
But, we also provide the option to set a second type of alignment by introducing a new property on SideNavigation level, called **alignItems** that will apply for both levels of items.
Available options are **Start** and **Text** (default).
- The Text option means the items will be aligned by their text - the items without icon will be indented.
- The Start option means the items will be aligned from the start - without any additional indentation.

<img width="534" alt="Screenshot 2020-11-26 at 1 54 03 PM" src="https://user-images.githubusercontent.com/15702139/100367314-b89c7680-300a-11eb-830c-0479b413b8b9.png">

2020-11-26 16:40 UTC, ilhan007 commented
align-items="Text" is strange, I will try come up with better proposal

2020-11-30 07:48 UTC, vladitasev requested changes
I would suggest unifying the enum for the `Tree` and `SideNavigation`, making the new property `public` in both places, renaming the property to `itemsAlignment` and renaming the enum to `ItemsAlignment` with values:

`ItemsAlignment`: `Start` | `Text`
`Start` - each item is aligned with the start of the other items
`Text` - each item's text is aligned with the text of the other items

I think this type would be general enough, as it could be applied to any list (anything that has a vertical list of items) and we could freely reuse it for future components as well.

Additional remark: does it work on `compact` mode? (I saw a hard-coded `1.5rem` indent in the CSS)

2020-11-30 07:48 UTC, vladitasev commented on packages/main/src/Tree.js
> +	 * Marks the items that needs to be idented.
needs => need

2021-03-16 17:54 UTC, ilhan007 commented
This won't be implemented in the standard SideNavigation. If ever implemented, it would go as a feature in a custom compoenent library.

2021-03-16 17:54 UTC, closed without merging