fix(ui5-input): focus is handled properly
SAP/ui5-webcomponents pull request #2670
Opened 2021-01-12 14:57 UTC by niyap

Previously, on focus the ui5-input component, when the event target was ui5-input, the focused attribute was not added. As a result, the focus outline was not presented, as well as the suggestions were not visualised initially when used.

Fixes #2652

2021-01-19 13:24 UTC, MapTo0 requested changes
add a test reproducing the described issue

I think the issue is now just moved in the multi input

2021-01-19 13:24 UTC, MapTo0 commented on packages/main/src/MultiInput.js
> +	 * @override
override?

2021-01-20 12:24 UTC, ilhan007 commented on packages/main/test/specs/Input.spec.js
> +	it("Should open suggestions popover when ui5-input is the fisrt focusable element within a dialog", () => {
first (typo)

2021-01-20 13:56 UTC, ilhan007 approved these changes

2021-01-20 13:57 UTC, ilhan007 approved these changes
it is ok to me, up to @MapTo0 to merge the change

2021-01-22 13:01 UTC, MapTo0 approved these changes

2021-01-22 13:01 UTC, merged