feat(ui5-slider, ui5-range-slider): Implement accessibility specifications
SAP/ui5-webcomponents pull request #2714
Opened 2021-01-21 08:51 UTC by ivoplashkov

FIXES: #2513

2021-01-21 08:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/ui5-webcomponents?pullRequest=2714) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAP/ui5-webcomponents?pullRequest=2714) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/ui5-webcomponents?pullRequest=2714) it.</sub>

2021-01-22 09:29 UTC, elenastoyanovaa requested changes

2021-01-22 09:29 UTC, elenastoyanovaa commented on packages/main/src/i18n/messagebundle.properties
> +#XACT: ARIA description for the slider
Aria description for range slider start handle

2021-01-22 09:29 UTC, elenastoyanovaa commented on packages/main/src/i18n/messagebundle.properties
> +#XACT: ARIA description for the slider
.... for range slider end handle

2021-01-22 09:29 UTC, elenastoyanovaa commented on packages/main/src/i18n/messagebundle.properties
> +#XACT: ARIA description for the slider
aria description for range slider progress

2021-01-22 09:29 UTC, elenastoyanovaa commented on packages/main/src/i18n/messagebundle.properties
> +#XACT: ARIA description for the slider
aria description for slider handle

2021-01-22 09:29 UTC, elenastoyanovaa commented on packages/main/src/RangeSlider.js
> +	get _ariaStartHandleText() {
the logic in _ariaStartHandleText & _ariaEndHandleText is the same, the only difference is the message bundle var...could we try to extract the common logic somehow?

2021-01-22 10:19 UTC, elenastoyanovaa requested changes
Also it is a good idea to add some tests regarding the swap of the aria-labelledby in the range slider handles.

2021-01-25 05:35 UTC, ndeshev commented on packages/main/src/Slider.js
> +	get ariaLabelledByText() {
Add an underscore indicating a private property like the rest of the aria related ones.

2021-01-25 05:35 UTC, ndeshev commented on packages/main/src/RangeSlider.hbs
> +<span id="{{_id}}-sliderDesc" class="ui5-hidden-text">{{_ariaLabelledByText}}</span>
We had these line in both Slider's and RangeSlider's template, maybe it will be a bit better to move it to the SliderBase.hbs

2021-01-25 05:35 UTC, ndeshev commented on packages/main/src/RangeSlider.js
> -
After removing of this code, the _tabindex private property declared in SliderBase.js is no longer used and not needed, remove it also.

2021-01-25 05:37 UTC, ndeshev commented on packages/main/src/RangeSlider.js
> -
Also in SliderBase.js remove the tabIndex getter from the bottom which is also no longer used anymore

2021-01-25 05:55 UTC, ndeshev commented on packages/main/src/RangeSlider.hbs
> +{{#*inline "progressbar"}}
Use camel case - progressBar

2021-01-25 08:27 UTC, ivoplashkov commented
Thanks for the reviews, comments are applied.

2021-01-25 12:53 UTC, elenastoyanovaa requested changes
Both slider and range slider are focusable when disabled, could you remove the focus, when the components are disabled?

2021-01-25 13:15 UTC, ivoplashkov commented
> Both slider and range slider are focusable when disabled, could you remove the focus, when the components are disabled?

Done.

2021-01-26 06:47 UTC, elenastoyanovaa approved these changes

2021-01-26 08:31 UTC, ilhan007 approved these changes

2021-01-26 08:32 UTC, merged