fix(ui5-combobox): center ValueState message text
SAP/ui5-webcomponents pull request #2733
Opened 2021-01-26 14:20 UTC by ndeshev

ValueState text is now vertically centered in the Popover's header.

Issue: #2274

2021-01-26 14:49 UTC, ilhan007 requested changes
Because the ResponsivePopover.css styles take effect in input with suggestions, combobox, multi combobox, multi input, select and all date-time components, I think the value state text alignment of the text should be checked for them as well. 
(1) Check if  this is a bug only in the ComboBox
and 
(2) make sure the fix won't break the rest of the components.

2021-01-26 16:01 UTC, ndeshev commented
The issue was also present in MultiComboBox, I added a fix for it and reverted back the previous value of the responsive popover's header CSS height param.

2021-01-27 08:36 UTC, ilhan007 commented on packages/main/src/themes/base/sizes-parameters.css
> -	--_ui5-responnsive_popover_header_height: 2.75rem;
Should we remove the cozy param? I think we should keep it and just fix the typo - responnsive -> responsive

2021-01-27 11:16 UTC, ilhan007 requested changes
It works for single line, but not for the valueStateMessage slot. I guess it is the line-height

<img width="382" alt="Screenshot 2021-01-27 at 1 15 34 PM" src="https://user-images.githubusercontent.com/15702139/105983684-c2da0000-60a1-11eb-9e5c-178c53c1f9ee.png">

2021-01-27 13:28 UTC, ilhan007 approved these changes

2021-01-27 14:07 UTC, merged