fix(ui5-input): fix Backspace on Input type=Number
SAP/ui5-webcomponents pull request #2864
Opened 2021-02-24 09:17 UTC by ilhan007

The "_handleInput" handler works with event from type "InputEvent" that never has "key" or "keyCode", that's why "isBackspace" or any other checks regarding pressed keys will always result in false. The solution is to execute the logic on keydown where the "KeyboardEvent" has "key" or "keyCode", store the result and later use it in "_handleInput".

FIXES: https://github.com/SAP/ui5-webcomponents/issues/2841

2021-02-24 14:32 UTC, fifoosid commented on packages/main/src/Input.js
> +	isBackSpacePressed() {
Do you really need this getter? You can just use the property

2021-02-25 14:22 UTC, fifoosid requested changes
https://user-images.githubusercontent.com/16850339/109166576-84f5f780-7785-11eb-9971-59a825548cf2.mov

This issue is introduced with the PR

2021-03-29 07:06 UTC, vladitasev approved these changes

2021-03-29 07:06 UTC, vladitasev commented on packages/main/src/Input.js
> +const rgxFloat = new RegExp(/(\+|-)?\d+(\.|,)\d+/);
Should we allow spaces? Or that's not valid for a number? In some countries they add a spce to delimit each thousands group.
There is also the scientific notation with the letter "E|e" also allowed, but probably not relevant.

2021-03-29 07:45 UTC, merged