chore: remove in language temporarily
SAP/ui5-webcomponents pull request #2879
Opened 2021-02-26 14:53 UTC by vladitasev

2021-03-01 08:16 UTC, ilhan007 approved these changes

2021-03-01 08:23 UTC, pskelin requested changes
separate change coming

2021-03-01 08:27 UTC, pskelin commented
suggested final fix: #2885

2021-03-11 10:09 UTC, vladitasev commented
Another change was merged instead.

2021-03-11 10:09 UTC, closed without merging