fix(ui5-date-picker): input now does not trigger value verification
SAP/ui5-webcomponents pull request #2922
Opened 2021-03-08 14:05 UTC by tsanislavgatev

fixes: https://github.com/SAP/ui5-webcomponents/issues/2827

2021-03-09 11:40 UTC, unazko commented on packages/main/src/DatePicker.js
>  		this.value = value;
Not sure if the `value `property should be updated, when `shouldChangeValueState `argument is `false`.
The sap.m.DatePicker control doesn't react in such case for comparison.

2021-03-09 11:47 UTC, unazko commented
There is another difference compared to the sap.m.DatePicker control behavior in relation to value validation.
The sap.m.DatePicker control keeps the last valid selected date, when invalid value is typed in the input and gets confirmed by pressing "Enter" keyboard key. The DatePicker component in the same case sets the selectedDates to empty array..

2021-04-01 15:50 UTC, ilhan007 commented
Hello @SAP/ui5-webcomponents-topic-b it's been more than 20 days after the initial review, can we help with the change/review?

2021-04-09 13:26 UTC, unazko commented
Looks good from my perspective.

2021-04-15 14:28 UTC, ilhan007 requested changes
shouldChangeValueState sounds a bit misleading, because the condition applies to changing of the value and the value state, I would name it updateValue

And as most of the use-cases are working with "true", I would make this default, and provide "false" just in one place

```js
async _onInputInput(event) {
		this._updateValueAndFireEvents(event.target.value, false, ["input"], false);
```

2021-04-16 09:05 UTC, ilhan007 approved these changes

2021-04-16 09:09 UTC, merged