feat(ui5-avatar-group): new slot overflowButton
SAP/ui5-webcomponents pull request #3037
Opened 2021-03-29 14:34 UTC by nnaydenow

Added new slot which allows to add custom overflow button.

Fixes: #2912

2021-03-29 14:49 UTC, vladitasev reviewed
IMO  looks great, almost ready to merge.

I would suggest 2 minor things:
 - You have 2 checks: _hasOverflowButton (which is this.overflowButton.length) and in many places in the code there is this.overflowButton[0]. Please merge these in a single getter: _customOverflowButton which returns null/undefined or this.overflowButton[0]. Then use this getter in place of both this.overflowButton.length and this.overflowButton[0]
  - in the html example, add arialabel to demonstrate the feature they wanted

2021-03-29 17:48 UTC, ilhan007 commented on packages/main/src/AvatarGroup.js
> +		 * @type {sap.ui.webcomponents.main.Button}
type HTMLElement

2021-03-29 17:51 UTC, ilhan007 requested changes
Check if it is fine in IE, to test on IE you have to build the project with yarn start:es5

2021-03-30 10:49 UTC, ilhan007 approved these changes

2021-03-30 10:55 UTC, merged