feat(ui5-avatar-group): Implement accessibility specification
SAP/ui5-webcomponents pull request #3154
Opened 2021-04-15 07:22 UTC by dobrinyonkov

Fixes: #2745

2021-04-21 11:55 UTC, fifoosid requested changes
From code POV, looks good to me. I have left some small comments regarding the docs. You can fix the build as well, because there are some lint errors:
![image](https://user-images.githubusercontent.com/16850339/115549622-876e5c80-a2b1-11eb-98ba-934293d190eb.png)

Once you fix the comments and get a review from @SAP/ui5-webcomponents-topic-p we can merge it.

2021-04-21 11:55 UTC, fifoosid commented on packages/main/src/Avatar.js
> +		 * <ul>
</ul>

2021-04-21 11:55 UTC, fifoosid commented on packages/main/src/Avatar.js
> +		 * <li><code> None - the aria-haspopup attribute will not be rendered.</li>
Add </code> to the end of every list item

2021-04-21 11:55 UTC, fifoosid commented on packages/main/src/AvatarGroup.js
> +		 * <ul>
</ul>

2021-04-21 11:55 UTC, fifoosid commented on packages/main/src/AvatarGroup.js
> +		 * <ul>
</ul>

2021-04-21 11:55 UTC, fifoosid commented on packages/main/src/AvatarGroup.js
> + * When focused the user can use the following keyboard
When focused, the ...

2021-04-22 07:28 UTC, fifoosid reviewed
There is a merge conflict, which needs to be resolved

2021-04-28 07:57 UTC, fifoosid reviewed
Looks good to me, someone from @SAP/ui5-webcomponents-topic-p should approve and we can merge

2021-05-14 08:48 UTC, ilhan007 submitted a review, later dismissed

2021-05-14 09:40 UTC, ilhan007 approved these changes

2021-05-14 09:42 UTC, merged