fix(ui5-bar): aria label added depending on the "design" property
SAP/ui5-webcomponents pull request #3161
Opened 2021-04-19 06:16 UTC by unazko

fix(ui5-bar): aria label added depending on the "design" property

Fixes #3020

2021-04-19 06:21 UTC, ilhan007 commented on packages/fiori/src/Bar.hbs
> +<div class="ui5-bar-root" aria-labelledby="{{accInfo.ariaLabelledBy}}"
shouldn't be "aria-label"?

2021-04-19 15:34 UTC, ilhan007 requested changes
Shouldn't be "aria-label"?

2021-04-20 11:25 UTC, unazko commented on packages/fiori/src/Bar.hbs
> +<div class="ui5-bar-root" aria-labelledby="{{accInfo.ariaLabelledBy}}"
Yes, that is right.

2021-04-21 07:06 UTC, ilhan007 approved these changes

2021-04-21 07:06 UTC, merged