feat(ui5-list): add keyboard handling docs
SAP/ui5-webcomponents pull request #3194
Opened 2021-04-28 11:38 UTC by dobrinyonkov

Fixes: #3089

2021-04-29 07:31 UTC, fifoosid requested changes

2021-04-29 07:31 UTC, fifoosid commented on packages/fiori/src/FlexibleColumnLayout.js
> + * <li>[SPACE, ENTER] - If focus is on the layout toggle button (arrow button) trigger the associated action (such as expand/collapse the column).</li>
If focus is on the layout toggle button (arrow button), once activated, it triggers the associated action (such as expand/collapse the column).

2021-04-29 07:31 UTC, fifoosid commented on packages/main/src/Avatar.js
> + * <li>[SPACE, ENTER] - Fires the <code>ui5-click</code> event if the <code>interactive</code> property is set to true.</li>
[SPACE, ENTER, RETURN]

2021-04-29 07:31 UTC, fifoosid commented on packages/main/src/Avatar.js
> + * <li>[SHIFT] - If [SPACE] or [ENTER],[RETURN] is pressed, releases the <code>ui5-avatar</code> without triggering the click event.</li>
If [SPACE] or [ENTER],[RETURN] is pressed, pressing [SHIFT] releases the <code>ui5-avatar</code> without triggering the click event.

2021-04-29 07:31 UTC, fifoosid commented on packages/main/src/Icon.js
> + * <li>[SHIFT] - If [SPACE] or [ENTER],[RETURN] is pressed, releases the <code>ui5-icon</code> without triggering the click event.</li>
If [SPACE] or [ENTER],[RETURN] is pressed, pressing [SHIFT] releases the <code>ui5-icon</code> without triggering the click event.

2021-05-11 08:03 UTC, ilhan007 requested changes

2021-05-12 06:40 UTC, ilhan007 approved these changes

2021-05-12 08:13 UTC, ilhan007 approved these changes

2021-05-14 08:42 UTC, merged