chore(ui5-avatar): rename backgroundColor property to backgroundDesign
SAP/ui5-webcomponents pull request #3222
Opened 2021-05-11 13:46 UTC by fifoosid

Part of #3107

2021-05-12 07:20 UTC, ilhan007 commented
make sure you merge the commit not with "chore" to have it in the release notes as it is breaking change

2021-05-12 07:33 UTC, ilhan007 submitted a review, later dismissed

2021-05-12 11:21 UTC, dobrinyonkov submitted a review, later dismissed

2021-05-12 11:43 UTC, ilhan007 approved these changes

2021-05-12 11:47 UTC, ilhan007 requested changes
@nnaydenow has concerns about the new name

2021-05-18 05:24 UTC, dobrinyonkov approved these changes

2021-05-18 06:39 UTC, ilhan007 approved these changes

2021-05-18 16:01 UTC, merged