feat(ui5-li-custom, ui5-li, ui5-li-groupheader): add accessibleName property
SAP/ui5-webcomponents pull request #3269
Opened 2021-05-18 12:02 UTC by nnaydenow

Work in progress

#3014

2021-05-25 12:28 UTC, dobrinyonkov commented
Works fine with screen readers and looks good from accessibility POV.

2021-05-31 09:51 UTC, fifoosid requested changes
Some minor docs to be fixed.

I was wondering why do you add the property to StandardListItem & CustomListItem as they extend ListItem and borrow the property?

2021-05-31 09:51 UTC, fifoosid commented on packages/main/src/CustomListItem.js
> +		 * Defines the text alternative of the <code>ui5-li</code>.
Defines the text alternative of the component

2021-05-31 09:51 UTC, fifoosid commented on packages/main/src/CustomListItem.js
> +		 * If not provided a default text alternative will be set, if present.
<b>Note:</b> If not provided a default text alternative will be set, if present.

2021-05-31 09:51 UTC, fifoosid commented on packages/main/src/GroupHeaderListItem.js
> +		 * Defines the text alternative of the <code>ui5-li</code>.
Same here

2021-05-31 09:51 UTC, fifoosid commented on packages/main/src/StandardListItem.js
> +		 * Defines the text alternative of the <code>ui5-li</code>.
Same here

2021-05-31 11:32 UTC, nnaydenow commented
Hi @fifoosid ,

We add this property to each component because it is not confirmed to other components that extends the ListItem. We are doing this to not affect them.

2021-05-31 11:51 UTC, fifoosid approved these changes

2021-05-31 11:52 UTC, merged