fix(ui5-upload-collection-item): fixed keyboard navigation
SAP/ui5-webcomponents pull request #3327
Opened 2021-05-27 12:50 UTC by TeodorTaushanov

- rename on Enter
- keep edit mode when focus out
- shift+tab on "edit" button doesn't act as it is pressed
- when edit and press "esc" button, the focus goes to the "edit" button
- editing is working and after pressing "esc" key

2021-05-28 15:22 UTC, gmkv requested changes
If the focus is on the Edit button of the item, pressing Enter makes it editable, then immediately changes it back to non-editable.

Activating the "Rename" button with Space doesn't do anything. This "Space" press is prevented in `ListItem.js` in the function `_onkeydown`. Same for "Cancel".

Run `yarn hash` and add the changed hash file to the commit.

2021-06-07 14:20 UTC, gmkv approved these changes

2021-06-08 13:50 UTC, dimovpetar approved these changes

2021-06-15 09:18 UTC, fifoosid approved these changes

2021-06-15 09:19 UTC, merged