refactor(i5-responsive-popover): API enhancements
SAP/ui5-webcomponents pull request #3363
Opened 2021-05-31 06:34 UTC by kskondov

BREAKING_CHANGE: Removed "open" method

2021-06-01 18:28 UTC, gmkv commented
The commit message still says "i5-responsive-popover"

2021-06-08 14:20 UTC, dimovpetar approved these changes

2021-06-08 14:22 UTC, dimovpetar requested changes
Replace `simpleRP.open(btnSimpleRP)` with `simpleRP.openBy(btnSimpleRP)` in ResponsivePopover.html

2021-06-21 07:00 UTC, dimovpetar approved these changes

2021-06-21 08:22 UTC, ilhan007 approved these changes

2021-06-21 08:31 UTC, merged