fix(ui5-link): rename wrap property to wrappingType
SAP/ui5-webcomponents pull request #3380
Opened 2021-06-02 15:40 UTC by gmkv

Part of #3107

- fixed documentation errors

BREAKING_CHANGE: property wrap has been renamed to wrappingType and its type has changed

2021-06-03 05:21 UTC, tsanislavgatev commented
I'm okay with the ui5-link change.

2021-06-03 06:56 UTC, fifoosid requested changes

2021-06-03 06:56 UTC, fifoosid commented on packages/main/src/Link.js
> +			type: String,
The enum that is used for the ```wrappingType``` property of the ```ui5-title``` should be used here as well

2021-06-04 13:52 UTC, ilhan007 commented on packages/main/src/Link.js
> +		 * @type {string}
Yes, this becomes a little odd, the type in the JSDoc should be changed
@type {string} -> @type {WrappingType} and both the type and the name of the prop will become "WrappingType":
```js
/**
@type {WrappingType}
*/
 wrappingType: {
			type: WrappingType,
			defaultValue: WrappingType.None,
		},
```

Not sure again, maybe we have to consider naming the enum "Wrapping".

2021-06-04 14:30 UTC, ilhan007 requested changes

2021-06-04 14:30 UTC, ilhan007 commented on packages/main/src/Link.js
> +		 * @type {string}
Small update needed: @ type {string} -> @ type {WrappingType}

2021-06-07 07:38 UTC, gmkv commented on packages/main/src/Link.js
> +		 * @type {string}
Done

2021-06-07 08:00 UTC, ilhan007 approved these changes

2021-06-07 08:02 UTC, merged