refactor(ui5-radio-button): change tag name
SAP/ui5-webcomponents pull request #3405
Opened 2021-06-07 10:38 UTC by gmkv

Part of #3107

BREAKING_CHANGE: component's tag name `ui5-radiobutton` has been changed to `ui5-radio-button`

2021-06-10 12:26 UTC, fifoosid requested changes

2021-06-10 12:26 UTC, fifoosid commented on packages/fiori/src/NotificationListItem.js
> +		 * Defines the elements, displayed in the footer of the of the <code>ui5-li-notification</code>.
of the component

2021-06-10 12:26 UTC, fifoosid commented on packages/main/src/RadioButton.js
> +		checked: {
please add a since tag

2021-06-10 12:26 UTC, fifoosid commented on packages/main/src/RadioButton.js
> +		change: {},
please add a since tag

2021-06-21 07:48 UTC, ilhan007 approved these changes

2021-06-21 09:03 UTC, dimovpetar requested changes
Also rename the CSS variables in RadioButton-parameters.css

2021-06-21 10:02 UTC, gmkv commented
> Also rename the CSS variables in RadioButton-parameters.css

Done. Renamed all related vars (some were _ui5_rb_..., others - _ui5_radiobutton).

2021-06-21 10:17 UTC, dimovpetar approved these changes

2021-06-21 11:51 UTC, merged