fix(ui5-popup) page scrolling up if more than one dialog is open
SAP/ui5-webcomponents pull request #3431
Opened 2021-06-15 16:19 UTC by kskondov

Fixes #3355

2021-06-16 06:28 UTC, gmkv requested changes
Can you write a test for this?

2021-06-23 06:43 UTC, kskondov commented
> Can you write a test for this?

Done

2021-06-29 17:04 UTC, gmkv approved these changes

2021-07-01 12:06 UTC, ilhan007 requested changes
Could you just briefly explain in the commit message how you fix the issue.

2021-07-06 14:23 UTC, vladitasev approved these changes

2021-07-06 14:24 UTC, merged