fix: rename aria-label to accessible-name
SAP/ui5-webcomponents pull request #3449
Opened 2021-06-21 09:26 UTC by fifoosid

Part of #3107

BREAKING_CHANGE: ```ariaLabell``` property is renamed to ```accessible-name``` for the following components:

- Button
- Timeline
- WIzard
- WizardStep
- FlexibleColumnLayout
- Card
- CheckBox
- ComboBox
- DatePicker
- Dialog
- Input
- Link
- List
- Panel
- Popover
- Popup
- RatingIndicator
- Select
- StepInput
- TextArea
- AvatarGroup

2021-06-23 05:33 UTC, elenastoyanovaa requested changes
Could you change the jsdoc of the accessible name for all components with something like the description for the panel https://sap.github.io/ui5-webcomponents/master/playground/components/Panel/ ?

2021-06-28 09:43 UTC, ilhan007 submitted a review, later dismissed

2021-07-09 12:50 UTC, elenastoyanovaa requested changes

2021-07-15 10:15 UTC, fifoosid commented on packages/base/src/util/AriaLabelHelper.js
>  	if (!el.ariaLabelledby) {
Yes, it is. Based on this check, ```getAriaLabelledByTexts```(line 12) is called.

2021-07-19 07:48 UTC, ilhan007 approved these changes

2021-07-21 07:08 UTC, elenastoyanovaa approved these changes

2021-07-21 08:40 UTC, merged