feat(ui5-combobox): add suggestions grouping
SAP/ui5-webcomponents pull request #3469
Opened 2021-06-25 05:23 UTC by ndeshev

Enable users to set items to groups. Groups are visually identified in the suggestions list by group headers. For group headers a new component is introduced - ComboBoxGroupItem which extends the SuggestionGroupItem one and adds a group name property to it.

2021-06-28 13:28 UTC, fifoosid requested changes
Add ```ui5-cb-group-item``` to the appenddocs tag in ```ComboBox.js```
Add a sample in ```ComboBox.sample.html```

2021-06-28 13:28 UTC, fifoosid commented on packages/main/src/ComboBoxGroupItem.js
> +	get groupItem() {
```isGroupItem``` fits better, because it returns a boolean

2021-06-28 13:28 UTC, fifoosid commented on packages/main/src/ComboBox.js
> +			let nextItemIdx = ++idx;
You can just use ```idx```, ```nextItemIdx``` is not needed

2021-06-28 13:37 UTC, MapTo0 reviewed
I suggest we deep test this changed once the value change pull request get merged

2021-06-28 13:37 UTC, MapTo0 commented on packages/main/src/ComboBox.js
> +		const currentlyFocusedItem = this.items.find(item => item.focused === true);
just `=> item.focused` its a predicate anyway

2021-06-29 10:12 UTC, fifoosid approved these changes
LGTM now, someone from @SAP/ui5-webcomponents-topic-rl  should approve and we can merge it

2021-06-29 13:46 UTC, MapTo0 submitted a review, later dismissed
/ ---------- /

1. type "b"
2. arrow down - b should be removed

/ ---------- /

1. Type "a"
2. items gets filtered, but not autocompleted

2021-06-29 13:46 UTC, MapTo0 commented on packages/main/src/ComboBox.js
> +		return this.items.filter((item, idx, allItems) => ComboBox._filterGroupItems(item, ++idx, allItems, filteredItems) || filteredItems.indexOf(item) !== -1);
that reads hard

2021-06-29 13:53 UTC, MapTo0 commented
Actually, there is a double focus all the time :D

2021-06-30 04:29 UTC, ndeshev commented
There is no double focus for me?
When a group item is reached with the keyboard the typed in value should not be cleared, as it is in UI5. 
The autocomplete also is working fine, this is strange. please pull the last changes, something is not right.

2021-07-01 06:29 UTC, hristop commented
lgtm, I think we can merge when someone with rights approve the change

2021-07-01 10:38 UTC, ilhan007 approved these changes

2021-07-01 10:39 UTC, merged