fix(ui5-step-input): firing step input once when value is deleted
SAP/ui5-webcomponents pull request #3474
Opened 2021-06-25 09:04 UTC by tsanislavgatev

fixes: https://github.com/SAP/ui5-webcomponents/issues/3457

2021-06-25 12:21 UTC, fifoosid reviewed
This fix breaks the following case:
Enter 0 as value
Focus out the step input(event is thrown)
Delete the value
Focus out
Value is now empty string (should be 0)

2021-06-28 08:46 UTC, fifoosid requested changes
This is a workaround for the previous comment and the following case is not handled:

Start with Stepinput with some value(for example: 5)
Mark the value & delete it
Focus out
The value 0 is restored(The value 5 should be restored).

2021-06-29 06:56 UTC, tsanislavgatev commented
> This is a workaround for the previous comment and the following case is not handled:
> 
> Start with Stepinput with some value(for example: 5)
> Mark the value & delete it
> Focus out
> The value 0 is restored(The value 5 should be restored).

The current behaviour is when you have any value and you delete it( the state is empty string), then you focus out, you have 0 as value.

2021-06-30 14:09 UTC, fifoosid approved these changes

2021-07-01 08:11 UTC, merged