feat(ui5-select): Change focus of options on keypress
SAP/ui5-webcomponents pull request #3538
Opened 2021-07-26 08:01 UTC by IlianaB

Implement changing of focus of options on keypress - typing letters now allows focusing different options of the ui5-select.

Fixes: #3476

2021-07-26 10:48 UTC, ilhan007 commented
Eslint errros, you can run yarn lint locally in the root of the project:

```js
/home/travis/build/SAP/ui5-webcomponents/packages/main/src/Select.js
  480:3  error  'sText' is never reassigned. Use 'const' instead          prefer-const
  494:7  error  'oItemToSelect' is never reassigned. Use 'const' instead  prefer-const
  496:1  error  Expected indentation of 2 tabs but found 3                indent
  497:1  error  Expected indentation of 3 tabs but found 4                indent
  499:1  error  Expected indentation of 3 tabs but found 4                indent
  501:1  error  Expected indentation of 3 tabs but found 4                indent
  502:1  error  Expected indentation of 4 tabs but found 5                indent
  503:1  error  Expected indentation of 3 tabs but found 4                indent
  504:1  error  Expected indentation of 2 tabs but found 3                indent
✖ 9 problems (9 errors, 0 warnings)
  8 errors and 0 warnings potentially fixable with the `--fix` option.
  ```
  
 In addition, you can rebase with the master, as some randomly failing tests have been fixed. Could avoid some build failures, that have nothing to do with this change.

2021-07-26 11:15 UTC, IlianaB commented
> Eslint errros, you can run yarn lint locally in the root of the project:
> 
> ```js
> /home/travis/build/SAP/ui5-webcomponents/packages/main/src/Select.js
>   480:3  error  'sText' is never reassigned. Use 'const' instead          prefer-const
>   494:7  error  'oItemToSelect' is never reassigned. Use 'const' instead  prefer-const
>   496:1  error  Expected indentation of 2 tabs but found 3                indent
>   497:1  error  Expected indentation of 3 tabs but found 4                indent
>   499:1  error  Expected indentation of 3 tabs but found 4                indent
>   501:1  error  Expected indentation of 3 tabs but found 4                indent
>   502:1  error  Expected indentation of 4 tabs but found 5                indent
>   503:1  error  Expected indentation of 3 tabs but found 4                indent
>   504:1  error  Expected indentation of 2 tabs but found 3                indent
> ✖ 9 problems (9 errors, 0 warnings)
>   8 errors and 0 warnings potentially fixable with the `--fix` option.
> ```
> 
> In addition, you can rebase with the master, as some randomly failing tests have been fixed. Could avoid some build failures, that have nothing to do with this change.

Done. It seems like have executed the eslint check in the wrong directory.

2021-07-27 10:26 UTC, PetyaMarkovaBogdanova submitted a review, later dismissed
Looks good to me! Works fine with different scenarios.

2021-07-27 11:00 UTC, fifoosid requested changes

2021-07-28 14:25 UTC, IlianaB commented on packages/main/src/Select.js
> +		this._sTypedChars = "";
Fixed at all places now.

2021-07-28 14:26 UTC, IlianaB commented on packages/main/src/Select.js
> +		} else if (event.keyCode >= 65 && event.keyCode <= 90) {
Not specified in the BLI, but improved now, as, yes, it makes a lot more sense! Thanks.

2021-07-31 07:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/ui5-webcomponents?pullRequest=3538) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAP/ui5-webcomponents?pullRequest=3538) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/ui5-webcomponents?pullRequest=3538) it.</sub>

2021-08-02 13:07 UTC, fifoosid approved these changes

2021-08-02 13:08 UTC, merged