fix(ui5-color-picker): focus outline is properly visualized
SAP/ui5-webcomponents pull request #3648
Opened 2021-08-12 19:47 UTC by unazko

- The color palette swatches focus outline is properly
according to the global focus visual concept.

Fixes: #3521

2021-08-13 07:57 UTC, tsanislavgatev commented
With removing of the styles we now receive a blue outline which is the browser provided focus. We need this to prevent it:
:host(:not([_disabled])) .ui5-cp-item:focus{
	outline: none;
}

:host(:not([_disabled]):focus) .ui5-cp-item {
	pointer-events: none;
	outline: none;
}

2021-08-13 11:19 UTC, fifoosid requested changes
Just switch the two colours and we can merge it.
Reason:
Current result:
![image](https://user-images.githubusercontent.com/16850339/129349619-d8e9e148-fa3c-4835-bb51-9001580186ba.png)

Expected behaviour:
![image](https://user-images.githubusercontent.com/16850339/129349604-36aff169-b869-4e5b-a63e-e8b558339137.png)

2021-08-13 11:19 UTC, fifoosid commented on packages/main/src/themes/ColorPaletteItem.css
> +	border: 0.0625rem solid black;
white

2021-08-13 11:19 UTC, fifoosid commented on packages/main/src/themes/ColorPaletteItem.css
> +	border: 0.0625rem dotted white;
black

2021-08-13 14:36 UTC, unazko commented on packages/main/src/themes/ColorPaletteItem.css
> +	border: 0.0625rem solid black;
done

2021-08-13 14:36 UTC, unazko commented on packages/main/src/themes/ColorPaletteItem.css
> +	border: 0.0625rem dotted white;
done

2021-08-17 08:05 UTC, fifoosid approved these changes

2021-08-17 08:06 UTC, merged