fix(ui5-timeline): elements with role option have a parent element with role listbox
SAP/ui5-webcomponents pull request #3650
Opened 2021-08-12 22:47 UTC by unazko

Fixes: #3459

2021-08-13 16:55 UTC, ghristanov requested changes
I see that you're following webcomponents' screen reader wiki with some improvements to it. However, looking at the current implementation as well as our original UI5 specification, several questions arise.
 
Timeline's specification in openUI5 is very clean and makes perfect logic, orbiting around `list`+`listem`_s_/`tree`+`treeitem`_s_. The final implementation of both projects however is `listbox`+`option`_s_, which isn't that logical on first glance (could TimelineItems even be selected?). What's even stranger is that WC's wiki differs from the original specification and suggests sticking with the `listbox`+`option`_s_ approach - do you know if there's any reason for this?

But let’s look past that. We immediately stumble on another problem. Using the suggested `<ul role="listbox">` for timeline's list and `<div role="option">` for the bubble will result in `listbox` > `listitem` > _wrapping_ `div`_s_ > `option`. Several big no-no’s here. Your fix makes it a tad better: `listbox` > `option` > `listbox` > `option`, which helps with the invalid parent/children roles, but it would mean that A) you'll have a `listbox` with `option`_s_ being the `option` of another `listbox` and B) each timeline item will be a separate `listbox` itself and for `option`_s_ you'll have its icon and its bubble - sounds pretty awkward.

If this isn't an urgent issue, then I'll recommend bringing these problems to WC's PO, so that any conceptual questions could be clarified and then we could change what's necessary in the control.

Hope this helps!

2021-08-13 20:12 UTC, unazko commented
Thank you, Georgi,

I was wandering about the TimeLineItems my self, as they can't be selected.
The same applies for the bubble and the icon in the list items as well.
I've added @ilhan007 as a reviewer so we could discuss those topics later on.

2021-10-01 10:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/ui5-webcomponents?pullRequest=3650) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/SAP/ui5-webcomponents?pullRequest=3650) before we can accept your contribution.<br/>**16** out of **19** committers have signed the CLA.<br/><br/>:white_check_mark: fifoosid<br/>:white_check_mark: TeodorTaushanov<br/>:white_check_mark: niyap<br/>:white_check_mark: nnaydenow<br/>:white_check_mark: dobrinyonkov<br/>:white_check_mark: Todor-ads<br/>:white_check_mark: vladitasev<br/>:white_check_mark: MapTo0<br/>:white_check_mark: tsanislavgatev<br/>:white_check_mark: unazko<br/>:white_check_mark: ilhan007<br/>:white_check_mark: xpr0gamers<br/>:white_check_mark: ndeshev<br/>:white_check_mark: Lukas742<br/>:white_check_mark: ajinkyapatil8190<br/>:white_check_mark: terezamch<br/>:x: PetyaMarkovaBogdanova<br/>:x: kskondov<br/>:x: hristop<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/ui5-webcomponents?pullRequest=3650) it.</sub>

2021-10-01 10:09 UTC, closed without merging

2021-10-01 10:10 UTC, unazko commented
Merge operation got messed up.