fix(ui5-select): correct screen reader speech out when popover is opened
SAP/ui5-webcomponents pull request #3705
Opened 2021-08-20 12:35 UTC by nnaydenow

Position of the current focused option is not read when the dropdown of the ui5-select is opened.

In addition disabled options are not displayed according to the latest control specification. 

#3617

2021-09-01 06:20 UTC, dobrinyonkov commented on packages/main/src/Select.js
> +		this._filteredItems[oldIndex].selected = false;
Can we do the same here : 
`const options = this._filteredItems;`

2021-09-14 10:31 UTC, fifoosid requested changes
Eslint is failing:
![image](https://user-images.githubusercontent.com/16850339/133242179-2f001502-11eb-427d-8dc0-3a1e6203a1a7.png)

2021-09-15 12:26 UTC, fifoosid approved these changes
LGTM, someone from @SAP/ui5-webcomponents-topic-p should also approve and we can merge it.

2021-09-20 08:13 UTC, dobrinyonkov approved these changes

2021-09-20 08:21 UTC, merged