feat(ui5-illustrated-message): add TNT illustration set
SAP/ui5-webcomponents pull request #3857
Opened 2021-09-07 17:10 UTC by nnaydenow

2021-09-08 08:19 UTC, fifoosid requested changes
You should fix the eslint

2021-09-08 13:22 UTC, fifoosid approved these changes

2021-09-08 13:22 UTC, merged

2021-09-10 06:03 UTC, vladitasev reviewed
It's just small things, mostly naming

2021-09-10 06:03 UTC, vladitasev commented on packages/tools/components-package/nps.js
> -				default: `node "${LIB}/create-illustrations/index.js" ${illustrationsPath} dist/illustrations`
you don't need a `default` field if it's just one command, you can pass it directly to the `illustrations` property

2021-09-15 11:16 UTC, nnaydenow commented
#3613