docs: new docs
SAP/ui5-webcomponents pull request #3890
Opened 2021-09-10 06:16 UTC by vladitasev

wip

2021-09-27 14:09 UTC, fifoosid requested changes
It would be easier to build the playground if each section is in separate folder, rather than having the name of the section in the title

2021-10-04 08:02 UTC, pskelin submitted a review, later dismissed

2021-10-04 08:06 UTC, fifoosid approved these changes

2021-10-04 10:07 UTC, fifoosid approved these changes

2021-10-04 10:07 UTC, merged