fix(ui5-file-uploader): Button is activated with Enter/Space key with screen reader virtual cursor
SAP/ui5-webcomponents pull request #3944
Opened 2021-09-16 15:58 UTC by Todor-ads

Upload files button now is activated with Enter/Space key with screen reader virtual cursor  ON"

2021-09-17 07:16 UTC, ilhan007 commented
Is that the issue being fixed here: https://github.com/SAP/ui5-webcomponents/issues/3767

2021-09-17 07:23 UTC, ilhan007 requested changes
With this change when you click on the input or the button in a standard none screen reader mode,
the browse files dialog opens two times. 

Open
http://localhost:8080/test-resources/pages/FileUploader.html

- use the first input
- click the input -> the dialog opens
- press cancel > notice that the dialog opens for a second time

2021-09-20 06:33 UTC, NHristov-sap approved these changes

2021-09-20 11:09 UTC, ilhan007 approved these changes

2021-09-20 11:10 UTC, merged