fix(ui5-link): Added underlining in the regular state in hcb / hcw
SAP/ui5-webcomponents pull request #3960
Opened 2021-09-20 08:37 UTC by Todor-ads

fix(ui5-link): Added underlining in the regular state in hcb / hcw

2021-09-20 08:45 UTC, ilhan007 requested changes
Is sap_fiori_3_hcb and sap_fiori_3_hcw fine? Because they are far more important, almost noone is using sap_belize

2021-09-20 08:59 UTC, ilhan007 commented on packages/main/src/themes/sap_belize_hcb/parameters-bundle.css
>  @import "../base/Link-parameters.css";
remove

2021-09-20 14:08 UTC, fifoosid approved these changes

2021-09-21 06:35 UTC, NHristov-sap approved these changes

2021-09-21 07:05 UTC, merged