(ui5-multi-combobox): Improve arrow navigation functionality
SAP/ui5-webcomponents pull request #3970
Opened 2021-09-21 12:15 UTC by ndeshev

Issue: #3790

2021-09-27 11:35 UTC, MapTo0 requested changes
Open http://localhost:8080/test-resources/pages/MultiComboBox.html
Go to Success MCB
Arrow down -> exception is thrown

2021-09-28 06:11 UTC, ndeshev commented
Note:
There is a separate issue for arrow navigation enablement when the suggestions picker is closed - #4010

2021-09-28 11:12 UTC, niyap requested changes
What about the N-more functionality. Now, it does not work at all. When the N-more popover is open, the focus is lost, you are not able to navigate at all. I think that, when the N-more popover is open, the focus should be in the input field and then you should be able to navigate via ARROW UP/DOWN through the selected items

2021-09-29 06:01 UTC, niyap requested changes
Check the "Validating input and placeholder" sample in the test page. Type "C" then something invalid for example "r". Try to navigate via Arrow Down while the value state is dynamically changed to "Error" for a second -> it is not possible, the focus remains in the input field. In the master, at least the focus can be moved to the suggestion. In UI5 it works as expected -> the focus is moved first to the value state header, then t the suggestions

2021-09-30 12:04 UTC, niyap commented on packages/main/test/specs/MultiComboBox.spec.js
> +			assert.equal(await mcb.getProperty("focused"), false, "The input should be focused");
should **NOT** be focused?

2021-09-30 12:07 UTC, niyap commented on packages/main/test/specs/MultiComboBox.spec.js
> +			assert.equal(await listItem.getProperty("focused"), false, "The first item is focused");
is **NOT**

2021-09-30 12:10 UTC, niyap commented on packages/main/test/specs/MultiComboBox.spec.js
> +			await icon.click();
Why in all the tests, the dropdown is open via the arrow. It will be better if we test the other ways as well (Alt + Down/F4)

2021-09-30 13:28 UTC, niyap approved these changes

2021-09-30 13:29 UTC, MapTo0 approved these changes

2021-09-30 13:30 UTC, merged