(ui5-input, ui5-multi-input): Improve arrow navigation functionality
SAP/ui5-webcomponents pull request #3976
Opened 2021-09-23 05:08 UTC by ndeshev

Issue: #3790

2021-10-05 06:17 UTC, niyap requested changes
1. Open the test page. Check the "Input suggestions with ui5-li" where inactive items are presented. On "Enter" key now the popover is closed, which is not correct, as well as in the master that behaviour is not presented.
2. On the same sample, the same inactive items have strange visualisation in my opinion. Navigating via mouse there is no hover state, as well as they could not be selected. Reaching them via ARROW Down key, they have the same visualisation as a normal active item. Please discuss it with the team and created an issue in order to fix it.
3. Open the sample "Input suggestions with grouping", type "C" and navigate via Arrow Down to the group's header -  the value is cleared which is not correct
4. Go to "Input with valueState and Dynamic suggestions", type "A" in order to open the dropdown, navigate to the first/second item via Arrow Down, then navigate back to the input field via Arrow Up, then continue pressing Arrow Up and notice how there is visual focus over the value state header which appears/disappears on each arrow up in addition to the visual focus in the input field
5. In addition to the previous point, if you press many times Arrow Up and stop in a moment that the visual focus is presented only in the input field. Then press Arrow Down - you can notice how the visual focus is directly moved on the first suggestion, skipping both the value state header and the group's header.
6. On the same sample, type "A" again and navigate to the group's header. Press "Enter" - the dropdown is closed. The behaviour is not presented in the master.

2021-10-08 06:52 UTC, ndeshev commented
Also fixes #4029

2021-11-02 07:52 UTC, ndeshev commented on packages/main/src/Input.js
> +		_isValueStateFocused: {
Let's leave it this way, because in ComboBox it is already merge as _isValueStateFocused

2021-11-02 07:53 UTC, ndeshev commented on packages/main/src/features/InputSuggestions.js
> +		if (hasValueState && previousSelectedIdx === null && !this.component._isValueStateFocused) {
I thought about it but couldn't come up with a good solution, different properties are set depending on different conditions handled by the focus and nav logic

2021-11-02 11:00 UTC, niyap approved these changes

2021-11-02 11:23 UTC, elenastoyanovaa approved these changes

2021-11-02 11:33 UTC, merged