fix(ui5-card): allow accessibleName and accessibleNameRef to be used
SAP/ui5-webcomponents pull request #4021
Opened 2021-09-29 15:10 UTC by GerganaKremenska

accessible-name and accessible-name-ref can be used. 

FIXES: #3681
FIXES: #3730

2021-10-01 11:54 UTC, gmkv commented on packages/main/src/Card.js
> +	get _getAriaLabelledby() {
better to name this method _getAriaLabel as it concerns the `aria-label` attribute

2021-10-04 07:56 UTC, fifoosid requested changes
The title of the PR says that two properties are introduced, but as much as I can see, only one is added to the metadata

2021-10-04 07:56 UTC, fifoosid commented on packages/main/src/Card.js
> +		 * @since 1.0.0-rc.15
rc16

2021-10-04 07:56 UTC, fifoosid commented on packages/main/src/Card.js
> +         * <b>Note:</b> <code>accessibleName</code> is required for <ui5-card>, it provides unique name for the card region.
is required for the component, it ...

2021-10-04 08:01 UTC, GerganaKremenska commented
> The title of the PR says that two properties are introduced, but as much as I can see, only one is added to the metadata

I forgot to update the title of the PR it is done now.

2021-10-04 10:55 UTC, fifoosid reviewed
Everything looks fine, but you should merge the master branch for the build to pass

2021-10-04 12:58 UTC, fifoosid approved these changes

2021-10-05 07:19 UTC, dimovpetar requested changes

2021-10-05 07:19 UTC, dimovpetar commented on packages/main/test/specs/Card.spec.js
> +    });
Please indent with tabs here

2021-10-05 07:19 UTC, dimovpetar commented on packages/main/src/Card.js
> +		const effectiveAriaLabel = getEffectiveAriaLabelText(this) ? ` ${getEffectiveAriaLabelText(this)}` : "";
Avoid calling `getEffectiveAriaLabelText(this)` twice

2021-10-05 07:19 UTC, dimovpetar commented on packages/main/src/Card.js
> +		 * <b>Note:</b> <code>accessibleName</code> is required for the component, it provides unique name for the card region.
How about:
<b>Note:</b><code>accessibleName</code> is used as the name of the card region and should be unique.

2021-10-05 11:19 UTC, dimovpetar approved these changes

2021-10-05 11:50 UTC, fifoosid approved these changes

2021-10-05 11:50 UTC, merged