docs(ui5-multi-input):  Improved samples
SAP/ui5-webcomponents pull request #4198
Opened 2021-10-27 12:07 UTC by d3xter666

Fixes: https://github.com/SAP/ui5-webcomponents/issues/3765

2021-11-03 07:24 UTC, niyap requested changes
One thing that I do not like in the current sample. If you type "a" and then select a suggestion via mouse - two tokens are created. One with "a" and one with the suggestion selected. In my opinion that should not happen. Something more, the behaviour is presented only initially, if you do the described interaction and then delete the created tokens and do it again, the issue is not reproducible. Moreover, the issue is not reproducible, if you type a character and then select a suggestion via navigating in the suggestions list using keyboard.

2021-11-03 14:26 UTC, d3xter666 commented
Hi @niyap ,

This is a separate issue, which, unfortunately, appears here. It would be fixed with: https://github.com/SAP/ui5-webcomponents/pull/4129

Cheers

2021-12-08 08:58 UTC, niyap approved these changes

2021-12-13 11:12 UTC, ilhan007 commented
I see the change is approved. If the review is completed, you can squash and merge the PR.

2021-12-13 14:04 UTC, merged