docs(ui5-date-range-picker): inherited methods documentation is improved
SAP/ui5-webcomponents pull request #4339
Opened 2021-11-15 15:40 UTC by unazko

The inherited methods from ui5-date-picker component, which are not in use
in the ui5-date-range-picker component are pointed out in the documentation.

2021-11-16 09:34 UTC, a-z-ivanov requested changes

2021-11-16 09:34 UTC, a-z-ivanov commented on packages/main/src/DatePicker.js
> + * then users can increment or decrement the JS date object referenced by <code>dateValue</code> property
increment or decrement the date

2021-11-25 07:53 UTC, a-z-ivanov approved these changes
I approve

2021-11-25 16:02 UTC, BorisDafov approved these changes

2021-11-25 17:12 UTC, merged