feat(ui5-tree-item): add indeterminate state
SAP/ui5-webcomponents pull request #4397
Opened 2021-11-29 15:06 UTC by nnaydenow

Closes: #3618

2021-11-30 14:23 UTC, kineticjs commented on packages/main/src/TreeItem.js
> +		* Defines whether the selection of tree node should be display as partially selected.
minor: "should be displayed"
I guess a UA will review the texts in the end anyway?

2021-11-30 16:09 UTC, xtatica requested changes

2021-11-30 16:09 UTC, xtatica commented on packages/main/src/TreeItem.js
> +		* Defines whether the selection of tree node should be display as partially selected.
```suggestion
		* Defines whether the selection of a tree node is displayed as partially selected.
```

2021-11-30 16:09 UTC, xtatica commented on packages/main/src/TreeItem.js
> +		* interaction and the resulting visual state depends on the values of the <code>indeterminate</code>
```suggestion
		* interaction, meaning that the resulting visual state depends on the values of the <code>indeterminate</code>
```

2021-11-30 16:09 UTC, xtatica commented on packages/main/src/TreeItem.js
> +		* <li> If the tree node is selected and indeterminate, it will be displayed as partially selected
```suggestion
		* <li> If a tree node has both <code>selected</code> and <code>indeterminate</code> set to <code>true</code>, it is displayed as partially selected.
```

2021-11-30 16:09 UTC, xtatica commented on packages/main/src/TreeItem.js
> +		* <li> If the tree node is selected and it is not indeterminate, it will be displayed as selected
```suggestion
		* <li> If a tree node has <code>selected</code> set to <code>true</code> and <code>indeterminate</code> set to <code>false</code>, it is displayed as selected.
```

2021-11-30 16:09 UTC, xtatica commented on packages/main/src/TreeItem.js
> +		* <li> If the tree node is not selected, it will be displayed as not selected regardless value of the indeterminate attribute
```suggestion
		* <li> If a tree node has <code>selected</code> set to <code>false</code>, it is displayed as not selected regardless of the value of the <code>indeterminate</code> property.
```

2021-11-30 16:09 UTC, xtatica commented on packages/main/src/TreeItem.js
> +		* <b>Note:</b> This property will take affect only when the <code>ui5-tree</code> is in <code>MultiSelect</code> mode.
```suggestion
		* <b>Note:</b> This property takes effect only when the <code>ui5-tree</code> is in <code>MultiSelect</code> mode.
```

2021-12-01 13:17 UTC, kineticjs approved these changes

2021-12-01 14:22 UTC, xtatica approved these changes

2021-12-01 14:23 UTC, kineticjs approved these changes

2021-12-06 12:17 UTC, nnaydenow commented
Hi @ilhan007,

Can you take a look before merging it?

2021-12-14 12:35 UTC, merged