feat(ui5-flexible-column-layout): new property accessibilityRoles
SAP/ui5-webcomponents pull request #4446
Opened 2021-12-07 12:23 UTC by dobrinyonkov

Summary:

1. New property accessibilityRoles added to set custom roles on the containers (start & mid & end columns + arrow containers);
2. Add 2 additional properties to the accessibilityTexts object to set custom labels on the arrow containers);
3. Hidden text elements are placed inside the columns to ensure that all elements are contained by landmarks;

Fixes: #3804, #3796

2021-12-07 13:23 UTC, nnaydenow approved these changes
Code seems to be clear. Let's wait @xtatica and @elenastoyanovaa to approve documentation changes.

2021-12-09 12:21 UTC, elenastoyanovaa approved these changes

2021-12-09 13:51 UTC, xtatica requested changes

2021-12-09 13:51 UTC, xtatica commented on docs/2-advanced/07-accessibility.md
> +| `accessibleName`                            | `aria-label`    | Defines the text alternative of the component. If not provided a default text alternative will be set, if present.
```suggestion
| `accessibleName`                            | `aria-label`    | Defines the text alternative of the component. If not provided, a default text alternative is set, if present.                                                                                  |
```

2021-12-09 13:51 UTC, xtatica commented on docs/2-advanced/07-accessibility.md
> +| `accessibleNameRef`                         | `aria-label`    | Alternative for `aria-labelledby`. Receives id (or many ids) of the elements that serve as labels of the component. Those labels are
```suggestion
| `accessibleNameRef`                         | `aria-label`    | Alternative for `aria-labelledby`. Receives ID (or many IDs) of the elements that serve as labels of the component. Those labels are passed as a concatenated string to the `aria-label` attribute. |
```

2021-12-09 13:51 UTC, xtatica commented on docs/2-advanced/07-accessibility.md
> +| `accessibilityTexts` (FlexibleColumnLayout) | `aria-label`    | An object of strings that define several additional accessibility texts for even further customization.
```suggestion
| `accessibilityTexts` (FlexibleColumnLayout) | `aria-label`    | An object of strings that define several additional accessibility texts for further customization.                                                                                             |
```

2021-12-09 13:51 UTC, xtatica commented on docs/2-advanced/07-accessibility.md
> +| `accessibilityRoles` (FlexibleColumnLayout) | `role`          | An object of strings that define several additional accessibility roles for even further customization.
```suggestion
| `accessibilityRoles` (FlexibleColumnLayout) | `role`          | An object of strings that define several additional accessibility roles for further customization.                                                                                             |
```

2021-12-09 13:51 UTC, xtatica commented on docs/2-advanced/07-accessibility.md
> +| `accessibilityTexts` (FlexibleColumnLayout) | `aria-label`    | An object of strings that define several additional accessibility texts for even further customization.
```suggestion
| `accessibilityTexts` (`FlexibleColumnLayout`) | `aria-label`    | An object of strings that define several additional accessibility texts for even further customization.                                                                                             |
```

2021-12-09 13:51 UTC, xtatica commented on docs/2-advanced/07-accessibility.md
> +| `accessibilityRoles` (FlexibleColumnLayout) | `role`          | An object of strings that define several additional accessibility roles for even further customization.
```suggestion
| `accessibilityRoles` (`FlexibleColumnLayout`) | `role`          | An object of strings that define several additional accessibility roles for even further customization.                                                                                             |
```

2021-12-09 13:51 UTC, xtatica commented on docs/2-advanced/07-accessibility.md
> +This property accepts `object` with properties values for different parts of the FlexibleColumnLayout elements. For more detailed information on every object property, read the API description in [Fl
```suggestion
This property accepts `object` with property values for different parts of the `FlexibleColumnLayout` elements. For more detailed information on every object property, read the API description in [FlexibleColumnLayout](https://sap.github.io/ui5-webcomponents/playground/components/FlexibleColumnLayout). 
```

2021-12-09 13:51 UTC, xtatica commented on docs/2-advanced/07-accessibility.md
> +Will result in the shadow DOM as:
```suggestion
Results in the shadow DOM as: 
```

2021-12-09 13:51 UTC, xtatica commented on packages/fiori/src/FlexibleColumnLayout.js
> +		 * An object of strings that defines several additional accessibility roles for even further customization.
```suggestion
		 * An object of strings that defines additional accessibility roles for further customization.
```

2021-12-15 09:09 UTC, nnaydenow approved these changes

2021-12-17 08:51 UTC, xtatica approved these changes

2021-12-17 11:36 UTC, merged