refactor(ui5-list): removed ui5-item-press event
SAP/ui5-webcomponents pull request #4471
Opened 2021-12-10 15:01 UTC by nnaydenow

Removed usage of undocumented ui5-item-press event. In addition controls which were using are refactored to use ui5-selection-change event of the ui5-list. With #4448 ui5-item-click event is fired before ui5-selection-change in order to cancel the click / selection if needed and the event doesn't provide information if the clicked item is selected.

2021-12-10 15:04 UTC, nnaydenow commented
Hello @SAP/ui5-webcomponents-topic-rd and @SAP/ui5-webcomponents-topic-rl,

Could you please check if everything works okey with the components that you are responsible for?

Regards,
Nayden

2021-12-13 11:48 UTC, gmkv requested changes

2021-12-13 11:48 UTC, gmkv commented on packages/main/src/TabContainer.js
> +		this._onItemSelect(event.detail.selectedItems[0]);
save this to a variable and reuse it on line 403 as well. otherwise it throws

2021-12-13 14:50 UTC, gmkv approved these changes

2021-12-13 14:50 UTC, gmkv commented
LGTM from @SAP/ui5-webcomponents-topic-rd

2021-12-14 06:53 UTC, kineticjs approved these changes

2021-12-15 08:54 UTC, gmkv requested changes

2021-12-15 08:54 UTC, gmkv commented on packages/main/src/TabContainerPopover.hbs
> +	<ui5-list mode="SingleSelect" separators="None" @ui5-selection-change="{{_onOverflowListItemSelect}}"></ui5-list>
do not place a closing tag here

2021-12-15 09:01 UTC, nnaydenow commented on packages/main/src/TabContainerPopover.hbs
> +	<ui5-list mode="SingleSelect" separators="None" @ui5-selection-change="{{_onOverflowListItemSelect}}"></ui5-list>
resolving conflicts mistake. thanks!

2021-12-15 09:04 UTC, MapTo0 commented
lgtm

2021-12-15 09:04 UTC, MapTo0 approved these changes

2021-12-15 09:06 UTC, gmkv approved these changes

2021-12-15 09:18 UTC, niyap approved these changes

2021-12-15 09:58 UTC, plamenivanov91 approved these changes

2021-12-20 12:01 UTC, merged