feat(ui5-switch): accessibleNameRef property implemented
SAP/ui5-webcomponents pull request #4472
Opened 2021-12-10 15:38 UTC by unazko

- Receives id(or many ids) of the elements that label the component.

2021-12-13 08:09 UTC, elenastoyanovaa requested changes
Add tests and examples in the test pages.

2021-12-14 08:27 UTC, elenastoyanovaa requested changes
Please add tests.

2021-12-16 16:59 UTC, ilhan007 commented
Now there is a issue that we can reference with Related to: https://github.com/SAP/ui5-webcomponents/issues/4497

into the commit message body

2021-12-20 07:14 UTC, elenastoyanovaa approved these changes

2022-01-14 15:21 UTC, merged