feat(ui5-combobox): add full keyboard handling
SAP/ui5-webcomponents pull request #4494
Opened 2021-12-15 17:39 UTC by stbodurov

The keyboard specification for the ComboBox is now fully implemented.

2021-12-21 08:18 UTC, d3xter666 approved these changes

2021-12-21 08:26 UTC, fifoosid requested changes

2021-12-21 08:26 UTC, fifoosid commented on packages/main/src/ComboBox.js
>  	async handleArrowKeyPress(event) {
This method doesn't need to be async

2021-12-21 08:26 UTC, fifoosid commented on packages/main/src/ComboBox.js
> +	async handleNavKeyPress(event) {
same here

2022-01-05 09:39 UTC, simonarangelova requested changes

2022-01-05 09:39 UTC, simonarangelova commented on packages/main/src/ComboBox.js
> + * <li>[ESC] - Closes the drop-down, if open. If closed or not enabled, cancels changes and reverts to the value which the ComboBox field had when it got the focus.</li>
```suggestion
 * <li>[ESC] - Closes the dropdown, if open. If closed or not enabled, cancels changes and reverts to the value which the ComboBox field had when it got the focus.</li>
```

2022-01-05 09:39 UTC, simonarangelova commented on packages/main/src/ComboBox.js
> + * <li>[ENTER] or [RETURN] - If drop-down is open takes over the current matching item and closes it.</li>
```suggestion
 * <li>[ENTER] or [RETURN] - If dropdown is open takes over the current matching item and closes it.</li>
```

2022-01-05 09:39 UTC, simonarangelova commented on packages/main/src/ComboBox.js
> + * <li>[DOWN] - Selects the next matching item in the drop-down.</li>
```suggestion
 * <li>[DOWN] - Selects the next matching item in the dropdown.</li>
```

2022-01-05 09:39 UTC, simonarangelova commented on packages/main/src/ComboBox.js
> + * <li>[UP] - Selects the previous matching item in the drop-down.</li>
```suggestion
 * <li>[UP] - Selects the previous matching item in the dropdown.</li>
```

2022-01-05 09:39 UTC, simonarangelova commented on packages/main/src/ComboBox.js
> + * <li>[PAGEUP] - Moves highlight up by page size (10 items by default). If focus is in the ComboBox and the list is open, does nothing.</li>
```suggestion
 * <li>[PAGEUP] - Moves highlight up by page size (10 items by default). </li>
```

2022-01-05 09:39 UTC, simonarangelova commented on packages/main/src/ComboBox.js
> + * <li>[PAGEDOWN] - Moves highlight down by page size (10 items by default). If focus is in the ComboBox and the list is open, does nothing.</li>
```suggestion
 * <li>[PAGEDOWN] - Moves highlight down by page size (10 items by default).</li>
```

2022-01-10 15:40 UTC, ndeshev commented on packages/main/test/specs/ComboBox.spec.js
> +		await input.keys('Backspace');
you can just set the value to ""

2022-01-10 16:58 UTC, ndeshev commented
[ALT]+[UP]/[DOWN],[F4] issues with the focus on open and text selection on close remain

2022-01-11 07:50 UTC, stbodurov commented on packages/main/test/specs/ComboBox.spec.js
> +		await input.keys('Backspace');
Тried https://webdriver.io/docs/api/element/setValue/, does not seem to work.

2022-01-11 11:40 UTC, ndeshev commented on packages/main/test/specs/ComboBox.spec.js
> +		await input.keys('Backspace');
You should set the component value property - input..setProperty("value", "");

2022-01-11 12:16 UTC, ndeshev reviewed
When F4 or Alt+Arr is used to open the picker the focus should go to the first item (and it should also be selected), it works only if there is not a value state present. If it is - the value state is focused, this is wrong.

Otherwise the changes looks fine.

2022-01-11 12:16 UTC, ndeshev commented on packages/main/src/ComboBox.js
> +		this[`_handle${event.key}`](event, indexOfItem);
well done :)

2022-01-13 08:53 UTC, ndeshev commented on packages/main/test/specs/ComboBox.spec.js
> +		await input.keys('Backspace');
Why is this comment marked as resolved.

I was looking at the tests and want to suggest 3 things:
1. If you insist of using kbd interaction for clearing the value you can just achieve it with the backspace key as it is selected by the component functionality after the nav key is pressed on closed picker.
2.  You can get rid off the inputValue variable and just use await in the assertion
3. In general the first assertion argument is the tested thing, in this case the value property, then the second is the expected value - it is so in the first part of this test and the opposite in the second half.

2022-01-13 09:59 UTC, stbodurov commented on packages/main/test/specs/ComboBox.spec.js
> +		await input.keys('Backspace');
Implemented all suggestions in the [last commit](https://github.com/SAP/ui5-webcomponents/pull/4494/commits/683153f5315e93c7b481adbc0c591c4780dba80c).

2022-01-14 07:24 UTC, ndeshev approved these changes

2022-01-14 08:55 UTC, merged