feat(ui5-tabcontainer): show separators in overflow
SAP/ui5-webcomponents pull request #4507
Opened 2021-12-20 08:25 UTC by gmkv

Part of #2540

2021-12-29 12:15 UTC, dimovpetar requested changes
1) Open the overflow popover
2) resize the browser, so that the tab container header is expanded
3) first tabs from the popover are now in the strip, but also remain in the popover

![image](https://user-images.githubusercontent.com/32839090/147661057-7acc77a6-06b0-4ba9-8137-ccad496742bc.png)

This looks like different issue so we can fix it seperately.

2021-12-29 12:15 UTC, dimovpetar commented on packages/main/test/specs/TabContainer.spec.js
> -	it("tests if content is scrollable when tabcontainer takes limited height by its parent", async () => {
Why this test had to be deleted?

2022-01-07 15:00 UTC, dimovpetar submitted a review, later dismissed
LGTM

2022-01-07 15:30 UTC, gmkv reviewed
The metrics of the separators in the overflow don't match the spec.
See the VD spec for UniversalIconTabBar for the correct sizes, colors, border etc.

2022-01-10 12:21 UTC, dimovpetar approved these changes

2022-01-10 12:24 UTC, merged