feat(ui5-checkbox): accessibleName and accessibleNameRef implemented
SAP/ui5-webcomponents pull request #4547
Opened 2022-01-07 05:33 UTC by dobrinyonkov

Fixes: #4500

Added `accessible-name` and `accessible-name-ref` properties.

2022-01-07 12:08 UTC, nnaydenow approved these changes

2022-01-10 09:42 UTC, fifoosid approved these changes

2022-01-10 09:42 UTC, fifoosid commented on packages/main/src/CheckBox.js
> +		 * Receives id(or many ids) of the elements that label the combo box
that label the component

2022-01-10 09:43 UTC, fifoosid requested changes
Please see the comment from my previous review

2022-01-17 07:00 UTC, ilhan007 approved these changes

2022-01-17 07:01 UTC, merged