fix(ui5-color-picker): hex value input now properly managed
SAP/ui5-webcomponents pull request #4601
Opened 2022-01-20 15:25 UTC by unazko

Fixes:  #4540
Fixes:  #4541

2022-01-24 13:30 UTC, tsanislavgatev commented
I think this refered issue is not fixed yet: https://github.com/SAP/ui5-webcomponents/issues/4541
Example:
I input ffffff, then pick red from slider and move the picker to a place different than bottom right corner(white), and then input ffffff again, the color change is not applied.

2022-01-24 13:30 UTC, tsanislavgatev requested changes
I think this refered issue is not fixed yet: #4541
Example:
I input ffffff, then pick red from slider and move the picker to a place different than bottom right corner(white), and then input ffffff again, the color change is not applied.

2022-01-24 15:52 UTC, unazko commented
You are right @tsanislavgatev,
I've created a separate PR for the other issue:
https://github.com/SAP/ui5-webcomponents/pull/4621
as it feels more suitable now.

2022-01-28 14:39 UTC, tsanislavgatev submitted a review, later dismissed

2022-01-28 15:18 UTC, ilhan007 commented on packages/main/test/specs/ColorPicker.spec.js
> +		assert.strictEqual(await colorPicker.getAttribute("_hue"), hueValue, "Hue value remained unchanched");
typo: "unchanched" -> "unchanged"

2022-01-28 15:20 UTC, ilhan007 submitted a review, later dismissed
Again, as in the other PR I reviewed - please pay attention on the commit message title https://www.conventionalcommits.org/en/v1.0.0/#examples

2022-01-31 08:26 UTC, unazko commented on packages/main/test/specs/ColorPicker.spec.js
> +		assert.strictEqual(await colorPicker.getAttribute("_hue"), hueValue, "Hue value remained unchanched");
Done

2022-02-03 11:25 UTC, tsanislavgatev approved these changes

2022-02-08 13:11 UTC, merged