feat(ui5-input): implement showClearIcon property
SAP/ui5-webcomponents pull request #4641
Opened 2022-01-26 14:03 UTC by MapTo0

FIXES: https://github.com/SAP/ui5-webcomponents/issues/4395

2022-01-26 17:33 UTC, ilhan007 commented on packages/main/src/Input.js
> +		 * @since 1.1.2
1.1.2 is already produced, you can set 1.2.0

2022-01-26 17:36 UTC, ilhan007 commented on packages/main/test/specs/Input.spec.js
> +	it("Change event is called when value of inut is cleared with clear icon and input is focused out", async () => {
inut-> input

2022-01-26 17:37 UTC, ilhan007 commented on packages/main/test/specs/Input.spec.js
> +		assert.strictEqual(await changeCounter.getText(), "2", "Change event not called twice");
It says "not called twice", but compared with 2, a bit confusing when reading trough it.

2022-01-26 17:41 UTC, ilhan007 requested changes
Did not test it, but the code looks fine, some minor changes needed. Perhaps the team would test it anyway.

2022-01-27 09:32 UTC, ilhan007 commented on packages/main/test/specs/Input.spec.js
> +		assert.strictEqual(await changeCounter.getText(), "2", "Change event called twice (first - typing, secnond - clear icon)");
Marti, don't want to be mean :D - but "secnond" -> "second"

2022-01-30 07:58 UTC, niyap reviewed
From my side, it looks good :) Just one question, do we expected when we have ui5-input with suggestions and a dialog is open on mobile device, to have the clear icon by default, because currently that happens and I am not sure whether it is done by reason or it is a bug.

2022-01-31 09:26 UTC, stbodurov commented on packages/main/test/pages/Input.html
> +		<ui5-input id="clear-input" show-clear-icon placeholder="Search for a country ..."></ui5-input>
```suggestion
		<ui5-input id="clear-input" show-clear-icon placeholder="Type to show clear icon..."></ui5-input>
```

2022-01-31 09:29 UTC, stbodurov commented on packages/main/test/pages/Input.html
> +			<ui5-input id="clear-input-compact" show-clear-icon placeholder="Search for a country ..." value="test"></ui5-input>
```suggestion
			<ui5-input id="clear-input-compact" show-clear-icon placeholder="Type to show clear icon..." value="test"></ui5-input>
```

2022-01-31 09:49 UTC, stbodurov reviewed
When you open an input with suggestions on mobile and set a value, the clear icon does not appear in the main input once you close the dialog. This is not the case in UI5.

2022-02-01 10:45 UTC, stbodurov reviewed
We can also enable `show-clear-icon` for the "**Input With Suggestions**" sample in the playground:

packages/main/test/samples/Input.sample.html:L49

2022-02-01 10:45 UTC, stbodurov commented on packages/main/src/InputPopover.hbs
> +						.show-clear-icon={{showClearIcon}}
Now what happens is the opposite - the clear icon is forwarded to the main input, but no longer shows in the dialog.

Removing the period seems to bind the property correctly:

```suggestion
						show-clear-icon={{showClearIcon}}
```

2022-02-03 15:47 UTC, stbodurov approved these changes

2022-02-04 09:02 UTC, merged