feat(ui5-message-strip): apply SAP Horizon parameters
SAP/ui5-webcomponents pull request #4941
Opened 2022-03-22 12:26 UTC by stbodurov

2022-03-23 00:09 UTC, ivoplashkov requested changes
Hi,
At first glance the border color for the messagestrip with states seems to be incorrect in all themes.
Also the border radius seems to be incorrect.

![Screenshot 2022-03-23 at 2 07 34](https://user-images.githubusercontent.com/23635149/159596800-2aa4a046-039a-4975-acdb-24a62cbaf546.png)

2022-03-23 08:05 UTC, ivoplashkov requested changes
Seems like I haven't installed the new dependencies, that's why the parameters didn't resolve correctly, therefore disregards my previous comment.

I saw a misalignment ( seems to be a little more to the top ) in the HC themes for the messagestrip button, could you please check?

![Screenshot 2022-03-23 at 10 01 31](https://user-images.githubusercontent.com/23635149/159651770-6d0631d2-61ab-4b29-aa84-8504a33d8133.png)

2022-03-24 19:09 UTC, stbodurov commented
> Seems like I haven't installed the new dependencies, that's why the parameters didn't resolve correctly, therefore disregard my previous comment.
> 
> 
> 
> I saw a misalignment ( seems to be a little more to the top ) in the HC themes for the messagestrip button, could you please check?
> 
> 
> 
> ![Screenshot 2022-03-23 at 10 01 31](https://user-images.githubusercontent.com/23635149/159651770-6d0631d2-61ab-4b29-aa84-8504a33d8133.png)
> 
> 
> 
> 

Done

2022-03-28 11:51 UTC, ivoplashkov approved these changes

2022-03-28 11:58 UTC, merged