WIP(ui5-popup): Synchronous opening of a popup from another popup with Enter key now works
SAP/ui5-webcomponents pull request #4975
Opened 2022-03-28 15:13 UTC by dimovpetar

Scenario:
Popup 1 opens popup 2 when `Enter` key is pressed on a list item (`keydown` event).
```js
list.addEventListener("ui5-item-click", () => {
    popup2.close();
    popup1.show();
});
```
When popup 2 opens it applies its initial focus, which changes the active element. The following `click` event triggered by the `Enter` key is then fired on the new active element, not the list item.
In the issue the new active element is the close button of the popup 2, that's why it closes immediately.

Solution:
Apply initial focus after the rendering has finished, and restore the focus of the previously selected element in a separate task.

Fixes #4861

2022-07-22 08:42 UTC, BorisDafov commented on packages/main/test/pages/Popover.html
> +		<ui5-button id="closeChainedPopover2">Close chained popover2</ui5-button>
add a space:
Close chained popover 2

2022-07-22 12:36 UTC, dimovpetar commented on packages/main/test/pages/Popover.html
> +		<ui5-button id="closeChainedPopover2">Close chained popover2</ui5-button>
Done

2022-07-22 13:36 UTC, BorisDafov approved these changes

2022-07-26 11:02 UTC, gmkv requested changes
LGTM, there is just one small thing

2022-07-26 11:02 UTC, gmkv commented on packages/main/test/specs/ResponsivePopover.spec.js
> +		// await browser.pause(30000)
remove this comment

2022-07-26 11:42 UTC, dimovpetar commented on packages/main/test/specs/ResponsivePopover.spec.js
> +		// await browser.pause(30000)
Done

2022-07-26 11:44 UTC, gmkv approved these changes

2022-07-26 11:50 UTC, merged