feat(ui5-switch): embed new horizon theme changes
SAP/ui5-webcomponents pull request #5017
Opened 2022-04-05 07:43 UTC by unazko

2022-04-19 06:52 UTC, Todor-ads commented
"disable" state in Horizon HC theme - color is not correct

2022-04-19 09:13 UTC, Todor-ads approved these changes

2022-04-26 11:46 UTC, unazko commented
> "disable" state in Horizon HC theme - color is not correct

The same question has been raised into the horizon teems group and the answer was that we need to revert to the opacity
approach, in order to have the same behavior in all horizon themes. This is now done.

2022-04-26 11:53 UTC, Todor-ads approved these changes

2022-04-28 11:02 UTC, fifoosid requested changes
In RTL, the all icons are not centered:

![image](https://user-images.githubusercontent.com/16850339/165738431-bbfc82c7-37f0-4f1c-b334-5fe6a0d36044.png)

2022-04-29 07:50 UTC, Todor-ads approved these changes

2022-04-29 08:19 UTC, fifoosid approved these changes

2022-04-29 13:56 UTC, merged