refactor(ui5-input): refactor inputs' icon RTL styles
SAP/ui5-webcomponents pull request #5162
Opened 2022-05-03 13:16 UTC by ilhan007

Replace inputs' icon RTL styles with CSS Logical props. The styles affect ComboBox, MultiComboBox, Select, DatePicker.

In addition, 
- the BarcodeScannerDialog does not need to set dir anymore as the Dialog does not need it.
- the MessageStrip has been refactored, but the dir has not been removed from the template.

2022-05-03 13:38 UTC, tsanislavgatev submitted a review, later dismissed

2022-05-03 15:37 UTC, nnaydenow approved these changes
BarcodeScannerDialog and Select look good for me.

2022-05-04 11:10 UTC, gmkv requested changes
RadioButton looks good. I have a suggestion for TabContainer.

2022-05-04 11:10 UTC, gmkv commented on packages/main/src/themes/TabContainer.css
> +}
In `/packages/main/src/themes/TabInStrip.css`, could you also change the following lines:

```css
.ui5-tab-expand-button > [ui5-button] {
	height: 1.5rem;
	min-width: 1.5rem;
	margin-top: 0.25rem;
-       margin-left: 0.625rem;
+       margin-inline-start: 0.625rem;
 }

       . . .

 .ui5-tab-single-click-icon {
-       margin-left: 0.875rem;
+       margin-inline-start: 0.875rem;
 }
```

2022-05-04 11:24 UTC, gmkv approved these changes
LGTM for Topic RD

2022-05-04 14:41 UTC, niyap approved these changes

2022-05-04 14:55 UTC, merged