feat(ui5-rating-indicator): implement small icons for readonly and disabled
SAP/ui5-webcomponents pull request #5233
Opened 2022-05-18 09:37 UTC by ivoplashkov

2022-05-19 12:33 UTC, elenastoyanovaa requested changes
![Screenshot 2022-05-19 at 15 24 52](https://user-images.githubusercontent.com/11913394/169293251-9df4179f-1621-499f-af50-3fffb532560a.png)
The big star is somehow misaligned. It is not aligned in the middle. Perhaps it is an ui5-icon issue, but I saw that we also have some additional stylings for the icon. You could ignore this comment, as it has nothing to do with your change (I think) but I wanted to make you aware of this issue as you previously implemented the horizon theme for the rating indicator.

2022-05-23 06:28 UTC, ivoplashkov commented on packages/main/src/themes/sap_horizon/RatingIndicator-parameters.css
> +	--_ui5_rating_indicator_readonly_item_spacing: 3px 3px;
I did it on purpose, because 0.188rem is hard to guess, but can change it if you insist.

2022-05-25 06:23 UTC, elenastoyanovaa commented on packages/main/src/themes/sap_horizon/RatingIndicator-parameters.css
> +	--_ui5_rating_indicator_readonly_item_spacing: 3px 3px;
Actually it is 0.1875rem and it is widely used in this repo for setting sizes: https://github.com/SAP/ui5-webcomponents/search?q=0.1875rem

The same applies for 0.125rem (2px).

2022-05-25 06:58 UTC, elenastoyanovaa approved these changes

2022-05-25 07:26 UTC, merged