fix(ui5-tabcontainer): update tab strip on tab selection
SAP/ui5-webcomponents pull request #5449
Opened 2022-07-01 13:10 UTC by gmkv

- Tabs are rearranged on the tab strip when a tab is selected programatically.
- Updated documentation for getTabInStripDomRef to clarify use
with nested tabs.

Fixes #5172
Part of #5116

2022-07-04 09:52 UTC, BorisDafov requested changes

2022-07-04 09:52 UTC, BorisDafov commented on packages/main/src/TabSeparator.js
> +	 * Returns the DOM reference of the separator that is placed in the header.
I suggest to combine into one note:
	 * <b>Note:</b> Tabs and separators, placed in the <code>subTabs</code> slot of other tabs are not shown in the header. Calling this method on such tabs or separators will return <code>undefined</code>.

2022-07-04 09:52 UTC, BorisDafov commented on packages/main/test/pages/TabContainer.html
> +			<ui5-button id="selectFirst">Select first tab</ui5-button>
I suggest title case for button labels:
			<ui5-button id="selectFirst">Select First Tab</ui5-button>
			<ui5-button id="selectLast">Select Last Tab</ui5-button>
			<ui5-button id="selectNested">Select a Nested Tab</ui5-button>

2022-07-05 13:40 UTC, BorisDafov submitted a review, later dismissed

2022-07-11 07:25 UTC, dimovpetar requested changes
Sub tabs menus cannot be opened the sample "Nested Tabs".
Try to press the arrow of tab "Two" or "Three"
![image](https://user-images.githubusercontent.com/32839090/178210460-0cd3f48a-1182-4511-9dc2-6932c8012de0.png)

2022-08-09 11:36 UTC, dimovpetar requested changes
When the overflow is not visible, expanding tabs with arrow down or click doesn't work

2022-08-12 11:18 UTC, TeodorTaushanov approved these changes

2022-08-12 12:20 UTC, merged