fix(ui5-dialog): fixed selection of the content when the dialog is dr…
SAP/ui5-webcomponents pull request #5724
Opened 2022-08-25 13:44 UTC by TeodorTaushanov

Fixes #5668

2022-08-26 06:13 UTC, ilhan007 approved these changes

2022-08-26 06:15 UTC, ilhan007 commented
Hi @TeodorTaushanov we discussed it briefly and we are in favour of the workaround in this PR. 
If we find issues with it in future we can step back and change the API. For now, it seems a good solution.

2022-08-26 08:54 UTC, alexandar-mitsev requested changes
this is not ideal because:
- draggable="draggable" and draggable="false" will do the same thing - dragging from the dialog header
- draggable="true" will do something slightly different - dragging from the full dialog (header and content)

if we decide to use the property "draggable" this should be solved in a different way - most likely by completely overriding the "draggable" attribute. Which seems to be considered not the best practice.

or this inconsistent behaviour should be well documented as exception

2022-08-26 10:14 UTC, alexandar-mitsev commented
> this is not ideal because:
> 
> * draggable="draggable" and draggable="false" will do the same thing - dragging from the dialog header
> * draggable="true" will do something slightly different - dragging from the full dialog (header and content)
> 
> if we decide to use the property "draggable" this should be solved in a different way - most likely by completely overriding the "draggable" attribute. Which seems to be considered not the best practice.
> 
> or this inconsistent behaviour should be well documented as exception

ignore the part with draggable="true" it will work fine, only inconsistency is that draggable="false" will also do the same

2022-09-02 13:19 UTC, alexandar-mitsev approved these changes

2022-09-02 13:53 UTC, BorisDafov commented on packages/main/src/Dialog.js
> +		 * When "draggable" is set to true, the native browser "draggable"
I suggest to clarify that this is about the property and not the attribute::
* When  the "draggable" property is set to true, the native browser "draggable"

2022-09-02 13:56 UTC, BorisDafov requested changes
I suggest to clarify that this is about the property and not the attribute::

When the "draggable" property is set to true, the native browser "draggable"

2022-09-02 14:32 UTC, merged

2022-09-02 14:36 UTC, TeodorTaushanov commented
> I suggest to clarify that this is about the property and not the attribute::
> 
> When the "draggable" property is set to true, the native browser "draggable"

It can be set with an attribute as well.