fix(ui5-date-range-picker): handle single date value
SAP/ui5-webcomponents pull request #5769
Opened 2022-09-01 13:16 UTC by nnaydenow

2022-09-01 13:47 UTC, ilhan007 requested changes
Let's add a test to cover this use-case. Thanks

2022-09-01 19:31 UTC, ilhan007 commented on packages/main/test/specs/DateRangePicker.spec.js
> +		assert.equal(await daterangepicker.getProperty("value"), "7 Sep 2022", "value is updated");
can you also assert the startDateValue endDateValue as they are public methods and directly related to this use-case.

It's a question what should endDateValue return and if it works at all

2022-09-02 07:38 UTC, ilhan007 approved these changes

2022-09-02 08:04 UTC, tsanislavgatev approved these changes

2022-09-02 08:04 UTC, merged