Side nav acc2
SAP/ui5-webcomponents pull request #5877
Opened 2022-10-02 15:49 UTC by LidiyaGeorgieva

**Thank you for your contribution!** 👏

To get it merged faster, kindly review the checklist below:

## Pull Request Checklist
- [ ] Reviewed the [Contributing Guidelines](https://github.com/SAP/ui5-webcomponents/blob/main/CONTRIBUTING.md)
    + Especially the [How to Contribute](https://github.com/SAP/ui5-webcomponents/blob/main/CONTRIBUTING.md#how-to-contribute) section 
- [ ] [Correct commit message style](https://github.com/SAP/ui5-webcomponents/blob/main/docs/6-contributing/02-conventions-and-guidelines.md#commit-message-style)
    + Bugfixes should generally include a test to cover the issue.

2022-10-31 11:09 UTC, TeodorTaushanov requested changes

2022-10-31 11:09 UTC, TeodorTaushanov commented on packages/fiori/src/SideNavigation.hbs
> +					aria-roledescription="{{this.item.ariaRoleDescNavigationListItem}}"
roledescription="{{this.ariaRoleDescNavigationListItem}}"

2022-10-31 11:09 UTC, TeodorTaushanov commented on packages/fiori/src/SideNavigationItem.js
> +	get ariaRoleDescNavigationListItem() {
Move this to the SideNavigation class as it depends on the "collapsed" property of the whole SideNavigation.

2022-10-31 11:09 UTC, TeodorTaushanov commented on packages/fiori/src/SideNavigationSubItem.js
> +	get ariaRoleDescNavigationListItem() {
Same as the SideNavigationListItem

2022-10-31 11:09 UTC, TeodorTaushanov commented on packages/fiori/src/SideNavigationItemPopoverContent.hbs
> +			ria-checked="{{this.selected}}"
aria-selected="{{this.selected}}"

2022-10-31 11:09 UTC, TeodorTaushanov commented on packages/fiori/src/SideNavigationItemPopoverContent.hbs
> +				aria-checked="{{this.selected}}"
aria-selected="{{this.selected}}"

2022-11-08 09:17 UTC, dobrinyonkov commented on packages/main/src/ListItem.js
>  			type: String,
Use the `HasPopup` enum.

2022-11-10 15:06 UTC, dobrinyonkov approved these changes

2022-11-11 09:31 UTC, dobrinyonkov approved these changes

2022-11-11 09:32 UTC, TeodorTaushanov approved these changes

2022-11-11 09:44 UTC, merged