fix(ui5-listitem): prevent default event action when fire custom press event
SAP/ui5-webcomponents pull request #5928
Opened 2022-10-12 10:58 UTC by TeodorTaushanov

Fixes #5891

2022-10-13 10:56 UTC, dimovpetar requested changes
Add test

2022-10-17 09:13 UTC, dobrinyonkov approved these changes

2022-10-18 13:41 UTC, dimovpetar requested changes

2022-10-18 13:41 UTC, dimovpetar commented on packages/main/test/pages/Dialog.html
> +				listContainerDialog.hide();
listContainerDialog.close();

2022-10-18 13:48 UTC, TeodorTaushanov commented on packages/main/test/pages/Dialog.html
> +				listContainerDialog.hide();
Done.

2022-10-18 13:49 UTC, dimovpetar approved these changes

2022-10-18 14:57 UTC, merged