feat(ui-li): navigation mode is enabled
SAP/ui5-webcomponents pull request #6024
Opened 2022-11-08 14:14 UTC by yanaminkova

2022-11-09 13:45 UTC, PetyaMarkovaBogdanova submitted a review, later dismissed

2022-11-09 13:53 UTC, simonarangelova commented on packages/main/src/types/ListItemType.js
> +	 * Enables the type of navigation, which is specified to add an arrow to the right side of the items and fires navigate-click event.
```suggestion
	 * Enables the type of navigation, which is specified to add an arrow at the end of the items and fires navigate-click event.
```

2022-11-09 20:24 UTC, ilhan007 commented on packages/main/src/ListItem.js
> +		navigated: {
if this is  a public property, it should be properly  documented

2022-11-09 20:25 UTC, ilhan007 commented on packages/main/src/ListItem.js
> +	get navigated() {
this getter is redundant, as "navigated" is part of the component metadata - there is already a getter with the same name

2022-11-09 20:33 UTC, ilhan007 commented on packages/main/src/ListItem.js
> +			  navigationItem = this.type === ListItemType.Navigation;
itemNavigated would be more consistent with "itemActive" and you can reuse the new getter "typeNavigation", which checks the same:
this.type === ListItemType.Navigation;

2022-11-09 20:33 UTC, ilhan007 requested changes
@yanaminkova Thank you for the PR, there are few inline comments from my side

2022-11-15 08:14 UTC, PetyaMarkovaBogdanova approved these changes

2022-11-15 15:38 UTC, ilhan007 approved these changes

2022-11-15 16:08 UTC, merged