feat(ui5-popover): accessibleRole property added
SAP/ui5-webcomponents pull request #6221
Opened 2022-12-22 12:13 UTC by s-todorova

Fixes #6090

2023-01-04 11:14 UTC, gmkv requested changes

2023-01-04 11:14 UTC, gmkv commented on packages/main/src/Dialog.js
> +		this.accessibleRole = this._role;
The attribute `accessible-role` cannot be customised with this approach.

2023-01-05 13:18 UTC, gmkv commented
Now, any accessibleRole will be ignored if the 'state' property is Error or Warning. Let the dialog continue having its custom accessibleRole, if it has been set. If the property is not set, then keep the old behavior: 
- state=Error & state=Warning => `role='alertdialog'`
- state=anything else  => `role='dialog'`

2023-01-05 14:34 UTC, gmkv requested changes

2023-01-05 14:34 UTC, gmkv commented on packages/main/src/Popup.ts
> +	 * @since 1.11.0
1.10.0

2023-01-05 14:42 UTC, gmkv approved these changes

2023-01-05 14:59 UTC, elenastoyanovaa commented
Hello @SAP/ui5-webcomponents-topic-rd ,

Is this discussed with the accessibility expert and Stefan Schnabel, since this seems to not be present in the SR spec and in the UI5 Popover as well?

Elena

2023-01-05 15:00 UTC, elenastoyanovaa submitted a review, later dismissed
Hello @SAP/ui5-webcomponents-topic-rd ,

Is this discussed with the accessibility expert and Stefan Schnabel, since this seems to not be present in the SR spec and in the UI5 Popover as well?

Elena

2023-01-23 11:21 UTC, gmkv requested changes

2023-01-23 11:21 UTC, gmkv commented on packages/main/src/Popup.ts
> +	 * Allows setting a custom role
Update the comment to something like "Allows setting the role. Available options are:..." since this no longer allows to set an actual custom role.

2023-01-23 11:21 UTC, gmkv commented on packages/main/src/Dialog.ts
> +		}
This getter does too much. Imagine accessing `const r = dialog._role;`and seeing the state being suddenly mutated.

2023-01-23 11:21 UTC, gmkv commented on packages/main/src/Popup.ts
> +			this.shadowRoot!.querySelector(".ui5-popup-root")?.removeAttribute("role");
Use the getter _root. But ideally you wouldn't need to call this at all.

2023-01-23 11:21 UTC, gmkv commented on packages/main/src/Popup.hbs
> +	role={{_role}}
The role here ends up in written PascalCase.
https://www.deque.com/blog/wai-aria-top-6-mistakes-to-avoid/#:~:text=Authors%20need%20to%20remember%20that,in%20lowercase

2023-01-23 12:28 UTC, gmkv requested changes

2023-01-23 12:28 UTC, gmkv commented on packages/main/src/types/PopupAccessibleRole.ts
> +	alertdialog = "alertdialog",
The enums should remain in PascalCase. Try to think of another way to make the role have all lowercase letters

2023-01-24 09:25 UTC, gmkv requested changes
Please add short description for the PR

2023-01-24 09:25 UTC, gmkv commented on packages/main/src/Dialog.ts
> +		return (this.accessibleRole === PopupAccessibleRole.None) ? undefined : "true";
you don't need the parentheses here

2023-01-24 09:25 UTC, gmkv commented on packages/main/src/Dialog.ts
> +		return (this.state === ValueState.Error || this.state === ValueState.Warning) ? PopupAccessibleRole.AlertDialog.toLowerCase() : this.accessibleRole.toLowerCase();
it would be easier to read if you write the state check in a separate if statement

2023-01-24 09:25 UTC, gmkv commented on packages/main/src/Popover.ts
> +		return (this.accessibleRole === PopupAccessibleRole.None) ? undefined : "true";
same thing

2023-01-24 09:25 UTC, gmkv commented on packages/main/src/Popup.ts
> +	 * <code>Dialog</code>, <code>None</code> and <code>AlertDialog</code>.
write those entries in a list
for example, see the docs here https://sap.github.io/ui5-webcomponents/playground/components/Avatar/

2023-01-24 09:48 UTC, gmkv commented on packages/main/src/Dialog.ts
> +import UI5Element from "@ui5/webcomponents-base/src/UI5Element.js";
this is unused

2023-01-24 09:58 UTC, gmkv approved these changes

2023-01-26 09:48 UTC, nnaydenow commented on packages/main/src/Popup.ts
>  	 * @returns {string}
returns { string | undefined } seems more correctly to me

2023-01-30 12:17 UTC, elenastoyanovaa requested changes
Please also add tests covering the alertdialog (with and without a set role as a property) and none scenario (we do not have tests if aria-modal is present or not)

2023-01-30 12:17 UTC, elenastoyanovaa commented on packages/main/src/Dialog.ts
> +		if (this.state === ValueState.Error || this.state === ValueState.Warning) {
we should document this behavior - if a user sets a dialog role explicitly, we overwrite it. Is this the desired behavior? If yes, please add a note in the documentation of the property.

2023-01-30 12:17 UTC, elenastoyanovaa commented on packages/main/test/specs/Popover.spec.js
> +		await popover.setAttribute("accessible-role", "menu");
this should not be valid?

2023-01-30 12:17 UTC, elenastoyanovaa commented on packages/main/test/specs/Popover.spec.js
> +		await popover.setAttribute("accessible-role", "menu");
we do not accept menu as a valid role

2023-01-30 12:17 UTC, elenastoyanovaa commented on packages/main/test/specs/ResponsivePopover.mobile.spec.js
> +describe("Acc", () => {
those scenarios should not be valid.

2023-01-30 12:17 UTC, elenastoyanovaa commented on packages/main/test/specs/ResponsivePopover.spec.js
> +describe("Acc", () => {
those scenarios should not be valid

2023-02-02 11:30 UTC, TeodorTaushanov approved these changes

2023-02-02 12:56 UTC, merged