fix(ui5-segmented-button): press item programatically works properly
SAP/ui5-webcomponents pull request #6502
Opened 2023-02-15 10:08 UTC by NHristov-sap

Fixes: #5890

2023-02-15 15:03 UTC, tsanislavgatev requested changes
I think we should change the test as it's still passing without the code in  normalizeSelection.

2023-02-16 11:49 UTC, tsanislavgatev commented
Can you please provide more information about the issue and how are we fixing it in the commit message body and pull request description?

2023-02-16 11:58 UTC, NHristov-sap commented
> Can you please provide more information about the issue and how are we fixing it in the commit message body and pull request description?



> Can you please provide more information about the issue and how are we fixing it in the commit message body and pull request description?

Done.

2023-02-16 12:11 UTC, tsanislavgatev approved these changes

2023-02-16 12:13 UTC, merged