fix(ui5-combobox): filter items when lazy-loading after initial rendering
SAP/ui5-webcomponents pull request #6512
Opened 2023-02-16 09:57 UTC by ivoplashkov

- Items are now filtered while typing in case of `ui5-combobox` with lazy-loading.

Fixes: #6480

2023-02-20 09:06 UTC, simonarangelova approved these changes

2023-02-20 17:41 UTC, elenastoyanovaa requested changes
I am not sure if this should be marked as a fix, since we sort of introduce a new property value (None), which was previously not available for usage.

Also maybe we could discuss with the team whether we should also include a sample in the playground for this scenario :)

Also when trying to reproduce in the test page, if I write "I" nothing happens the first time and if I press space, then the popover opens. Is this expected? If so, please add a short text near the input explaining how to use it.

2023-02-20 17:41 UTC, elenastoyanovaa commented on packages/main/test/specs/ComboBox.spec.js
> +			assert.strictEqual(listItems.length, 5, "Items should be 10");
actually they are 5

2023-02-28 07:45 UTC, ivoplashkov commented on packages/main/test/specs/ComboBox.spec.js
> +			assert.strictEqual(listItems.length, 5, "Items should be 10");
Done

2023-02-28 08:54 UTC, elenastoyanovaa approved these changes

2023-02-28 13:10 UTC, merged