chore(ui5-dialog): add samples to Storybook
SAP/ui5-webcomponents pull request #6619
Opened 2023-03-01 15:09 UTC by gmkv

2023-03-07 09:03 UTC, dimovpetar requested changes
When you open the "Docs" page, all dialogs from the samples are open

2023-03-07 09:26 UTC, dimovpetar requested changes
If you open any dialog, let's say the one from sample 'Basic', and then go to the 'Docs' page, you won't be able to open it there. Also, if you leave the dialog open on the 'Basic' story, then on the main page you will see the block layer.

2023-03-07 09:26 UTC, dimovpetar commented on packages/playground/_stories/main/Dialog/Dialog.stories.ts
> +	default: `
"default": and "footer" slots appear with extra indentation in the storybook for all samples

2023-03-08 12:22 UTC, gmkv commented
> If you open any dialog, let's say the one from sample 'Basic', and then go to the 'Docs' page, you won't be able to open it there. Also, if you leave the dialog open on the 'Basic' story, then on the main page you will see the block layer.

I will check with Dobrin about this. Looks like the page is not completely destroyed/removed when you switch from a Story to the Docs Page. Therefore, onExitDOM on the Popup does not get called, which will remove the block layer. For some reason though, clicking between different Stories does destroy the page completely, which does call onExitDOM.

2023-03-09 15:14 UTC, gmkv commented
> > If you open any dialog, let's say the one from sample 'Basic', and then go to the 'Docs' page, you won't be able to open it there. Also, if you leave the dialog open on the 'Basic' story, then on the main page you will see the block layer.
> 
> I will check with Dobrin about this. Looks like the page is not completely destroyed/removed when you switch from a Story to the Docs Page. Therefore, onExitDOM on the Popup does not get called, which will remove the block layer. For some reason though, clicking between different Stories does destroy the page completely, which does call onExitDOM.

Switching to the Docs page while a Dialog is open will be addressed separately by @dobrinyonkov

2023-03-28 12:47 UTC, TeodorTaushanov approved these changes

2023-03-28 12:50 UTC, merged