Bar in dialog
SAP/ui5-webcomponents pull request #6821
Opened 2023-03-29 13:17 UTC by LidiyaGeorgieva

**Thank you for your contribution!** 👏

To get it merged faster, kindly review the checklist below:

## Pull Request Checklist
- [ ] Reviewed the [Contributing Guidelines](https://github.com/SAP/ui5-webcomponents/blob/main/CONTRIBUTING.md)
    + Especially the [How to Contribute](https://github.com/SAP/ui5-webcomponents/blob/main/CONTRIBUTING.md#how-to-contribute) section 
- [ ] [Correct commit message style](https://github.com/SAP/ui5-webcomponents/blob/main/docs/6-contributing/02-conventions-and-guidelines.md#commit-message-style)
    + Bugfixes should generally include a test to cover the issue.

2023-04-06 20:38 UTC, gmkv requested changes

2023-04-06 20:38 UTC, gmkv commented on packages/playground/_stories/main/Dialog/Dialog.stories.ts
> +	header: '<ui5-bar slot="header" design="Header"> <ui5-text slot="startContent">Bar used in Header and Footer</ui5-text> <ui5-button class="dialogCloser" design="Transparent" id="closeDialogButton" s
You can give this HTML some proper indentation by using a template literal instead.
There's also no such component like ui5-text, perhaps you meant to use a ui5-title?
And custom elements can't be self-closing. It is a requirement for them to have a separate closing tag.

2023-04-06 20:38 UTC, gmkv commented on packages/playground/_stories/main/Dialog/Dialog.stories.ts
> +	<ui5-button class="dialogCloser" design="Emphasized" slot="endContent">OK</ui5-button>
Add an inline style here or an extra style below to give all footer buttons a min-width of 4rem. This comes from the Fiori Guidelines (or VD spec). See the usage on line 118.

2023-04-07 12:21 UTC, gmkv commented
Also, rewrite the title of the PR to a sentence which explains more on what this commit does.

2023-04-07 14:50 UTC, gmkv requested changes

2023-04-07 14:50 UTC, gmkv commented on packages/playground/_stories/main/Dialog/Dialog.stories.ts
> +			</ui5-bar>`,
this indentation should be corrected to so it looks right in the Storybook page:
![image](https://user-images.githubusercontent.com/22086365/230628919-c72f60a1-9960-4c14-96a8-0166c7ca23bb.png)


We can't make the indentation look ok both in Storybook and in TS, so we choose to make it look correct only for Storybook

2023-04-10 11:51 UTC, gmkv approved these changes

2023-04-10 12:38 UTC, BorisDafov requested changes
minor

2023-04-10 12:38 UTC, BorisDafov commented on packages/fiori/test/pages/DialogWithBar.html
> +			<ui5-title level="H5" slot="startContent">Sample Dialog With Bar</ui5-title>
no need to capitalize "with":
Sample Dialog with Bar

2023-04-10 12:38 UTC, BorisDafov commented on packages/main/test/samples/Dialog.sample.html
> +				<ui5-title level="H5" slot="startContent">Sample Dialog With Bar</ui5-title>
with

2023-04-10 12:38 UTC, BorisDafov commented on packages/main/test/samples/Dialog.sample.html
> +				<ui5-title level="H5" slot="startContent">Sample Dialog With Bar</ui5-title>
with

2023-04-10 13:28 UTC, BorisDafov approved these changes

2023-04-10 13:29 UTC, gmkv approved these changes

2023-04-11 05:19 UTC, merged