feat(ui5-title): add custom overstyles when used with Link
SAP/ui5-webcomponents pull request #6932
Opened 2023-04-19 15:13 UTC by gmkv

There are cases when a Link will be used inside a Title.

A subtle link will look like a default link when it is used inside a title. Refactored Link to allow for overstyling.

Fixes #6785

2023-04-21 10:36 UTC, tsanislavgatev approved these changes
+1 on link.

2023-04-25 15:00 UTC, dimovpetar requested changes
Also update the documentation of the slot sap.ui.webc.main.Title.prototype.default

2023-04-26 06:55 UTC, dimovpetar approved these changes

2023-04-26 08:30 UTC, BorisDafov requested changes

2023-04-26 08:30 UTC, BorisDafov commented on packages/main/test/pages/Title.html
> +		<ui5-title level="H6" id="truncated-title">Truncated title Lorem ipsum dolor, sit amet consectetur adipisicing elit. Numquam, ab.</ui5-title>
Truncated Title Lorem Ipsum Dolor, Sit Amet Consectetur Adipisicing Alit. Numquam, Ab.

2023-04-26 08:30 UTC, BorisDafov commented on packages/main/test/pages/Title.html
>  		<ui5-title level="H6" wrapping-type="Normal" id="wrapping-title">Wrapping title Lorem ipsum dolor, sit amet consectetur adipisicing elit. Numquam, ab.</ui5-title>
Wrapping Title Lorem Ipsum Dolor, Sit Amet Consectetur Adipisicing Elit. Numquam, Ab.

2023-04-26 08:30 UTC, BorisDafov commented on packages/main/test/pages/Title.html
> +		<ui5-title level="H3">
<ui5-title level="H3">
			<ui5-link design="Default">With Default Link (57)</ui5-link>
		</ui5-title>
		<ui5-title level="H3">
			<ui5-link design="Emphasized">With Emphasized Link (58)</ui5-link>
		</ui5-title>
		<ui5-title level="H3">
			<ui5-link design="Subtle">With Subtle Link (59)</ui5-link>
		</ui5-title>
		<div class="wrapping">
			<h2>Wrapping with Link</h2>
			<ui5-title level="H6">
				<ui5-link design="Default">Truncated with Link (60) Lorem Ipsum Dolor, Sit Amet Consectetur Adipisicing Elit. Numquam, Ab.</ui5-link>
			</ui5-title>
			<ui5-title level="H6" wrapping-type="Normal">
				<ui5-link design="Default">Wrapping with Link (61) Lorem Ipsum Dolor, Sit Amet Consectetur Adipisicing Elit. Numquam, Ab.</ui5-link>
			</ui5-title>

2023-04-26 13:05 UTC, BorisDafov reviewed
From UA perspective, I approve these changes...

2023-04-26 13:07 UTC, dimovpetar approved these changes

2023-04-26 13:59 UTC, merged