feat(ui5-input): add storybook samples
SAP/ui5-webcomponents pull request #6933
Opened 2023-04-19 15:43 UTC by Okiana

Add storybook sample for ui5-input

2023-04-20 12:50 UTC, elenastoyanovaa requested changes
- Change the PR name to docs
- Remove the ts-ignore
- The formatting of the code (in the storybook when you click on the show code button) is wrong - wrong tabulation or several items on concatenated on one line, which makes the code very unreadable.

2023-04-20 12:50 UTC, elenastoyanovaa commented on packages/playground/_stories/main/Input/Input.stories.ts
> +		valueHelpInput.addEventListener("input", loadSuggestions);
where are those variables defined?

2023-04-21 13:24 UTC, Okiana commented on packages/playground/_stories/main/Input/Input.stories.ts
> +BasicInput.storyName = "Basic Input";
Done

2023-04-21 14:08 UTC, Okiana commented on packages/playground/_stories/main/Input/Input.stories.ts
> +		valueHelpInput.addEventListener("input", loadSuggestions);
Done

2023-04-21 14:08 UTC, Okiana commented
> * Change the PR name to docs
> * Remove the ts-ignore
> * The formatting of the code (in the storybook when you click on the show code button) is wrong - wrong tabulation or several items on concatenated on one line, which makes the code very unreadable.

Done

2023-05-09 11:00 UTC, MapTo0 requested changes
- do not mix tabs and spaces in the file. format with tabs only
- Could you please rewrite the examples with arrow functions instead of fn declarations

The output in the playground looks strange:

<img width="365" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/5821279/9fe13f55-e98e-4584-9548-62ef1aab2ba8">

Some private props are there but should not be part of the example. Do we have a solution for that one? @dobrinyonkov 

I would say that we remove search field example since we have the value help example which basically sets the same slot - `icon` with and presents an input with a custom icon

Input with label example is not working correctly - clicking on the label does not focus the input, also I guess the ACC is broken @elenastoyanovaa 

Consider also combining or removing one of the value states examples. I would suggest that we have just 1 custom implemented value state message since changing the value-state property is quite straight forward.

2023-05-15 12:51 UTC, Okiana commented on packages/playground/_stories/main/Input/Input.stories.ts
> +	let value,
Done

2023-05-15 12:51 UTC, Okiana commented on packages/playground/_stories/main/Input/Input.stories.ts
> +	input.addEventListener("input", function(event) {
Done

2023-05-16 07:06 UTC, Okiana commented
> <img alt="image" width="365" src="https://user-images.githubusercontent.com/5821279/237075718-9fe13f55-e98e-4584-9548-62ef1aab2ba8.png">
> Some private props are there but should not be part of the example. Do we have a solution for that one? @dobrinyonkov ->related to: #7035 


All other comments are done.

2023-05-16 11:52 UTC, MapTo0 commented on packages/playground/_stories/main/Input/Input.stories.ts
> +		SuggestionItem: 'ui5-suggestion-item',
fix tabulation, do not mix spaces and tabs

2023-05-17 12:23 UTC, MapTo0 approved these changes

2023-05-17 12:23 UTC, MapTo0 commented on packages/playground/_stories/main/Input/Input.stories.ts
> +		[].slice.call(input${index}.children).forEach((child) => {
Use `Array.from` ?

2023-05-18 06:37 UTC, elenastoyanovaa approved these changes

2023-05-18 06:46 UTC, merged