feat(ui5-range-slider): add storybook sample
SAP/ui5-webcomponents pull request #6935
Opened 2023-04-19 16:28 UTC by Okiana

Add ui5-range-slider storybook sample

2023-04-20 12:34 UTC, elenastoyanovaa requested changes
- Change the PR name to docs, not feat.
- Remove the ts-ignore

2023-04-21 13:19 UTC, Okiana commented on packages/playground/_stories/main/RangeSlider/RangeSlider.stories.ts
> +BasicRangeSlider.storyName = "Basic Range Slider";
Done

2023-04-21 13:20 UTC, Okiana commented
> * Change the PR name to docs, not feat.
> * Remove the ts-ignore

Done

2023-04-21 13:44 UTC, elenastoyanovaa approved these changes

2023-04-21 16:18 UTC, merged