feat(ui5-multi-input): add storybook sample
SAP/ui5-webcomponents pull request #6936
Opened 2023-04-19 17:07 UTC by Okiana

Add storybook sample for ui5-multi-input

2023-04-20 12:43 UTC, elenastoyanovaa requested changes
- Change the PR name to docs, not feat.
- Remove the ts-ignore

2023-04-20 12:43 UTC, elenastoyanovaa commented on packages/playground/_stories/main/MultiInput/MultiInput.stories.ts
> +BasicMultiInput.storyName = "Basic Multi Input";
no need

2023-04-21 10:09 UTC, Okiana commented on packages/playground/_stories/main/MultiInput/MultiInput.stories.ts
> +BasicMultiInput.storyName = "Basic Multi Input";
Done :)

2023-04-21 10:42 UTC, Okiana commented on packages/playground/_stories/main/MultiInput/MultiInput.stories.ts
>  		<script>
Done

2023-04-21 12:00 UTC, Okiana commented
> * Change the PR name to docs, not feat.
> * Remove the ts-ignore

Done

2023-04-21 13:45 UTC, elenastoyanovaa approved these changes

2023-04-21 16:19 UTC, merged