fix(ui5-carousel): update carousel horizon theme
SAP/ui5-webcomponents pull request #6984
Opened 2023-05-04 13:09 UTC by TeodorTaushanov

2023-05-19 14:17 UTC, dimovpetar requested changes
Add `box-sizing: border-box;` to the page indicator dots

2023-05-19 14:17 UTC, dimovpetar commented on packages/main/src/themes/Carousel.css
> +.ui5-carousel-navigation-wrapper-bg-translusent {
translu**c**ent
Fix it in all places

2023-05-26 07:12 UTC, BorisDafov reviewed
I approve the request from UA perspective

2023-05-26 12:05 UTC, dimovpetar approved these changes

2023-05-29 06:52 UTC, merged