fix(ui5-dialog): add text with instructions for resizing of dialog fo…
SAP/ui5-webcomponents pull request #6989
Opened 2023-05-05 14:27 UTC by LidiyaGeorgieva

Fixes #6659

2023-05-10 13:47 UTC, TeodorTaushanov requested changes
Add aria-roledescription = "Interactive Header"
Add also text for dragging the dialog:
aria-describedby = "Use Arrow keys to move, Shift+Arrow keys to resize"

2023-05-18 11:59 UTC, TeodorTaushanov requested changes
How the "describedby text" is not read by screen readers. 

Create a new "div" inside the "header" with role="group" and put all the logic there. Check the Openui5 Dialog control.

Check if the css styles should be adapted.

```
<header>
			<div
				class="ui5-popup-header-root"
				id="ui5-popup-header"
				role="group"
				aria-describedby={{effectiveAriaDescribedBy}}
				aria-roledescription={{ariaRoleDescriptionHeaderText}}
				tabindex="{{_headerTabIndex}}"
```

2023-05-25 06:15 UTC, LidiyaGeorgieva commented
> 

It works on my machine :)
![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/8236bbc4-ec29-4264-b6df-3663ae8aa859)
Tested on: chrome 113, Jaws 2022, Win 11

2023-05-31 11:16 UTC, TeodorTaushanov requested changes

2023-05-31 11:16 UTC, TeodorTaushanov commented on packages/main/src/Dialog.hbs
> +					<span id="{{_id}}-descr" class="ui5-hidden-text">{{ariaDescribedByHeaderTextDraggableAndResizable}}</span>
Add aria-hidden="true" to the "describedby" text.

2023-06-01 10:08 UTC, TeodorTaushanov approved these changes

2023-06-01 10:21 UTC, merged