fix(ui5-label): enhance the documentation and the samples
SAP/ui5-webcomponents pull request #7108
Opened 2023-05-26 14:17 UTC by LidiyaGeorgieva

The correct usage of ui5-label is to be connected to some input element (using for attribute). This is documented in all the test pages.
Also in the Playgrounds pages for ui5-label are added corresponding inputs.

Related to: #6488

2023-05-29 08:50 UTC, TeodorTaushanov submitted a review, later dismissed

2023-05-29 08:50 UTC, TeodorTaushanov commented on packages/main/src/Label.ts
>   * The <code>ui5-label</code> is a component used to represent a label,
```
 * The <code>ui5-label</code> is a component used to represent a label for elements like input, textarea, select. <br><br>
The <code>for</code> property of the <code>ui5-label</code> must be the same as the id attribute of the related input element.<br><br>
Screen readers read out the label, when the user focuses the labelled control.
```

2023-05-29 10:49 UTC, gmkv requested changes

2023-05-29 10:49 UTC, gmkv commented on packages/playground/_stories/main/Label/Label.stories.ts
> +	<ui5-input id="myInputSimple"></ui5-input>
Extract this input into a function and use it in all places. Like the `SetWidth200Px` decorator.

2023-05-29 14:00 UTC, gmkv commented on packages/playground/_stories/main/Label/Label.stories.ts
> +`;
these can be deleted now

2023-05-29 14:00 UTC, gmkv commented on packages/playground/_stories/main/Label/Label.stories.ts
> +};
```ts
const addInput = (id: string): Decorator => {
	return (story, { args }) => {
		return html`
${story({ args: { ...args, for: id } })}
<ui5-input id="${id}"></ui5-input>`;
	};
};
```
the decorator import is from `import type { Decorator } from "@storybook/web-components"`

2023-05-29 14:01 UTC, gmkv commented on packages/playground/_stories/main/Label/Label.stories.ts
> +},
rewrite the SetWidth200Px as:
```ts
const SetWidth200Px: Decorator = (story, { args }) => {
	return html`
<style>
	.w200 {
		width: 200px;
	}
</style>
${story({ args: { ...args, className: "w200" } })}`;
};
```
and this middle function can be deleted

2023-05-29 14:03 UTC, gmkv commented on packages/playground/_stories/main/Label/Label.stories.ts
>  </ui5-label>`;
please remove the newlines here:
```ts
>${unsafeHTML(args.default)}</ui5-label>`;
```
it causes some extra whitespace that #7042 describes

2023-05-29 14:05 UTC, gmkv commented on packages/main/test/pages/Label.html
> +	<div id="message"><ui5-message-strip design="Information">The proper use of the component is to define a label for elements like input, textarea, select.</ui5-message-strip></div>
No-one will read these pages. These test files are not part of our documentation

2023-05-29 20:49 UTC, gmkv commented on packages/playground/_stories/main/Label/Label.stories.ts
>  </ui5-label>`;
All on one line

2023-05-29 20:50 UTC, gmkv requested changes

2023-05-29 20:50 UTC, gmkv commented on packages/playground/_stories/main/Label/Label.stories.ts
> +	className: "limitedWidth",
not needed any more

2023-05-30 06:33 UTC, gmkv approved these changes

2023-05-30 07:28 UTC, merged