chore: add event detail types
SAP/ui5-webcomponents pull request #7119
Opened 2023-05-30 10:37 UTC by ilhan007

The PR addresses Event Detail missing types or using wrong convention, or missing exports of types:
- adding new types
- renaming existing to follow the convention:
{Component}{EventName}EventDetail
- export existing and new types

Related to: https://github.com/SAP/ui5-webcomponents/issues/7118

2023-05-30 10:58 UTC, MarcusNotheis requested changes

2023-05-30 10:58 UTC, MarcusNotheis commented on packages/fiori/src/FlexibleColumnLayout.ts
> +	FCLLayoutChangeEventDetail,
```suggestion
	FlexibleColumnLayoutLayoutChangeEventDetail,
```
Although I don't like the `LayoutLayout` part in the middle of this super long type we should stick to the full component name convention

2023-05-30 10:58 UTC, MarcusNotheis commented on packages/fiori/src/NotificationListItem.ts
> +import type { NotificationListItemBaseCloseEventDetail as NotificationListGroupItemCloseEventDetail } from "./NotificationListItemBase.js";
```suggestion
import type { NotificationListItemBaseCloseEventDetail as NotificationListItemCloseEventDetail } from "./NotificationListItemBase.js";
```

2023-05-30 10:58 UTC, MarcusNotheis commented on packages/fiori/src/NotificationListItem.ts
> +	NotificationListGroupItemCloseEventDetail,
```suggestion
	NotificationListItemCloseEventDetail,
```

2023-05-30 13:31 UTC, MarcusNotheis approved these changes

2023-05-30 16:05 UTC, MarcusNotheis approved these changes

2023-05-31 07:35 UTC, nnaydenow approved these changes

2023-05-31 07:40 UTC, merged