feat(ui5-radio-button): update visual design to latest SAP Horizon spec
SAP/ui5-webcomponents pull request #7148
Opened 2023-06-05 13:28 UTC by kskondov

New styles parameters are applied as per the latest SAP Horizon spec
PartOf: #7001

2023-06-07 06:50 UTC, BorisDafov commented
From UA perspective I have only one small suggestion - to change the commit message to:
feat(ui5-radio-button): update visual design to latest Horizon spec

2023-06-14 07:18 UTC, dimovpetar requested changes
1) there is strange background that appears on hover on both Horizon and Quartz
2) the dot for read only buttons is now darker in Quartz, which is not expected

2023-06-14 14:03 UTC, kskondov commented
> 1. there is strange background that appears on hover on both Horizon and Quartz
> 2. the dot for read only buttons is now darker in Quartz, which is not expected

Done

2023-06-16 11:27 UTC, LidiyaGeorgieva approved these changes

2023-06-16 13:08 UTC, dimovpetar approved these changes

2023-06-16 13:15 UTC, merged