fix(ui5-textarea): avoid unnecessary assigning to variable
SAP/ui5-webcomponents pull request #7162
Opened 2023-06-08 08:18 UTC by ivoplashkov

FIXES: #7147

2023-06-08 14:15 UTC, nnaydenow reviewed
With this change you will create popover on onAfterRendering even it's not needed. Please wait until we find a performed solution or rework this one.

2023-06-08 15:12 UTC, nnaydenow requested changes
Seems like it's because chrome released new popover attribute to each HTML element https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover

I would keep the old solution because it's improving performance and just rename the property.

2023-06-09 08:20 UTC, vladitasev approved these changes

2023-06-09 08:20 UTC, nnaydenow approved these changes

2023-06-09 08:21 UTC, merged