feat(ui5-menu): add delay between opening and closing submenu and sub menu items
SAP/ui5-webcomponents pull request #7246
Opened 2023-06-22 13:30 UTC by hinzzx

Previously, the sub-menus would **open** and **close** in an instant when **hovering over** or **hovering out** of a menu item. This sometimes caused unintentional closing of sub-menus, resulting in a poor user experience.

To address this, we made the following changes:

- We added a `300ms` delay when opening a sub-menu upon hovering over it.
- We added a `400ms` delay when hovering over another item or when hovering out of the menu item that opens the sub-menu.

Additionally, we made a modification to the `_openItemSubMenu()` method. We removed the forced firing of the "before-open" event into the main Menu component. This change prevents the loss of focus on sub-menu items when there are more than two nested sub-menus.

Fixes: #7078

2023-06-27 06:11 UTC, NHristov-sap commented on packages/main/src/Menu.ts
> +		}, 300);
It will be better if we have this in a constant.

2023-06-27 06:12 UTC, NHristov-sap commented on packages/main/src/Menu.ts
> +		}, 400);
Is there a reason to have different timeouts for opening and closing?
If yes, this also should be a constant.

2023-07-04 12:40 UTC, NHristov-sap commented
Looks good to me, but please adapt the test too.

2023-07-06 07:12 UTC, NHristov-sap approved these changes

2023-07-19 13:39 UTC, nnaydenow requested changes
At all do we need timeout maps since we clear every existing timeout when the new one is going to be created?

2023-08-04 06:58 UTC, nnaydenow commented
Looks good to me. Please add some information about the comment test.

2023-08-04 09:34 UTC, tsanislavgatev approved these changes
We fixed the test, so we are good to go.

2023-08-04 09:37 UTC, merged