fix(ui5-upload-collection): correct visualization of "mode" property
SAP/ui5-webcomponents pull request #7252
Opened 2023-06-23 12:27 UTC by LidiyaGeorgieva

Fixes #7111

**Thank you for your contribution!** 👏

### PR checklist
- [ ] Follow the [Commit message Guidelines](https://github.com/SAP/ui5-webcomponents/blob/main/docs/6-contributing/02-conventions-and-guidelines.md#commit-message-style)

For example: `fix(ui5-*): correct/fix sth` or `feat(ui5-*): add/introduce sth`. If you don't want the change to be part of the release changelog - use `chore`, `refactor` or `docs`.

- [ ] Add proper description about the background of the change and the change itself

- [ ] Link to an existing issue (if available)

Use `Fixes: {#PR_NUMBER}` to close the issue automatically when the PR is merged
or `Related to: {#PR_NUMBER}` to just create a link between the PR and the issue.

- [ ] Read the [Contributing Guidelines](https://github.com/SAP/ui5-webcomponents/blob/main/CONTRIBUTING.md)

2023-07-05 08:44 UTC, dimovpetar requested changes
1) Cursor should be "pointer" for selectable items
2) Mode "Delete" shouldn't have effect. By default the delete icon of every item is shown and it can be hidden through "hideDeleteButton"

2023-07-06 15:05 UTC, LidiyaGeorgieva commented
> 1. Cursor should be "pointer" for selectable items
> 2. Mode "Delete" shouldn't have effect. By default the delete icon of every item is shown and it can be hidden through "hideDeleteButton"

1. Done
2. Please check again, I can't reproduce the reported issue
3.  Story book samples enhanced

2023-07-07 08:28 UTC, dimovpetar requested changes
- In Fiori 3 themes, during selection, the color of the file name, thumbnail and the default slot has to be changed. Currently it looks like this:
![image](https://github.com/SAP/ui5-webcomponents/assets/32839090/876b6158-2ff1-4a40-a416-3a1a19d16f84)

2023-07-21 10:49 UTC, dimovpetar approved these changes

2023-07-21 10:51 UTC, merged