fix(ui5-token): adjust Horizon themes according to the specification
SAP/ui5-webcomponents pull request #7266
Opened 2023-06-28 08:15 UTC by niyap

Related to: #7001

2023-07-05 07:02 UTC, elenastoyanovaa requested changes

2023-07-05 07:02 UTC, elenastoyanovaa commented on packages/main/src/themes/base/Token-parameters.css
> +	--_ui5_token_focus_outline_color: var(--sapContent_FocusColor);
this variable is set to the same value in all places

2023-07-05 07:10 UTC, elenastoyanovaa reviewed
One general thing: I see that the semibold font family is applied, but I do not see any visual difference between the regular font family (of a non selected token) and the selected one. Could you please check? I remember that in UI5 there was a visual difference.

2023-07-05 13:09 UTC, niyap commented
> One general thing: I see that the semibold font family is applied, but I do not see any visual difference between the regular font family (of a non selected token) and the selected one. Could you please check? I remember that in UI5 there was a visual difference.

Yes, you are right. That is an issue which is not related to the ui5-token implementation, so it will be covered in a separate issue

2023-07-06 05:45 UTC, elenastoyanovaa approved these changes

2023-07-06 11:52 UTC, merged