docs(ui5-file-uploader): improve accessibility in storybook samples
SAP/ui5-webcomponents pull request #7282
Opened 2023-06-30 13:19 UTC by hinzzx

Related to the **`accessibleNameRef`** initiative of the story #5893

2023-06-30 13:30 UTC, unazko approved these changes

2023-06-30 13:32 UTC, unazko commented
Hi @hinzzx,

What about the documentation for the ui5-file-uploader? We could improve it in the same PR or in a separate one.
It is not recommended to not have any interactable components inside the default slot.

2023-06-30 13:53 UTC, ilhan007 requested changes
Just temporary -1 until we perform a release

2023-07-11 07:47 UTC, ilhan007 approved these changes

2023-07-11 07:50 UTC, merged