feat(ui5-tokenizer): change indicator's text when there are no visible tokens
SAP/ui5-webcomponents pull request #7327
Opened 2023-07-13 10:31 UTC by niyap

2023-07-13 11:29 UTC, elenastoyanovaa requested changes
is it applicable to add tests for the standalone tokenizer?

2023-07-13 11:29 UTC, elenastoyanovaa commented on packages/main/test/specs/MultiComboBox.spec.js
> +			resourceBundleTextItems = await browser.executeAsync(done => {
you can concat this in one browser.executeAsync, just pass a {} as a result of done.

2023-07-13 11:29 UTC, elenastoyanovaa commented on packages/main/test/specs/MultiInput.spec.js
> +			const mi = document.getElementById("mi-items");
same

2023-07-13 12:04 UTC, niyap commented
> is it applicable to add tests for the standalone tokenizer?

Currently, there is no separate file for ui5-tokenizer related tests. We can plan such action in future

2023-07-14 06:04 UTC, elenastoyanovaa requested changes
Please add an issue link or JIRA in the PR description

2023-07-14 07:34 UTC, elenastoyanovaa approved these changes

2023-07-23 20:25 UTC, merged