fix(ui5-busy-indicator): fix spacing between dots
SAP/ui5-webcomponents pull request #7523
Opened 2023-08-31 10:44 UTC by LidiyaGeorgieva

JIRA: 3114

2023-08-31 11:35 UTC, BorisDafov reviewed
I approve the request from UA perspective

2023-08-31 15:32 UTC, ilhan007 commented on packages/main/src/themes/BusyIndicator.css
> +	margin-right: 4px;
margin-inline-end

2023-09-01 11:53 UTC, gmkv requested changes

2023-09-01 11:53 UTC, gmkv commented on packages/main/src/themes/BusyIndicator.css
> +	margin-right: 1px;
please convert the px values to rem

2023-09-05 10:52 UTC, ilhan007 approved these changes

2023-09-05 12:52 UTC, merged