feat(ui5-popover): add "closeOnScroll" property
SAP/ui5-webcomponents pull request #7526
Opened 2023-08-31 13:47 UTC by TeodorTaushanov

Fixes #6829 
Fixes #7356

2023-09-08 15:02 UTC, gmkv submitted a review, later dismissed
Edit the pull request description to have every issue that will be closed on a separate line each with the keyword "Fixes" otherwise Github will only automatically close the first issue:

![image](https://github.com/SAP/ui5-webcomponents/assets/22086365/0eea41cd-7573-449c-b283-dbc44fab254e)

2023-09-11 11:06 UTC, alexandar-mitsev commented
> Fixes #6829 #7356 #7173

This change alone is not fixing any of the issues, so don't mark them with fixed. More instructions and code change is needed for the reporters.

2023-09-11 11:06 UTC, alexandar-mitsev requested changes
> Fixes #6829 #7356 #7173

This change alone is not fixing any of the issues, so don't mark them with fixed. More instructions and code change is needed for the reporters.

2023-09-15 10:11 UTC, gmkv reviewed
LGTM
We discussed and agreed that this logic better fits in Popover.ts

2023-09-15 11:38 UTC, alexandar-mitsev requested changes
The approach with giving a new option to close the popover on scroll does not really solve the issues.

This property will  be accessible only for popovers which the app developers have created themselfs, it will not be in their control when it comes to select, date picker or other controls with popovers.

Even for popovers for which they can set the property - they need to first know if there is sticky /fixed header on top which might not be the case.

Closing popover on scroll will also give inconsistent user experience with OpenUI5, which is good to have.

One thing which needs to be improved is to use the IntersectionObserver to see if popover opener is intersecting on scroll. This however does not fix the problem with sticky or fixed headers, which is a browser limitation.

2023-09-15 11:41 UTC, alexandar-mitsev requested changes

2023-09-15 11:41 UTC, alexandar-mitsev commented on packages/main/src/Popover.ts
In PopoverRegistry use the IntersectionObserver to close the popover when opener is not intersecting anymore

2023-09-15 11:46 UTC, closed without merging