fix(ui5-avatar): prevent hover effect on non-interactive avatars
SAP/ui5-webcomponents pull request #7611
Opened 2023-09-20 12:14 UTC by kgogov

2023-10-04 14:04 UTC, PetyaMarkovaBogdanova requested changes

2023-10-04 14:04 UTC, PetyaMarkovaBogdanova commented on packages/main/src/themes/Avatar.css
>  }
":host(:not([hidden])[pressed]:hover) {
	background: var(--sapButton_Selected_Hover_Background);
	border-color: var(--sapButton_Selected_Hover_BorderColor);
	color: var(--sapButton_Selected_TextColor);
}"

These styles need to be specified for :not([disabled]), interactive state, too.

2023-10-09 14:53 UTC, kgogov reviewed
Thank you for addressing this.
I've fixed my mistakes.

2023-10-10 09:59 UTC, PetyaMarkovaBogdanova approved these changes

2023-10-10 10:02 UTC, merged