fix(ui5-toolbar): documentation
SAP/ui5-webcomponents pull request #7667
Opened 2023-10-04 12:29 UTC by PetyaMarkovaBogdanova

Toolbar abstract item documentation

2023-10-17 09:30 UTC, yanaminkova requested changes
Some improvements for the documentation could be made for the following steps:

**1.** It would be better to mention the file name, because using words such as "component", "module" and so on is a bit confusing for the user. 
This is applicable for the whole documentation.
**2.** It is good to have basic example about how the structure should looks like:
```
class ToolbarDummyComponent extends ToolbarItem {
}
```
**3.** It would be more clear if you mention that the getter should be defined inside the class.
Also, the name is not correct - it should be ToolbarDummyComponentPopoverTemplate
**5.** It would be better if this step is before the one for the class definition (step 2). If the user follows and applies the code step by step, they would get an error if they do not paste the `@customElement` before the class.
6. Maybe add an additional step, for creating the both files  before this one. Include some basic code, showing what should be added inside them -`<ui5-button></ui5-button>` for example.
Also, add a bit more information how the template files should be imported: 
`import ToolbarDummyComponentTemplate from "./generated/templates/ToolbarDummyComponentTemplate.lit.js";`
and how the "lit.js" file is being created.
7. This step is a bit incomprehensible. Give an example how the mapping should looks like:
`<ui5-button >{{text}}</ui5-button>` 
and also, that the property "text" should be added to the `ToolbarDummyComponent.ts` file.
9. Mention that this is css class
10. Maybe, give an example how the import should looks like:
`import ToolbarDummyComponent from "./dist/ToolbarDummyComponent.js";`
and that it should be placed in` bundle.common.js` file of the corresponding  library.

Otherwise, everything works as expected.

2023-10-17 13:34 UTC, simonarangelova commented on docs/internal/Toolbar.md
> +*It will help for creation of the sample web component **ui5-toolbar-dummy-component***.
```suggestion
*It will guide you through the creation of the sample web component **ui5-toolbar-dummy-component***.
```

2023-10-17 13:34 UTC, simonarangelova commented on docs/internal/Toolbar.md
> +UI5-Toolbar is a composite web component, which slots different UI5 components, desigining them as abstract items. They can contain
```suggestion
UI5-Toolbar is a composite web component, that slots different UI5 components, desigining them as abstract items. They can contain
```

2023-10-17 13:34 UTC, simonarangelova commented on docs/internal/Toolbar.md
> +properties, slots and events and they can match the API of already existing component.
```suggestion
properties, slots and events, and they can match the API of already existing component.
```

2023-10-17 13:34 UTC, simonarangelova commented on docs/internal/Toolbar.md
> +In order to be suitable for usage inside ui5-toolbar, each component should align to following guidelines:
```suggestion
In order to be suitable for usage inside ui5-toolbar, each component should adhere to following guidelines:
```

2023-10-17 13:34 UTC, simonarangelova commented on docs/internal/Toolbar.md
> +3. The class should extend **ToolbarItem** base class, which should be also added as a dependency.
```suggestion
3. The class should extend **ToolbarItem** base class, which should also be added as a dependency.
```

2023-10-17 13:34 UTC, simonarangelova commented on docs/internal/Toolbar.md
> +5. After class declaration there should be a registry call for the item inside Toolbar. **registerToolbarItem** helper should be added as a dependency.
```suggestion
5. After the class declaration there should be a registry call for the item inside the toolbar. **registerToolbarItem** helper should be added as a dependency.
```

2023-10-17 13:34 UTC, simonarangelova commented on docs/internal/Toolbar.md
> +8. Inside the new component class there should be mapping of events that the component is subscribed to in order to pass them to the abstract item.
```suggestion
8. Inside the new component class there should be mapping of events that the component is subscribed to, in order to pass them to the abstract item.
```

2023-10-17 16:05 UTC, yanaminkova approved these changes

2023-10-18 07:47 UTC, simonarangelova approved these changes

2023-10-26 12:33 UTC, dobrinyonkov commented on docs/internal/Toolbar.md
> +compatible with ui5-toolbar. Currently developed items can be used without those efforts. They are:*
```suggestion
compatible with `ui5-toolbar`. Currently developed items can be used without those efforts. They are:*
```

2023-10-26 12:33 UTC, dobrinyonkov commented on docs/internal/Toolbar.md
> +    ToolbarButton.ts
```suggestion
ToolbarButton.ts
```

2023-10-26 12:33 UTC, dobrinyonkov commented on docs/internal/Toolbar.md
> +    ToolbarButton.hbs and ToolbarPopoverButton.hbs
```suggestion
ToolbarButton.hbs and ToolbarPopoverButton.hbs
```

2023-10-26 12:33 UTC, dobrinyonkov commented on docs/internal/Toolbar.md
> +   class ToolbarButton extends ToolbarItem
```suggestion
class ToolbarButton extends ToolbarItem
```

2023-10-26 12:33 UTC, dobrinyonkov commented on docs/internal/Toolbar.md
> +    import { registerToolbarItem } from "./ToolbarRegistry.js";
```suggestion
import { registerToolbarItem } from "./ToolbarRegistry.js";
```

2023-10-26 12:33 UTC, dobrinyonkov commented on docs/internal/Toolbar.md
> +    registerToolbarItem(ToolbarButton);
```suggestion
registerToolbarItem(ToolbarButton);
```

2023-10-26 12:33 UTC, dobrinyonkov commented on docs/internal/Toolbar.md
> +8. Inside the new component class there should be mapping of events that the component is subscribed to, in order to pass them to the abstract item.
Since we now have e section about the evetns we can omit the step 8

2023-10-26 12:33 UTC, dobrinyonkov commented on docs/internal/Toolbar.md
> +    import ToolbarButton from "./dist/ToolbarButton.js";
```suggestion
import ToolbarButton from "./dist/ToolbarButton.js";
```

2023-10-30 10:28 UTC, dobrinyonkov approved these changes

2023-10-30 10:33 UTC, merged