fix(ui5-view-settings-dialog): improve settings management
SAP/ui5-webcomponents pull request #7769
Opened 2023-10-30 14:51 UTC by tsanislavgatev

fixes: https://github.com/SAP/ui5-webcomponents/issues/7752

2023-10-30 20:17 UTC, hinzzx commented on packages/fiori/src/ViewSettingsDialog.ts
> +import UI5Element, { ChangeInfo } from "@ui5/webcomponents-base/dist/UI5Element.js";
maybe **import type { ChangeInfo }...**, on the next row, would be better for consistency in my opinion ?

2023-10-31 07:08 UTC, nnaydenow requested changes
https://sap.github.io/ui5-webcomponents/nightly/playground/?path=/docs/docs-development-understanding-components-metadata--docs#slot-configuration-settings

Could you please check invalidateOnChildChange option for the slot decorators?

2023-10-31 08:06 UTC, tsanislavgatev commented on packages/fiori/src/ViewSettingsDialog.ts
> +	_slotChanged!: boolean;
yes, missed when changing approach.

2023-10-31 08:09 UTC, tsanislavgatev commented
> https://sap.github.io/ui5-webcomponents/nightly/playground/?path=/docs/docs-development-understanding-components-metadata--docs#slot-configuration-settings
> 
> Could you please check invalidateOnChildChange option for the slot decorators instead of using the onInvalidation hook?

I've tried it but in this case it doesn't work as we have validation between confirmed/current state. The different states are because after close we keep the selection and when opened again we restore the selected state. Only with invalidation, it would still return the old state, that's why we overwrite the variable and we replace with the latest state.

2023-10-31 14:25 UTC, nnaydenow approved these changes

2023-10-31 14:25 UTC, hinzzx approved these changes

2023-10-31 16:08 UTC, merged

2023-11-10 09:01 UTC, lateefsofi commented
I don't see this fixing https://github.com/SAP/ui5-webcomponents/issues/7752 issue, can you please check it again