docs: new cem for Topic-RD components
SAP/ui5-webcomponents pull request #7778
Opened 2023-11-01 07:10 UTC by s-todorova

Related to: #7610

2023-11-08 10:00 UTC, gmkv requested changes
Try to think of a better name for this PR. Something that describes what your change does instead of "new cem" which doesn't tell me anything. You can refer to https://github.com/SAP/ui5-webcomponents/blob/main/docs/6-contributing/02-conventions-and-guidelines.md#commit-message-style for ideas.

2023-11-20 09:18 UTC, nnaydenow requested changes

2023-11-20 09:18 UTC, nnaydenow commented on packages/main/src/Carousel.ts
> + * @param selectedIndex the current selected index
We don't write param type for methods only. For events it's still required

2023-11-20 09:18 UTC, nnaydenow commented on packages/main/src/Carousel.ts
>  	 * @type {boolean}
remove type

2023-11-20 09:18 UTC, nnaydenow commented on packages/main/src/Carousel.ts
>  	 * @type {HTMLElement[]}
remove type tag

2023-11-20 09:18 UTC, nnaydenow commented on packages/main/src/Carousel.ts
> +	 * @type {Integer[]} the indices of the visible items
remove type and add explicit return type for the getter

2023-11-20 09:18 UTC, nnaydenow commented on packages/main/src/types/PopoverPlacementType.ts
>  	/**
remove type

2023-11-20 09:18 UTC, nnaydenow commented on packages/fiori/src/NotificationListItem.ts
> +	* @type {WrappingType}
Remove type

2023-11-20 09:18 UTC, nnaydenow commented on packages/fiori/src/NotificationListItem.ts
>  	* @type {Node[]}
remvoe type

2023-11-20 09:18 UTC, nnaydenow commented on packages/fiori/src/NotificationListItemBase.ts
>   * @public
reorder customElement and event decorator. first customElement and then event

2023-11-22 12:20 UTC, nnaydenow requested changes

2023-11-22 12:20 UTC, nnaydenow commented on packages/fiori/src/UploadCollectionItem.ts
>   * <br><br>
move default slot definition into the class comment

2023-11-22 12:20 UTC, nnaydenow commented on packages/main/src/BusyIndicator.ts
>  	 */
move default slot definition into the class comment

2023-11-22 12:20 UTC, nnaydenow commented on packages/main/src/Popup.ts
>   */
before-close => param type is required when describing event params

2023-11-22 12:20 UTC, nnaydenow commented on packages/main/src/TabContainer.ts
>  @customElement({
allItems => add return type

2023-11-22 12:20 UTC, nnaydenow commented on packages/main/src/Title.ts
>  	 * Available options are: <code>"H6"</code> to <code>"H1"</code>.
move default slot definition into the class comment

2023-11-22 12:20 UTC, nnaydenow commented on packages/main/src/types/TabContainerBackgroundDesign.ts
>  	 * @type {Transparent}
add privacy tag adn remove type

2023-11-26 20:04 UTC, nnaydenow commented on packages/main/src/Carousel.ts
>  	 */
add :void as return type here

2023-11-26 20:04 UTC, nnaydenow commented on packages/main/src/Carousel.ts
>  	 */
Same for isOpen/ close method of popup and responsivepopover

2023-11-26 20:04 UTC, nnaydenow commented on packages/main/src/Tab.ts
Add return type for getTabInStripDomRef method

2023-11-26 20:04 UTC, nnaydenow commented on packages/main/src/TabContainer.ts
>   * @constructor
getter allItems is treated as readonly property so we have to add default value for it. Since it's array we have to add empty array as default value

2023-11-26 20:04 UTC, nnaydenow commented on packages/fiori/src/SideNavigationItemBase.ts
>   * click/tap or by using the Enter or Space key.
reorder this comments. 

```ts
/**
 * event comment
 */
@event("click")
/**
 * class comment
 */
class SideNavigationItemBase extends UI5Element ... {}
```

2023-11-30 07:16 UTC, merged