docs: new cem for Topic-P components - ui5-select
SAP/ui5-webcomponents pull request #7850
Opened 2023-11-15 12:10 UTC by yanaminkova

Related: https://github.com/SAP/ui5-webcomponents/issues/7610

New cem for the following Topic-P components:
ui5-select

2023-11-15 12:54 UTC, nnaydenow requested changes
Migrate also Option.ts

2023-11-15 12:54 UTC, nnaydenow commented on packages/main/src/Select.ts
>  	 * <br><br>
Events should not have `@event` tag.

2023-11-15 12:54 UTC, nnaydenow commented on packages/main/src/Select.ts
>  	 * @since 1.0.0-rc.15
Only 1 since tag should exists

2023-11-15 12:54 UTC, nnaydenow commented on packages/main/src/Select.ts
>  	@slot({ "default": true, type: HTMLElement, invalidateOnChildChange: true })
Here we have to use ISelectOption as a type of the slot. If the interface doesn't exist create it as it's described.

2023-11-15 12:54 UTC, nnaydenow commented on packages/main/src/Select.ts
> +	get selectedOption(): IOption | undefined {
ISelectOption

2023-11-15 12:54 UTC, nnaydenow commented on packages/main/src/SelectMenu.ts
>  	 */
Use ISelectMenuOption as slot type

2023-11-15 12:54 UTC, nnaydenow commented on packages/main/src/SelectMenuOption.ts
>  	 */
Comment slots should be defined in the class comment.

2023-11-22 10:03 UTC, dobrinyonkov commented on packages/main/src/Interfaces.ts
> +interface IBreadcrumbsItem {
As it turned out, in a recent sync with the webcomponents team it was decided to have the interfaces of the non abstract components described with their public APIs. Abstract element/components on the other hand may not necessary implement an interface as they don't bring visual representation and extending them will not be of any value to consumers.

So this interface is not needed and its usages could be replaced with the BreadcrumbsItem type directly.

2023-11-22 10:03 UTC, dobrinyonkov commented on packages/main/src/Interfaces.ts
> +interface ISelectOption extends UI5Element {
As it turned out, in a recent sync with the webcomponents team it was decided to have the interfaces of the non abstract components described with their public APIs. Abstract element/components on the other hand may not necessary implement an interface as they don't bring visual representation and extending them will not be of any value to consumers.

So this interface is not needed and its usages could be replaced with the Option type directly.

2023-11-22 11:39 UTC, nnaydenow requested changes
Add default  tag for every public property with corresponding value for: Option, ProgressIndicator, Select, SelectMenuOption

Remove readonly tag from: src/types/IllustrationMessageType.ts

2023-11-22 11:39 UTC, nnaydenow commented on packages/main/src/Option.ts
>  	 * @name sap.ui.webc.main.Option.prototype.disabled
Remove name tag

2023-11-22 11:39 UTC, nnaydenow commented on packages/main/src/Breadcrumbs.ts
BreadcrumbsItem is an abstract component so we can use class instead of interface (interface is redundant)

2023-11-22 11:39 UTC, nnaydenow commented on packages/main/src/Option.ts
>  	 * Defines the additional text displayed at the end of the option element.
add default tag

2023-11-22 11:39 UTC, nnaydenow commented on packages/main/src/ProgressIndicator.ts
>  	 * @public
add default tag

2023-11-23 08:38 UTC, nnaydenow requested changes
- IllustrationMessageType's JSDoc comment in src/types/IllustrationMessageType.ts: 
        - `@readonly` tag is being used wrong or it's not part of enum JSDoc tags
- disabled's JSDoc comment in src/Option.ts: 
        - `@name` tag is being used wrong or it's not part of field JSDoc tags
- value's JSDoc comment in src/Option.ts: Default value is missing
- additionalText's JSDoc comment in src/Option.ts: Default value is missing
- displayValue's JSDoc comment in src/ProgressIndicator.ts: Default value is missing
- selectedOption's JSDoc comment in src/Select.ts: Default value is missing
- displayText's JSDoc comment in src/SelectMenuOption.ts: Default value is missing
- value's JSDoc comment in src/SelectMenuOption.ts: Default value is missing
- accessibilityAttributes's JSDoc comment in src/SelectMenuOption.ts: Default value is missing
- navigated's JSDoc comment in src/SelectMenuOption.ts: Default value is missing

2023-11-29 07:45 UTC, merged