fix(ui5-split-button): use correct params
SAP/ui5-webcomponents pull request #8140
Opened 2024-01-18 12:10 UTC by hinzzx

After updating the theming version and adapting new values of the css parameters, we found few issues we had in the SplitButton. 

With this change we apply the correct parameters, and align the Split Button with the Visual Specifications.

Fixes: #8136

2024-01-22 10:53 UTC, unazko requested changes
Hello @hinzzx,

The arrow button active state is as per specification now.
There is one issue left with the Emphasized button focused and active state:
![SplitButton_focused](https://github.com/SAP/ui5-webcomponents/assets/15860295/26b5d566-8913-4fec-879a-8113466aa805)

In the picture the Emphasized arrow button is set to `active `and `focused` .
The expected result in this case would be to see the focus border with a blue color.
Actual - the focus border is white and it's not recognizable.

2024-01-22 13:01 UTC, hinzzx commented
Hi,

Just for clarity we discussed offline that this is a separate issue not introduced by the change, for which we opened new incident.
It can be tracked [here](https://github.com/SAP/ui5-webcomponents/issues/8156)

Best regards,
Stoyan

2024-01-22 13:10 UTC, unazko approved these changes

2024-01-29 13:55 UTC, nnaydenow approved these changes

2024-01-29 13:56 UTC, merged