feat(ui5-side-navigation): add external link icon
SAP/ui5-webcomponents pull request #8199
Opened 2024-01-30 12:14 UTC by kskondov

if the navigation item is an external link, show the external link indicator

2024-02-02 09:54 UTC, LidiyaGeorgieva reviewed
expand/collapse arrows are missing in this sample:
https://sap.github.io/ui5-webcomponents/nightly/playground/fiori/pages/SideNavigationOnly/?sap-ui-theme=sap_horizon#events

2024-02-02 16:37 UTC, LidiyaGeorgieva reviewed
Please add more samples:
- in the Story books
- in the fixed part of the Side Navigation
- maybe example with disabled item

Please add tests.

Please check again if the color of the arrow is correct:
https://wiki.one.int.sap/wiki/display/CPDesign/Vertical+Navigation
![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/528a7dce-b655-42db-9903-b5da12e4eb90)
https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2650676561
![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/087351be-943d-40ac-85b1-aef04df7ecd3)
currently is "#1d2d3e;" for Horizon

2024-02-02 16:37 UTC, LidiyaGeorgieva commented on packages/fiori/src/SideNavigation.hbs
> +				></ui5-icon>
please fix indentation

2024-02-02 16:37 UTC, LidiyaGeorgieva commented on packages/fiori/src/SideNavigation.hbs
> +				></ui5-icon>
please fix indentation

2024-02-02 16:37 UTC, LidiyaGeorgieva commented on packages/fiori/src/SideNavigation.hbs
> +								<ui5-icon class="ui5-sn-item-external-link-icon"
please fix indentation

2024-02-02 16:37 UTC, LidiyaGeorgieva commented on packages/main/src/NavigationMenu.hbs
> +							<ui5-icon class="ui5-sn-item-external-link-icon"
please fix indentation

2024-02-06 15:09 UTC, TeodorTaushanov requested changes
External links in the overflow menu are not opened by keyboard Enter and Space key

2024-02-06 15:09 UTC, TeodorTaushanov commented on packages/fiori/src/SideNavigation.hbs
> +		   externalLink="{{_isExternalLink}}"
not needed

2024-02-06 15:09 UTC, TeodorTaushanov commented on packages/fiori/src/SideNavigation.hbs
> +			   externalLink="{{_isExternalLink}}"
not needed

2024-02-06 15:09 UTC, TeodorTaushanov commented on packages/fiori/src/SideNavigationItemBase.ts
> +	_externalLink!: boolean;
this is not used anywhere

2024-02-07 07:21 UTC, LidiyaGeorgieva reviewed
In SideNavigationOnly.html test page the arrow for expand/collapse is grey now. 
![image](https://github.com/SAP/ui5-webcomponents/assets/7242508/4914f072-1ba9-4c6c-a348-bba67f4e220b)
This is not correct.

2024-02-13 09:40 UTC, LidiyaGeorgieva reviewed
+1

2024-02-13 11:20 UTC, TeodorTaushanov approved these changes

2024-02-13 12:32 UTC, merged