[WIP][Discussion] feat: introduce Text web component
SAP/ui5-webcomponents pull request #8299
Opened 2024-02-19 07:12 UTC by ilhan007

**Note:** This is work in progress. The PR shows how Text as web component would look like and will serve as base for further discussions.

### API

```ts
/**
 * @class
 * @slot {Array<Node>} default - Defines the text of the component.
 * @since 1.23.0
 */
class Text extends UI5Element {
	/**
	 * Defines how the text of a component will be displayed,
	 * when there is not enough space for the entire text.
	 *
	 * <ul>
	 * <li>"None" - the text will truncate (default).</li>
	 * <li>"Normal" - the text will wrap.</li>
	 * </ul>
	 *
	 * @default "None"
	 * @public
	 */
	@property({ type: WrappingType, defaultValue: WrappingType.None })
	wrappingType!: `${WrappingType}`;

	/**
	 * Defines the number of lines the text should wrap before it truncates.
	 * <br><b>Note:</b> The property takes effect when <code>wrapping-type</code> is set to <code>Normal</code>.
	 *
	 * @default Infinity
	 * @public
	 */
	@property({ validator: Integer, defaultValue: Infinity })
	maxLines!: number;
```
### Usage

```html
<ui5-text>Simple Text</ui5-text>
<ui5-text wrapping-type="None">Text that will truncate</ui5-text>
<ui5-text wrapping-type="Normal">Text that will wrap</ui5-text>
<ui5-text wrapping-type="Normal" max-lines="3">Text wraps to 3 lines and truncate afterwards</ui5-text>
```

<img width="575" alt="Screenshot 2024-02-19 at 8 56 54" src="https://github.com/SAP/ui5-webcomponents/assets/15702139/d48c2c45-4098-423b-a6de-161ccf035327">

2024-02-27 09:46 UTC, MarcusNotheis commented
From UI5 Web Components for React Side we would love to see a `Text` web component.
It would be great if you could support the following props as well because then we would be to remove our custom `Text` implementation in the React wrapper:
- [ ] `emptyIndicator` (SAPUI5 uses the `emptyIndicatorMode` for with the [EmptyIndicatorMode enum](https://ui5.sap.com/#/api/sap.m.EmptyIndicatorMode) that)
- [ ] `renderWhitespace`
- [ ] `hyphenated` (SAPUI5 uses `wrappingType=[WrappingType](https://ui5.sap.com/#/api/sap.m.WrappingType)` for that)

2024-02-29 09:50 UTC, petyabegovska commented
Related to: #6788

2024-04-01 10:57 UTC, BorisDafov requested changes

2024-04-01 10:57 UTC, BorisDafov commented on packages/main/src/Text.ts
> + * - Do not use the `Text` if you need to reference input type of components (use ui5-label).
I suggest:
- Do not use the `ui5-text` if you need to reference the input of other components (use `ui5-label` instead).

2024-04-01 10:57 UTC, BorisDafov commented on packages/main/src/Text.ts
> + * The Text component displays text that can be used in any content area of an application.
I suggest this formatting when referencing the component:
`ui5-text`

2024-04-01 10:57 UTC, BorisDafov commented on packages/main/src/Text.ts
> + * - Use the `Text` if uou want to display text inside a form, table, or any other content area.
- Use the `ui5-text` if you ...

2024-04-01 10:57 UTC, BorisDafov commented on packages/main/src/Text.ts
> + * The Text component is fully adaptive to all screen sizes.
`ui5-text`

2024-04-01 10:57 UTC, BorisDafov commented on packages/main/test/pages/Text.html
> +	<title>Text Web Component</title>
<title>Text</title>

2024-04-02 13:46 UTC, BorisDafov commented
I approve the PR from UA perspective.

2024-04-09 09:04 UTC, dimovpetar approved these changes
Looks good 👍 
I will add test in another PR.

2024-04-10 06:29 UTC, ilhan007 commented
> From UI5 Web Components for React Side we would love to see a `Text` web component. It would be great if you could support the following props as well because then we would be to remove our custom `Text` implementation in the React wrapper:
> 
> * [ ]  `emptyIndicator` (SAPUI5 uses the `emptyIndicatorMode` with the [EmptyIndicatorMode enum](https://ui5.sap.com/#/api/sap.m.EmptyIndicatorMode) for that)
> * [ ]  `renderWhitespace`
> * [ ]  `hyphenated` (SAPUI5 uses `wrappingType` [WrappingType](https://ui5.sap.com/#/api/sap.m.WrappingType) for that)

Hi Marcus we had sync with design owners and all the features will be part of newest Text component design. Once the spec is finalised, we will implement them on top of the initial scope that we will merge now.

2024-04-10 06:29 UTC, merged