docs(ui5-dialog): add documentation for keyboard handling
SAP/ui5-webcomponents pull request #8355
Opened 2024-02-27 12:59 UTC by s-todorova

Missing information about keyboard shortcuts for dragging/resizing the dialog is now properly documented.

Fixes #8190

2024-02-27 14:58 UTC, LidiyaGeorgieva commented on packages/main/src/Dialog.ts
> + * When the <code>ui5-dialog</code> is focused and has the <code>draggable</code> property set, the user can move the dialog
The focus  should be on the header in order to use the keys to drag the dialog.
I suggest:
When the header of the code>ui5-dialog</code> is focused.

But in this case we should say first that the dialog is draggable (if its not - the header can't be focused :) ).
So this:
"When the <code>ui5-dialog</code> is focused and has the <code>draggable</code> property set"
could be said as this:
"When the <code>ui5-dialog</code> has the <code>draggable</code> property set and the header is focused"

2024-02-27 14:58 UTC, LidiyaGeorgieva commented on packages/main/src/Dialog.ts
> + * When the <code>ui5-dialog</code> is focused and has the <code>resizable</code> property set, the user can change the size of the dialog
same as above

2024-02-27 14:58 UTC, LidiyaGeorgieva commented on packages/main/src/Dialog.ts
> + * <li>[UP/DOWN] arrow keys - Move the dialog to the top/bottom.</li>
up/down

2024-02-27 14:58 UTC, LidiyaGeorgieva commented on packages/main/src/Dialog.ts
> + * <li>[LEFT/RIGHT] arrow keys - Move the dialog to the left/right.</li>
left/right

2024-02-28 10:39 UTC, BorisDafov requested changes

2024-02-28 10:39 UTC, BorisDafov commented on packages/main/src/Dialog.ts
> + * When the <code>ui5-dialog</code> has the <code>draggable<code> property set and the header is focused, the user can move the dialog
Better:
When the <code>ui5-dialog</code> has the <code>draggable<code> property set to <code>true<code> and the header is focused, the user can move the dialog

2024-02-28 10:39 UTC, BorisDafov commented on packages/main/src/Dialog.ts
> + * When the <code>ui5-dialog</code> has the <code>resizable<code> property set and the header is focused, the user can change the size of the dialog
same:
When the <code>ui5-dialog</code> has the <code>resizable<code> property set to <code>true<code> and the header is focused, the user can change the size of the dialog

2024-02-28 11:56 UTC, BorisDafov commented
I approve the change from UA perspective.

2024-02-28 12:57 UTC, LidiyaGeorgieva approved these changes

2024-02-28 13:00 UTC, merged