feat(ui5-button): add accessible-role api
SAP/ui5-webcomponents pull request #8366
Opened 2024-02-28 11:41 UTC by tsanislavgatev

fixes: https://github.com/SAP/ui5-webcomponents/issues/7612

2024-02-28 12:00 UTC, hinzzx requested changes

2024-02-28 12:00 UTC, hinzzx commented on packages/main/src/Button.ts
> +	accessibleRole!: string;
The type here should be `${ButtonAccessibleRole}` by convention. Same way as the above property `type`.

2024-02-28 12:04 UTC, hinzzx commented on packages/main/src/Button.ts
> +	 * NOTE: Use link role only with a press handler, which performs a navigation. In all other scenarios the default button semantics is recommended.
Very minor one:
> ...button semantics is recommended

semantics **are** recommended.

2024-02-28 14:14 UTC, hinzzx approved these changes
Looks good to me.

2024-02-28 16:29 UTC, nnaydenow requested changes
As discussed offline

2024-02-29 06:59 UTC, nnaydenow approved these changes

2024-02-29 07:39 UTC, merged