refactor(ui5-menu): adjust menu and sub-menu creation
SAP/ui5-webcomponents pull request #8367
Opened 2024-02-28 15:27 UTC by unazko

- The ui5-menu elements used for sub-menus are created only once and are being reused afterwards. They are no longer destroyed on close. This contributes to lowering the count of the slow DOM manipulation operations.

- There is now no differentiation between mobile and desktop device in regards to the display mechanism. In both cases we rely on the template to do the job as the components used for composition like ui5-list and ui5-responsive-popover do comply with the device.

Fixes: #7767
Fixes: #7423
Fixes: #6761
Related to: #7391

2024-03-01 06:53 UTC, tsanislavgatev requested changes
Two things:
Now when hovering with mouse on a menu with busy indicator, the focus goes to busy indicator.
We have arrow back in main menu on mobile view.

2024-03-01 09:22 UTC, NHristov-sap commented
One from me: on mobile view, there is a focus on disabled items, please check.

2024-03-01 15:45 UTC, unazko commented
> One from me: on mobile view, there is a focus on disabled items, please check.

The focus appears on an actual mobile device on item press. The same behavior was also reproducible before this change
and also this behavior actually comes from the `ui5-list` component. It could be reproduced there if the `ui5-item-click`
event gets prevented at application side.

2024-03-05 08:05 UTC, unazko commented
> I am not able to select the first item.(Space, Enter or Mouse click). Is that something with the sample or an issue?

The default behavior for the menu item is prevented at application level. I've improved the tooltip and menu item texts, in order to give detail about the item selection as we've discussed.

2024-03-05 10:14 UTC, NHristov-sap approved these changes

2024-03-05 12:55 UTC, tsanislavgatev approved these changes

2024-03-14 06:35 UTC, GerganaKremenska approved these changes

2024-03-25 08:04 UTC, nnaydenow approved these changes

2024-03-25 08:06 UTC, merged