fix(ui5-monthpicker): switch to two column layout on Islamic or Persian secondary calendar type
SAP/ui5-webcomponents pull request #8453
Opened 2024-03-15 12:05 UTC by hinzzx

Previously when `secondaryCalendarType` was set to `Islamic/Persian`, the texts of the months' names didnt had enough space in the cell to be displayed on one row, which wasnt the desired behavior.

Now, when any of those two calendar types is set as a `secondaryCalendarType`, when the end user is in month view of the calendar, the months are displayed in two column layout, instead of three, providing enough space for the texts to be displayed in one row.

Tested in both Cozy/Compact modes in following scenarios:

------------------------------

### Primary/SecondaryCalendarType:

1. Gregorian/Buddhist
2. Gregorian/Islamic
3. Gregorian/Japanese
4. Gregorian/Persian
5. Buddhist/Gregorian
6. Buddhist/Islamic
7. Buddhist/Japanese
8. Buddhist/Persian
9. Islamic/Gregorian
10. Islamic/Buddhist
11. Islamic/Japanese
12. Islamic/Persian
13. Japanese/Gregorian
14. Japanese/Buddhist
15. Japanese/Islamic
16. Japanese/Persian
17. Persian/Gregorian
18. Persian/Buddhist
19. Persian/Islamic
20. Persian/Japanese

#### Before
![image](https://github.com/SAP/ui5-webcomponents/assets/88034608/93b53e03-941f-4a34-bcb0-d612d89fd16f)

#### After
![image](https://github.com/SAP/ui5-webcomponents/assets/88034608/ff78e32c-e86c-4b27-ba01-ae364f59ede7)

Fixes: #7712

2024-03-28 11:00 UTC, nnaydenow requested changes

2024-03-28 11:00 UTC, nnaydenow commented on packages/main/src/MonthPicker.ts
> +let ROW_SIZE = 3; // months per row (4 rows of 3 months each)
lets make this variable per instance otherwise it might result in wrong visual appearance

2024-04-05 15:05 UTC, unazko commented on packages/main/src/MonthPicker.ts
> +		this._setTimestamp(parseInt(this._months[homePressed ? 0 : PAGE_SIZE - 1].timestamp));
According to the keyboard handling spec:

> Home: Moves focus to the first column of the same row and same page.
> End: Moves focus to the last column of the same row and same page. Decouples focus from selection.

Currently the Home/End moves focus from the first grid cells to the last grid cell thus changing the current row.

Additionally Home/End combination doesn't work if the primary calendar type is different than Gregorian.
Not that it worked before. We could log separate incident for those keyboard interactions.

2024-04-05 15:12 UTC, unazko requested changes
All fine except the Home/End keyboard interactions.

2024-04-10 14:36 UTC, nnaydenow commented on packages/main/src/MonthPicker.ts
> +		return this.secondaryCalendarType === "Islamic" || this.secondaryCalendarType === "Persian" ? 2 : 3;
minor: use values enum here - e.g. `CalendarType.Islamic`

2024-04-11 05:52 UTC, hinzzx commented on packages/main/src/MonthPicker.ts
> +type MonthInterval = Array<Month>;
Hmm, interesting the issue wasn't present yesterday on my end, perhaps the local sever wasn't refreshed.. Fixing it.

2024-04-12 09:01 UTC, unazko approved these changes

2024-04-26 07:26 UTC, tsanislavgatev requested changes
Two things, when changing from month to year picker, there is a moving of the header of the calendar. The arrows and the button are going lower. Also when primary and secondary calendar are the same and are one of the exceptions, the calendar is still in 2 columns

2024-04-26 13:38 UTC, hinzzx commented
> Two things, when changing from month to year picker, there is a moving of the header of the calendar.

The problem isn't introduced by the change.

> ...when primary and secondary calendar are the same and are one of the exceptions, the calendar is still in 2 columns

Done ✅

2024-04-26 13:54 UTC, nnaydenow commented
> > Two things, when changing from month to year picker, there is a moving of the header of the calendar.
> 
> The problem isn't introduced by the change.
> 
> > ...when primary and secondary calendar are the same and are one of the exceptions, the calendar is still in 2 columns
> 
> Done ✅

If you are not going to fix issue with current PR please reference issue where the issue could be tracked.

2024-05-10 07:19 UTC, tsanislavgatev approved these changes

2024-05-10 08:28 UTC, merged