feat(ui5-side-navigation): make items customizable
SAP/ui5-webcomponents pull request #8479
Opened 2024-03-20 08:42 UTC by TeodorTaushanov

2024-03-22 07:41 UTC, BorisDafov requested changes
minor

2024-03-22 07:41 UTC, BorisDafov commented on packages/fiori/src/themes/SideNavigationItemBase.css
> +in some themes, the border is drawn only on the bottom.
better:
at the bottom

2024-03-22 07:41 UTC, BorisDafov commented on packages/fiori/src/themes/SideNavigationItemBase.css
> +in high contrast themes the border is on all sides and there is extra border on hover */
I suggest:
In high contrast themes, the border is present on all sides, and there is an additional border that appears on hover.

2024-03-27 09:05 UTC, alexandar-mitsev requested changes
in the current implementation it is not possible to override the item in the overflow, maybe you can add a part to allow this?

2024-03-27 10:14 UTC, alexandar-mitsev approved these changes

2024-03-27 11:23 UTC, merged