fix(ui5-progress-indicator): hidden value design
SAP/ui5-webcomponents pull request #8545
Opened 2024-03-26 13:01 UTC by PetyaMarkovaBogdanova

Component padding reduced in case with hidden value.

2024-03-27 09:32 UTC, IlianaB approved these changes

2024-03-27 13:37 UTC, ilhan007 requested changes
For the other themes, this parameter `--_ui5_progress_indicator_padding_novalue` won't exist and basically it will be padding-top: undefined.

Even if this works and does not cause issue in the other themes, if we follow this pattern to only define variables for the themes they were initially required, soon it will get difficult to maintain the css params, because some of them will be defined only in these themes, some of them only in these themes.

That's why so far we used to define the variables always by adding them to the base params with some default value that is fine for most of the themes, and then overwrite them where needed (in this case sap_horizon, would not be also needed in sap_horizon_dark - they are usually pretty close in padding/margins). This way when you see a parameter, it's guaranteed to exist in all themes and you won't need to track it down and see where it comes from.

2024-03-28 07:27 UTC, PetyaMarkovaBogdanova commented
> For the other themes, this parameter `--_ui5_progress_indicator_padding_novalue` won't exist and basically it will be padding-top: undefined.
> 
> Even if this works and does not cause issue in the other themes, if we follow this pattern to only define variables for the themes they were initially required, soon it will get difficult to maintain the css params, because some of them will be defined only in these themes, some of them only in these themes.
> 
> That's why so far we used to define the variables always by adding them to the base params with some default value that is fine for most of the themes, and then overwrite them where needed (in this case sap_horizon, would not be also needed in sap_horizon_dark - they are usually pretty close in padding/margins). This way when you see a parameter, it's guaranteed to exist in all themes and you won't need to track it down and see where it comes from.

Thanks, Ilhan, for the informative remark.

2024-04-04 06:58 UTC, ilhan007 approved these changes

2024-04-08 08:32 UTC, PetyaMarkovaBogdanova commented
> last check: should not we also add the --_ui5_progress_indicator_padding_novalue: 0.3125rem; int sap_horizon_dark?

Horizon_dark theme seems to inherit parameters for ProgressIndicator from the main horizon theme (which imports also layout parameters), so for now I do not see the need to add it there also.

2024-04-17 15:26 UTC, ilhan007 approved these changes

2024-04-18 07:07 UTC, merged