Ui5 list 2.0
SAP/ui5-webcomponents pull request #8594
Opened 2024-04-01 12:59 UTC by yanaminkova

Renames the `mode` property  of `ui5-list`, `ui5-tree` and `ui5-upload-collection` to `selectionMode`.
 Also renames the `ListMode` enum to `ListSelectionMode` and its values as it follows:
 `SingleSelect` is renamed to `Single`
 `MultiSelect` is renamed to `Multiple`

BREAKING CHANGE: The `mode` property and the `ListMode` enum have been renamed.
If you have previously used the `mode` property and the `ListMode` values `SingleSelect` and `MultiSelect`:
```html
<ui5-list class="list" mode="SingleSelect">
<ui5-upload-collection mode="MultiSelect">
<ui5-tree mode="None" >
```
Now use `selectionMode`  and `Single`, `Multiple` instead:
```html
<ui5-list class="list" selection-mode="Single">
<ui5-upload-collection selection-mode="Multiple">
<ui5-tree selection-mode="None">
```

Related to https://github.com/SAP/ui5-webcomponents/issues/8461, https://github.com/SAP/ui5-webcomponents/issues/7887

2024-04-03 12:37 UTC, dimovpetar commented
UploadCollection changes looks good 👍

2024-04-03 18:33 UTC, plamenivanov91 requested changes
There might be additional occurrences except my comments where corrections should be made.

Also if you globally search for "mode=" in our project, you'll notice that there are quite a few files which are still using the old syntax. For example `ui5-webcomponents\packages\main\test\pages\TableSelection.html`

2024-04-03 18:33 UTC, plamenivanov91 commented on packages/fiori/src/UploadCollection.ts
> + * in `Single` and `Multiple` modes.
Minor:
might change it to selection modes instead of just modes. But it's okay to leave it as it is.

2024-04-03 18:33 UTC, plamenivanov91 commented on packages/fiori/src/ViewSettingsDialog.hbs
> +						selection-mode="SingleSelectBegin"
I believe SingleSelectBegin should be SingleStart.

Same for the rest of the occurrences.

2024-04-03 18:33 UTC, plamenivanov91 commented on packages/main/src/List.ts
> + * in `Single`, `SingleSelectBegin`, `SingleSelectEnd` and `Multiple` selection modes.
Again.

I believe `SingleSelectBegin`, `SingleSelectEnd` should be `SingleStart`, `SingleEnd`

2024-04-03 18:33 UTC, plamenivanov91 commented on packages/main/src/SelectPopover.hbs
> +			selection-mode="SingleSelectAuto"
SingleAuto

2024-04-04 06:08 UTC, yanaminkova commented
> There might be additional occurrences except my comments where corrections should be made.
> 
> Also if you globally search for "mode=" in our project, you'll notice that there are quite a few files which are still using the old syntax. For example `ui5-webcomponents\packages\main\test\pages\TableSelection.html`

The `mode` property of the Table has not been renamed to `selectionMode` as part of this change, since the scope of the task is limited to controls that utilize the `ListMode` enum. As such, the syntax within `ui5-webcomponents\packages\main\test\pages\TableSelection.html` should remain unchanged.

2024-04-04 08:46 UTC, closed without merging