fix(ui5-link): remove unnecessary transparent border
SAP/ui5-webcomponents pull request #8641
Opened 2024-04-04 12:41 UTC by unazko

Fixes: #8512

2024-04-11 11:39 UTC, hinzzx requested changes

2024-04-15 19:50 UTC, unazko commented on packages/main/src/themes/sap_horizon_hcb/Link-parameters.css
> +	--_ui5_link_outline: none;
Adjusted

2024-04-19 08:54 UTC, tsanislavgatev approved these changes

2024-04-23 06:52 UTC, hinzzx approved these changes

2024-04-23 09:32 UTC, merged