feat(ui5-*): integrate element internals in input components
SAP/ui5-webcomponents pull request #8685
Opened 2024-04-08 11:39 UTC by nnaydenow

Integrate the ElementInternals feature into UI5 web components. This enhancement allows input-like web components to behave as native input elements within HTML forms. As a result, the `features/InputElementsFormSupport.js` feature is now redundant and has been removed.

BREAKING CHANGE: The `features/InputElementsFormSupport.js` feature has been deleted.

Related: #8461

2024-05-09 12:37 UTC, nnaydenow commented on packages/base/src/features/InputElementsFormSupport.ts
> +export {
export type

2024-05-09 14:26 UTC, ilhan007 commented on packages/main/src/Button.ts
> +		if (this.internals_?.form && this._isSubmit) {
submitForm and resetForm internally check for  this.internals_?.form, we can simplify the condition a little bit.

2024-05-09 14:26 UTC, ilhan007 commented on packages/base/src/features/InputElementsFormSupport.ts
> +		return;
As discussed, you can shorten to single line:
element.internals_?.form.?

2024-05-09 14:29 UTC, ilhan007 reviewed
Overall, looks good to me.

We have to only commonly agree on the `updatesFormValue` new metadata entity name.

2024-05-10 07:34 UTC, nnaydenow commented
> Overall, looks good to me.
> 
> We have to only commonly agree on the `updatesFormValue` new metadata entity name.

As discussed offline the metadata name is changed to formValue

2024-05-10 09:23 UTC, pskelin requested changes

2024-05-10 09:23 UTC, pskelin commented on packages/main/src/MultiComboBox.ts
> +				formData.append(this.name, this.value);
value should be first, easier to check for apps. also we should document that the first value is what the user typed and the rest (if any) is the selected

2024-05-10 09:23 UTC, pskelin commented on packages/base/src/features/InputElementsFormSupport.ts
> +	return true;
this check is not doing anything, you can use a cast where it is used

2024-05-10 09:23 UTC, pskelin commented on packages/main/src/MultiInput.ts
> +				formData.append(this.name, this.value);
same as combo box, user typed value should be first (event if empty) and it should be documented

2024-05-13 11:26 UTC, ilhan007 approved these changes

2024-05-14 07:16 UTC, pskelin approved these changes

2024-05-14 10:02 UTC, merged