fix(ui5-menu-item): apply scoping to internal `Icon`
SAP/ui5-webcomponents pull request #8751
Opened 2024-04-12 13:17 UTC by Lukas742

Fixes #8745

This PR fixes the scoping issue of the `MenuItem`. I'm not sure if there's more changes necessary, but locally and when patching `@ui5/webcomponents` inside the node_modules it solved the issue for me. If there are more adjustments required, please feel free to use this branch.

2024-04-15 07:22 UTC, nnaydenow approved these changes

2024-04-15 07:25 UTC, nnaydenow requested changes
Hi @Lukas742,

There is no mechanism that merges child and parent dependencies atm, we have to add also dependencies that comes from parent class to the array.

Please change:
```ts
dependencies: [Icon]
```
to:
```ts
dependencies: [...CustomListItem.dependenices, Icon]
```

2024-04-16 06:04 UTC, vladitasev approved these changes

2024-04-16 06:04 UTC, merged

2024-04-16 06:50 UTC, Lukas742 commented
Thanks @vladitasev!