feat(ui5-avatar, ui5-avatar-gorup): introduce `accessibilityAttribute…
SAP/ui5-webcomponents pull request #8810
Opened 2024-04-19 16:09 UTC by ilhan007

Changes:

-  Avatar and AvatarGroup: remove private `ariaHaspopup` property from  in favour of  public `accessibilityAttributes` property.

old
```ts
@property()
ariaHaspopup!: string;
```
new
```ts
/**
* Defines the additional accessibility attributes that will be applied to the component.
* The following field is supported:
*
* - hasPopup: Indicates the availability and type of interactive popup element, such as menu or dialog, that can be triggered by the button.
* Accepts the following string values: `dialog` | `grid` | listbox` | `menu` | `tree`.
*/
@property({ type: Object })
accessibilityAttributes!: AvatarGroupAccessibilityAttributes;
```

-Use unified type for accessibilityAttributes property, describing which acc props are supported and the exact values they accept
- ListItem: remove obsolete `title` property from ListItem (as tooltip is available)
- Fix wrong usages of aria-label, aria-haspop being set mostly on ui5-button and ui5-link in the templates, while accessible-name and accessibilityAttributes: {hasPopup: "sth"} must be used.

**Don't**
```html
<ui5-button aria-label="{{overflowBtnAccessibleName}}"
<ui5-button aria-haspopup="menu""
```
**Do**
```html
<ui5-button accessible-name="{{overflowBtnAccessibleName}}"
<ui5-button .accessibilityAttributes="{{overflowBtnAccessibilityAttributes}}" // {hasPopup: "menu"}
```

2024-04-23 14:25 UTC, elenastoyanovaa requested changes

2024-04-23 14:25 UTC, elenastoyanovaa commented on packages/base/src/types.ts
> +	hasPopup?: "dialog" | "grid" | "menu" | "listbox" | "tree",
we have an HasPopup enum, can we use it instead?

2024-04-25 05:31 UTC, GerganaKremenska reviewed
looks good for team Rodopi components!

2024-04-26 05:22 UTC, yanaminkova commented
Looks good for team Pirin components.

2024-04-29 14:12 UTC, elenastoyanovaa reviewed
+1 from my side.

2024-04-29 14:14 UTC, elenastoyanovaa submitted a review, later dismissed
Don't forget to update the PR description as I assume that some parts are outdated after the last changes. Please inform me once the PR is submitted as we need to update the Accessibility Documentation Chapter after that.

2024-04-30 13:44 UTC, unazko commented on packages/main/src/Button.ts
>  import ButtonAccessibleRole from "./types/ButtonAccessibleRole.js";
Seems like the `ButtonAccessibleRole` enum is no longer needed. We could use the `AriaRole` enum instead. Same applies for the ui5-link component and the corresponding `accessibleRole` property. There is the following related PR: https://github.com/SAP/ui5-webcomponents/pull/8807/files

2024-04-30 16:18 UTC, ilhan007 commented on packages/main/src/SplitButton.ts
> -	_splitButtonAccInfo!: Record<string, boolean>;
@unazko _splitButtonAccInfo is removed because it's not used by any component, and it's private so not used by outside as well.

2024-05-08 06:54 UTC, dobrinyonkov approved these changes

2024-05-08 08:33 UTC, merged