refactor(ui5-li, ui5-list): changes accessibleRole type
SAP/ui5-webcomponents pull request #8825
Opened 2024-04-23 08:38 UTC by yanaminkova

Changes the type of `accessibleRole` property  for both `ui5-li` and `ui5-list`.

The `accessibleRole` property for both `ui5-li` and `ui5-list` has been updated from a string type to an enum type. 
Additionally, the new enums `ListItemAccessibleRole` and `ListAccessibleRole` have been introduced for these properties respectively.

Related to https://github.com/SAP/ui5-webcomponents/issues/8461, https://github.com/SAP/ui5-webcomponents/issues/7887

2024-04-24 10:47 UTC, nnaydenow reviewed
Seems related to:  #8810 . Lets wait until the other task is completed

Update: Ignore this comment

2024-04-24 13:43 UTC, nnaydenow requested changes

2024-04-24 13:43 UTC, nnaydenow commented on packages/main/src/ListItem.ts
> +	@property({ type: ListItemAccessibleRole })
enum properties should always have default value

2024-04-24 13:43 UTC, nnaydenow commented on packages/main/src/types/ListItemAccessibleRole.ts
> + * @public
add since to both newly introduced enums

2024-04-24 13:43 UTC, nnaydenow commented on packages/main/src/List.ts
>  	 * @default "list"
change jsdoc default value

2024-04-25 07:46 UTC, nnaydenow requested changes

2024-04-25 07:46 UTC, nnaydenow commented on packages/main/src/ListItem.ts
> +		return this.accessibleRole?.toLowerCase();
? no longer needed

2024-04-26 13:15 UTC, nnaydenow approved these changes
LGTM

2024-04-29 14:59 UTC, dobrinyonkov approved these changes

2024-04-30 05:45 UTC, merged