refactor(ui5-option): tooltip property added
SAP/ui5-webcomponents pull request #8827
Opened 2024-04-23 10:30 UTC by yanaminkova

The private `title` property, previously available in the `ui5-option` component, has been removed. 
It is replaced by a new property named `tooltip`.

BREAKING CHANGE: The `ui5-option` has new `tooltip` property, used for defining the text of the tooltip that would be displayed for the `ui5-option` component.
Now, you can set the tooltip of the `ui5-option` as it follows:
```html
<ui5-select id="selectTooltip">
    <ui5-option tooltip="Cozy">Cozy</ui5-option>
    <ui5-option tooltip="Compact">Compact</ui5-option>
    <ui5-option selected tooltip="Condensed">Condensed</ui5-option>
</ui5-select>
```

Related to: https://github.com/SAP/ui5-webcomponents/issues/8461, https://github.com/SAP/ui5-webcomponents/issues/7887

2024-04-24 13:36 UTC, nnaydenow approved these changes

2024-04-24 21:38 UTC, nnaydenow requested changes

2024-04-24 21:38 UTC, nnaydenow commented on packages/main/test/specs/Select.spec.js
> +
We can only test if the tooltip is correctly propagated. No need to check framework side if it's changed due property change

2024-04-25 07:57 UTC, nnaydenow requested changes

2024-04-25 07:57 UTC, nnaydenow commented on packages/main/test/specs/Select.spec.js
> +
I meant to check if the tooltip is propagated to the list item correctly. Here is an example (in addition to make it work we have to add `stable-dom-ref="tooltip-test-option"` attribute to the option that we are testing):
```js
	it("Tooltip propagation", async () => {
		const select = await browser.$("#mySelect");
		const tooltip = "Tooltip text"

		await select.click();

		const popover = await select.shadow$("[ui5-responsive-popover]");
		const option = await select.shadow$("[ui5-option]");
		const listItem = await popover.$("[data-ui5-stable='tooltip-test-option']")

		assert.strictEqual(await option.getProperty("tooltip"), tooltip, "Tooltip is correct");
		assert.strictEqual(await listItem.getProperty("tooltip"), tooltip, "Tooltip is correctly propagated");
	});
```

2024-04-29 14:00 UTC, dobrinyonkov approved these changes

2024-04-30 05:47 UTC, merged