WIP: refactor(ui5-combobox): integrate properly popover api
SAP/ui5-webcomponents pull request #8842
Opened 2024-04-24 15:15 UTC by nikoletavnv

Adjustments in ui5-combobox after integrating the popover api

2024-05-28 11:59 UTC, ivoplashkov requested changes
A couple issues I have found:
- focus the first input with value state and press Tab, value state popover does not get closed and next one gets opened.
- Focus the input with valueState=“Warning” press escape to close the popover and then tab out (styles remain as it is focused) and focus it again, it does not get opened anymore.

2024-05-30 16:05 UTC, nikoletavnv commented
> A couple issues I have found:
> 
> * focus the first input with value state and press Tab, value state popover does not get closed and next one gets opened.
> * Focus the input with valueState=“Warning” press escape to close the popover and then tab out (styles remain as it is focused) and focus it again, it does not get opened anymore.

These 2 are fixed now.

2024-06-03 11:05 UTC, ivoplashkov requested changes
I have left some comments but I have realized that you don't have the latest changes from the main branch. The logic behind the group items is quite different now, could you please check and I will review again?

2024-06-03 13:49 UTC, nikoletavnv commented on packages/main/src/ComboBox.ts
> +			this._getPicker()!.querySelector<HTMLInputElement>("[ui5-input]")!.value = this.value;
Done

2024-06-03 13:49 UTC, nikoletavnv commented on packages/main/src/ComboBox.ts
> +			this._closeRespPopover(null, true);
Done

2024-06-04 06:57 UTC, ivoplashkov requested changes
1. The sample with valueState="Information" does not show valueState popover upon focusing the input.
2. The sample with valueState="Erorr" and link, if you click the link and then press Tab, focus get trapped. ( seems like the valueState could be focused upon click, which is incorrect, I think we need to move the fake focus to the valueState only on arrow navigation)

2024-06-06 09:21 UTC, ivoplashkov requested changes
As discussed:

1. Focus should go to the first real item in case of grouping.
2. When face focus goes to the ValueStateMessage and user presses Tab, focus should go to the link if any.
3. Write some tests for the common issues you have fixed.

2024-06-07 06:48 UTC, nikoletavnv commented
> 1. The sample with valueState="Information" does not show valueState popover upon focusing the input.
> 2. The sample with valueState="Erorr" and link, if you click the link and then press Tab, focus get trapped. ( seems like the valueState could be focused upon click, which is incorrect, I think we need to move the fake focus to the valueState only on arrow navigation)

These issues are fixed now

2024-06-07 06:49 UTC, nikoletavnv commented
> As discussed:
> 
> 1. Focus should go to the first real item in case of grouping.
> 2. When fake focus goes to the ValueStateMessage and user presses Tab,  real focus should go to the link if any.
> 3. Write some tests for the common issues you have fixed.

Done

2024-06-11 09:37 UTC, ivoplashkov commented on packages/main/src/ComboBox.ts
> +
Could we please think of another approach for this use case as this seems to be very complex and unreliable. If you think that handling this case means spending a lot of time on research we may create another BLI for this case only ( I have discussed this with our PO ).

2024-06-13 11:28 UTC, ivoplashkov approved these changes

2024-06-13 11:32 UTC, merged