refactor: rename ValueState values
SAP/ui5-webcomponents pull request #8864
Opened 2024-04-26 11:28 UTC by ilhan007

BREAKING CHANGE: If you previously used `ValueState.Warning`, `ValueState.Error` or `ValueState.Success`, they are now renamed to `ValueState.Critical`, ValueState.Negative or `ValueState.Positive`. All components with valueState property are affected:
To be described

2024-04-26 21:29 UTC, nnaydenow requested changes
To things to discuss:
- some of the css classes related to value states are renamed and others not
- should we find and replace all value state translations texts for consistency?

2024-04-26 21:29 UTC, nnaydenow commented on packages/main/src/types/HighlightTypes.ts
> +	Success = "Positive",
Change enum keys to the new ones.

2024-04-26 21:29 UTC, nnaydenow commented on packages/main/src/TreeItemBase.ts
> +	 * Available options are: `"None"` (by default), `"Positive"`, `"Critical"`, `"Information"` and `"Critical"`.
We have `Critical` twice. Maybe you though `Negative` on the second one.

2024-04-27 16:51 UTC, ilhan007 commented
- the translation texts keys we can change, but the values should remain the same for now, they will be update later in the specs
- the classes we can change, I thought it will become huge change and focused on the API changes

2024-04-27 16:52 UTC, nnaydenow approved these changes

2024-04-27 17:33 UTC, merged