feat(ui5-menu-separator): add new component
SAP/ui5-webcomponents pull request #8871
Opened 2024-04-29 06:38 UTC by didip1000

New component that can be slotted with menu items

BREAKING CHANGE: `startsSection` property removed from MenuItems

Before: 
```html
<ui5-menu>
    <ui5-menu-item text="Item A" ></ui5-menu-item>
    <ui5-menu-item text="Item B" starts-section></ui5-menu-item>
</ui5-menu>
```

Now:
```html
<ui5-menu>
    <ui5-menu-item text="Item A" ></ui5-menu-item>
    <ui5-menu-separator></ui5-menu-separator>
    <ui5-menu-item text="Item B" starts-section></ui5-menu-item>
</ui5-menu>
```

[Add image for how it looks once done]

!! PR & DESCRIPTION A WIP !!

2024-05-09 06:57 UTC, vladitasev commented
The "Now:" section of the commit description still contains the removed property (`starts-section`)

2024-06-05 08:04 UTC, BorisDafov requested changes
I suggest to rename the "Usage" section to "Structure" (lines 62-65), and to include the information about the ui5-menu-separator there:

Structure
Can hold two types of entities:
•	`ui5-menu-item` components.
•	`ui5-menu-separator` to separate menu items with a line.
An arbitrary hierarchy structure can be represented by recursively nesting menu items.

2024-06-05 09:19 UTC, unazko approved these changes

2024-06-06 09:21 UTC, tsanislavgatev requested changes
There is hover effect over the menu-separator in the menu. And we need to fix it.
setting the pointer events to none might do the job.

2024-06-06 09:21 UTC, tsanislavgatev commented on packages/main/src/Menu.ts
> +		const menuItems = this._menuItems;
Why not just `this._menuItems[0]?.focus();`?

2024-06-06 09:21 UTC, tsanislavgatev commented on packages/main/src/MenuItem.ts
> +	get _menuItems() {
Why are the getters for the same thing in the same change different?  Can we unify them?

2024-06-06 09:21 UTC, tsanislavgatev commented on packages/main/src/themes/MenuSeparator.css
> +	-ms-user-select: none;
this is redundant. we no longer support IE

2024-06-07 13:51 UTC, didip1000 commented
> There is hover effect over the menu-separator in the menu. And we need to fix it. setting the pointer events to none might do the job.

Setting pointer events to none will cause the focus to go back to the parent, but I removed the hover effect with css

2024-06-10 08:11 UTC, nnaydenow requested changes
Also the API of the component looks strange when all jsdoc related comments are addressed:

![image](https://github.com/SAP/ui5-webcomponents/assets/31909318/57e47fe3-107e-4afb-8bec-86ec026398dc)

2024-06-10 08:11 UTC, nnaydenow commented on packages/main/src/MenuSeparator.ts
> + * @public
add `@implements` jsdoc tag to the class.

remove `@abstract` tag since this class has its own template.

change `@extends` to ListItem

2024-06-10 08:11 UTC, nnaydenow commented on packages/main/src/MenuSeparator.ts
> +	 * @default true
I would leave that getter without JSDoc comment

2024-06-13 12:06 UTC, didip1000 commented
> Also the API of the component looks strange when all jsdoc related comments are addressed:

We reworked the separator and it no longer inherits from ListItem so those properties and elements are not being inherited either :)

2024-06-13 12:07 UTC, unazko approved these changes
The code looks clean with the new changes and works as expected.

2024-06-13 12:47 UTC, tsanislavgatev requested changes

2024-06-13 12:47 UTC, tsanislavgatev commented on packages/main/src/MenuSeparator.ts
> +class MenuSeparator extends UI5Element implements IMenuItem {
The List component accepts types ListItemBase | ListItemGroup, please extend the ListItemBase, as it was done before.

2024-06-17 12:02 UTC, unazko commented
Retested. The solution continues to work as expected.

2024-06-17 12:43 UTC, tsanislavgatev approved these changes

2024-06-20 13:39 UTC, nnaydenow approved these changes

2024-06-21 06:37 UTC, BorisDafov approved these changes

2024-06-21 06:47 UTC, merged