fix(ui5-multi-input): focus tokens on BACKSPACE for inputs of type 'Number' and 'Email'
SAP/ui5-webcomponents pull request #8897
Opened 2024-05-02 11:05 UTC by ndeshev

fixes #8712

2024-05-07 08:21 UTC, nikoletavnv approved these changes

2024-05-07 09:29 UTC, nnaydenow requested changes
Fix doesn't fully fix the issue. Please recheck the case where the cursor is at the beginning:
 
https://github.com/SAP/ui5-webcomponents/assets/31909318/372a4306-50c4-4e96-88af-a41d7416a496

2024-05-07 10:09 UTC, ndeshev commented
2.0 PR - #8866

2024-05-09 06:58 UTC, nnaydenow approved these changes

2024-05-09 08:05 UTC, merged