fix(ui5-notification-list-item): focus is no longer trapped in loading item
SAP/ui5-webcomponents pull request #8969
Opened 2024-05-15 10:48 UTC by dimovpetar

Fixes https://github.com/SAP/ui5-webcomponents/issues/8768

2024-07-02 13:22 UTC, BorisDafov commented
I approve the PR from UA perspective

2024-07-08 10:30 UTC, TeodorTaushanov requested changes
"arrow" navigation in fiori/test/pages/NotificationListItem.html doesn't work correctly.

2024-07-08 11:03 UTC, TeodorTaushanov approved these changes

2024-07-08 11:04 UTC, dimovpetar commented
> NotificationListItem.html

added title before every list in the test page to make it clear that those are separate lists

2024-07-08 12:02 UTC, merged