refactor(ui5-multi-combobox): introduce nested grouping of items
SAP/ui5-webcomponents pull request #9072
Opened 2024-05-28 06:47 UTC by ivoplashkov

Removes the `ui5-mcb-group-item` component.

BREAKING CHANGE: The `ui5-mcb-group-item` component is removed. Groups can now be created with the `ui5-mcb-group`. Instead of using `ui5-mcb-group-item` as separator in a flat structure:
```html
<ui5-multi-combobox placeholder="Select a country">
	<ui5-mcb-group-item text="Asia"></ui5-mcb-group-item>
        <ui5-mcb-item text="Afghanistan"></ui5-mcb-item>
        <ui5-mcb-item text="China"></ui5-mcb-item>
        <ui5-mcb-item text="India"></ui5-mcb-item>
        <ui5-mcb-item text="Indonesia"></ui5-mcb-item>
	<ui5-mcb-group-item text="Europe"></ui5-mcb-group-item>
        <ui5-mcb-item text="Austria"></ui5-mcb-item>
        <ui5-mcb-item text="Bulgaria"></ui5-mcb-item>
        <ui5-mcb-item text="Germany"></ui5-mcb-item>
        <ui5-mcb-item text="Italy"></ui5-mcb-item>
</ui5-multi-combobox>
```
The API supports nesting of `ui5-mcb-item` components inside an `ui5-mcb-group`:
```html
<ui5-multi-combobox placeholder="Select a country">
	<ui5-mcb-group text="Asia">
		<ui5-mcb-item text="Afghanistan"></ui5-mcb-item>
		<ui5-mcb-item text="China"></ui5-mcb-item>
		<ui5-mcb-item text="India"></ui5-mcb-item>
		<ui5-mcb-item text="Indonesia"></ui5-mcb-item>
	</ui5-mcb-group>
	<ui5-mcb-group text="Europe">
		<ui5-mcb-item text="Austria"></ui5-mcb-item>
		<ui5-mcb-item text="Bulgaria"></ui5-mcb-item>
		<ui5-mcb-item text="Germany"></ui5-mcb-item>
		<ui5-mcb-item text="Italy"></ui5-mcb-item>
	</ui5-mcb-group>
</ui5-multi-combobox>
```

Relates to https://github.com/SAP/ui5-webcomponents/issues/8461

2024-05-29 13:43 UTC, ndeshev commented on packages/main/src/MultiComboBox.ts
> +	getItems(): Array<IMultiComboBoxItem> {
add a bit of documentation for this method

2024-05-29 13:43 UTC, ndeshev commented on packages/website/docs/_components_pages/main/MultiComboBox/MultiComboBoxGroupItem.mdx
> +slug: ../../MultiComboBoxGroup
MultiComboBoxItemGroup

2024-05-29 13:43 UTC, ndeshev commented on packages/main/README.md
> +| Multi ComboBox Group     | `ui5-mcb-group`             | comes with `ui5-multi-combobox`                            |
Multi ComboBox Item Group

2024-05-30 06:27 UTC, ndeshev approved these changes

2024-05-30 07:12 UTC, elenastoyanovaa requested changes
When you press F4 on a MCB with grouping the focus stays in the input, which interrups the screen reader modes. 
Other that that the speech output is as expected.

2024-06-10 07:59 UTC, merged