refactor(ui5-tag): remove design Color Set 3
SAP/ui5-webcomponents pull request #9115
Opened 2024-06-04 08:18 UTC by kskondov

Removes Color Set 3 from the design types

**BREAKING CHANGE**: If you have previously used Color Set3 as design type it is no longer available

2024-06-04 11:47 UTC, TeodorTaushanov requested changes
Also remove all --ui5-tag-color-scheme-1/10-background/border/color parameter definitions and also --_ui5-tag-default-background and --_ui5-tag-default-color

2024-06-04 12:20 UTC, GerganaKremenska requested changes
remove #XACT: ARIA announcement for the badge
TAG_DESCRIPTION_BADGE=Badge from messagebundle.properties

2024-06-06 13:08 UTC, TeodorTaushanov requested changes
There are some [_is-tag-design] CSS selectors. Now the Tag is always [_is-tag-design]

2024-06-07 10:21 UTC, TeodorTaushanov approved these changes

2024-06-10 15:03 UTC, GerganaKremenska approved these changes

2024-06-11 09:43 UTC, merged