refactor(ui5-tag): wrap text by default
SAP/ui5-webcomponents pull request #9126
Opened 2024-06-05 10:26 UTC by LidiyaGeorgieva

The text of `ui5-tag` now wraps by default.

BREAKING CHANGE: `wrapping-type` property default value has changed from `None` to `Normal`. Before:
```html
<ui5-tag>In Process</ui5-tag>
```

Now:
```html
<ui5-tag>In Process</ui5-tag>
```

Related to https://github.com/SAP/ui5-webcomponents/issues/8461

2024-06-05 14:23 UTC, BorisDafov commented
I approve the PR from UA perspective

2024-06-11 07:57 UTC, GerganaKremenska requested changes

2024-06-11 07:57 UTC, GerganaKremenska commented on packages/main/test/pages/Tag.html
remove all occurences of wrapping-type="Normal" as this is the default and it is applied by default.

2024-06-11 07:57 UTC, GerganaKremenska commented on packages/main/src/themes/Tag.css
> +:host([_is-tag-design]) [ui5-icon],
_is-tag-design is regarding design="Set3", as it is deleted with this pull https://github.com/SAP/ui5-webcomponents/pull/9115/files#diff-9dc0bd3858a768f765383f49db1243e566677dae75941c9e40048637c57e0b7d

You can delete this selector regarding"_is-tag-design"

2024-06-11 07:57 UTC, GerganaKremenska commented on packages/main/src/themes/base/Tag-parameters.css
> +	--_ui5-tag-icon-height: calc(var(--_ui5-tag-height) - 2px); /* remove width of the border since tag root is with box-sizing:border-box*/
change 2px to 0.125rem

2024-06-11 07:57 UTC, ilhan007 commented on packages/main/src/themes/Tag.css
> +	height: calc(var(--_ui5-tag-height) - 2px); /* remove width of the border since tag root is with box-sizing:border-box*/
you have the calculation in a parameter : `--_ui5-tag-icon-height` in base/Tag-parameters.css, or it does not work somehow?

2024-06-12 07:29 UTC, merged