refactor(ui5-li-notification): wrap text by default
SAP/ui5-webcomponents pull request #9128
Opened 2024-06-05 12:11 UTC by LidiyaGeorgieva

The title and description of `ui5-li-notification` now wrap by default.

BREAKING CHANGE: `wrapping-type` property default value has changed from `None` to `Normal`. Before:
```html
<ui5-li-notification title-text="Message 1">
	Description with details.
</ui5-li-notification>

```

Now:
```html
<ui5-li-notification title-text="Message 1">
	Description with details.
</ui5-li-notification>

```

Related to https://github.com/SAP/ui5-webcomponents/issues/8461

2024-06-05 14:55 UTC, BorisDafov requested changes

2024-06-05 14:55 UTC, BorisDafov commented on packages/fiori/src/NotificationListItem.ts
> +	* a `More/Less` button would be displayed.
I suggest:
Defines if the `titleText` and `description` should wrap when there is not enough space. The possible values are:
•	"Normal" (default) - the texts should wrap.
•	"None" – the texts should truncate, and a `More/Less` button should be displayed.

2024-06-06 07:34 UTC, BorisDafov reviewed
I approve the PR from UA perspective

2024-06-11 10:17 UTC, GerganaKremenska commented on packages/fiori/test/pages/NotificationListGroupItem.html
Should we add wrapping-type="None", or just remove it so we can show case the new behavior? It looks a little wierd to change the default just so we can preset it with the old value?

2024-06-11 11:13 UTC, LidiyaGeorgieva commented on packages/fiori/test/pages/NotificationListGroupItem.html
We will not change the default behavior for now.
I'm deleting this pull request.

2024-06-11 11:13 UTC, closed without merging