refactor(ui5-li): wrap by default
SAP/ui5-webcomponents pull request #9178
Opened 2024-06-11 10:42 UTC by yanaminkova

The text of `ui5-li` and `ui5-notification-list` now wraps by default.
Also, the `wrappingType` property of `ui5-li` is not public.

Before: 
```html
<ui5-li-notification title-text="Very very very long text"></ui5-li-notification>
```

Now:
```html
<ui5-li-notification title-text="Very very very long text"></ui5-li-notification>
```

Related to https://github.com/SAP/ui5-webcomponents/issues/8461, https://github.com/SAP/ui5-webcomponents/issues/7887

2024-06-14 08:57 UTC, dobrinyonkov commented
This is considered breaking change so let's add it to the commit message body.

2024-06-14 08:58 UTC, dobrinyonkov commented
Hello @SAP/ui5-webcomponents-topic-rd, could you please check this PR in terms of NoticationList updates? 
Thanks!

2024-06-14 09:22 UTC, dobrinyonkov commented
The fixed 5rem height of the ListItem, is blocking/cutting the title text (perhaps the description and additionalText too). You can test this by adding wrapping-type="Normal" to a the first list item in the List.html file. This way the wrapping styles are applied.

BTW,  shouldn't the text wrap even without setting that attribute? Perphaps we should review this once again with design team, once the above issue is resolved.

2024-06-14 10:31 UTC, LidiyaGeorgieva requested changes
The notifications have special type of wrapping/truncation concept. It the text is truncated there will be always a "More" button to show the full text.
Therefore the notifications doesn't need to wrap by default.
Please exclude them from this pull request.

2024-06-17 11:22 UTC, dobrinyonkov commented on packages/main/src/ListItemStandard.ts
>  	 * @since 1.5.0
the since tag needs to ajdusted to 2.0

2024-06-27 07:01 UTC, dobrinyonkov commented
There is a richer design spefication about the wrapping of the list items that needs to be implemented. The property wrappingType of the ui5-li is currently private so this change would not be a breaking one. The work on this will continue in the coming sprints.

2024-06-30 17:28 UTC, ilhan007 commented
Also, don't forget to remove the BREAKING CHANGE section, If we keep it and merge it after 2.0 - it would trigger the release of new major.

2024-07-30 00:25 UTC, closed without merging