feat(ui5-menu-item): add accessibility attributes
SAP/ui5-webcomponents pull request #9333
Opened 2024-06-28 08:34 UTC by NHristov-sap

This PR introduces new property **accessibilityAttributes** in `ui5-menu-item` component.

It has 2 properties that affect the accessibility attributes of the menu item: 

`role` - can be used to change the devault **menuitem** role to something different (for example **menuitemcheckbox**) `ariaKeyShortcuts` - can be used to add **aria-keyshortcuts** attribute value to an item that has a shortcut key defined.

BGSOFUIBALKAN-8351
BGSOFUIBALKAN-8315

2024-07-02 16:27 UTC, unazko approved these changes
Tested the change with the screen reader. Everything is readout like expected.

2024-07-03 13:58 UTC, dobrinyonkov approved these changes
Looks good to me!

2024-07-03 14:52 UTC, tsanislavgatev approved these changes

2024-07-08 06:22 UTC, nnaydenow requested changes

2024-07-08 06:22 UTC, nnaydenow commented on packages/main/src/MenuItem.ts
> +	 * @since 2.0
`since @2.1.0`

2024-07-08 06:29 UTC, NHristov-sap commented on packages/main/src/MenuItem.ts
> +	 * @since 2.0
done

2024-07-08 07:42 UTC, nnaydenow approved these changes

2024-07-08 07:48 UTC, merged