feat(ui5-time-picker): add required, accessibleName & accessibleNameRef
SAP/ui5-webcomponents pull request #9352
Opened 2024-07-01 14:33 UTC by didip1000

With this change, users can now set `required`, `accessible-name` and `accessible-name-ref` properties for `ui5-time-picker`.

### Required
This property defines if time pickers are required in forums. Time picker can be used in a form as follows:

```HTML
<form>
    <ui5-time-picker required></ui5-time-picker>
    <ui5-button type="Submit">Submit</ui5-button>
</form>
```

### Accessible Name
This property defines the aria label for the time picker. In the following example, a screen reader will read out "Pick a time" when focused on the picker input:

```HTML
<ui5-time-picker accessible-name="Pick a time"></ui5-time-picker>
```

### Accessible Name Ref
Reference to other components that define the aria label for the time picker. In the following example, a screen reader will read out "Pick a time" when focused on the picker input:

```HTML
<ui5-label id="label">Pick a time</ui5-label>
<ui5-time-picker accessible-name-ref="label"></ui5-time-picker>
```

Closes: #5895

2024-07-01 18:14 UTC, nnaydenow commented on packages/main/test/specs/TimePicker.spec.js
> +		const innerInput = await timepicker.shadow$("ui5-input").shadow$("input");
Adjust for `FormSupport.spec.js` too

2024-07-02 17:05 UTC, unazko commented on packages/main/src/TimePicker.ts
> +		if (isEnter(e) && this._internals?.form) {
We could move this conditional on line 602 similar to how it is done for the `ui5-date-picker`.
That way the user won't be able to submit the form when the value help is open and interactions won't be mixed.

2024-07-04 06:49 UTC, unazko approved these changes

2024-07-04 12:22 UTC, tsanislavgatev requested changes

2024-07-04 12:22 UTC, tsanislavgatev commented on packages/main/src/TimePicker.ts
> +	 * @default ""
undefined

2024-07-04 12:22 UTC, tsanislavgatev commented on packages/main/src/TimePicker.ts
> +	 * @default ""
undefined

2024-07-08 07:23 UTC, merged