fix(ui5-radio-button): fix selection issue
SAP/ui5-webcomponents pull request #9565
Opened 2024-07-26 10:51 UTC by TeodorTaushanov

radio button which is not in the DOM should not change the selection of any other button

fixes: #9510

2024-07-29 08:05 UTC, BorisDafov requested changes
minor

2024-07-29 08:05 UTC, BorisDafov commented on packages/main/test/pages/RadioButton.html
> +	<ui5-title level="H2">Dynamically created buttons</ui5-title>
Use title case:
<ui5-title level="H2">Dynamically Created Buttons</ui5-title>

2024-07-31 10:11 UTC, BorisDafov reviewed
I approve the PR from UA perspective

2024-08-01 10:59 UTC, dimovpetar approved these changes

2024-08-01 13:08 UTC, merged