Cal week numbering
SAP/ui5-webcomponents pull request #9694
Opened 2024-08-15 07:42 UTC by tsanislavgatev

2024-08-19 13:42 UTC, hinzzx approved these changes

2024-08-19 13:42 UTC, hinzzx commented on packages/website/docs/_components_pages/main/Calendar/Calendar.mdx
> +You can use the component the preferred week numbering and first day of week.
Very minor one: 
`You can use the component, the preferred week numbering and first day of week.`

2024-08-19 13:42 UTC, hinzzx commented on packages/website/docs/_components_pages/main/DatePicker.mdx
> +You can use the component the preferred week numbering and first day of week.
same as previous comment (missing comma);

2024-08-20 07:29 UTC, nnaydenow requested changes

2024-08-20 07:29 UTC, nnaydenow commented on packages/main/src/types/CalendarWeekNumbering.ts
> + * <ul>
use markdown syntax for list

2024-08-20 07:29 UTC, nnaydenow commented on packages/main/src/DateComponentBase.ts
> +	calendarWeekNumbering?: `${CalendarWeekNumbering}` = "Default";
? is not needed when the property has initializer

2024-08-23 07:27 UTC, nnaydenow approved these changes

2024-08-23 13:38 UTC, merged