fix(ui5-wizard): disabled steps are no longer clickable
SAP/ui5-webcomponents pull request #9706
Opened 2024-08-20 07:56 UTC by MapTo0

FIXES: #9571

2024-08-20 07:57 UTC, MapTo0 commented
Cherry pick of https://github.com/SAP/ui5-webcomponents/pull/9459

2024-08-20 10:23 UTC, ivoplashkov requested changes
Issue seems to be still reproducible.

<img width="1605" alt="Screenshot 2024-08-20 at 13 11 26" src="https://github.com/user-attachments/assets/0a93d8b4-83b3-4845-ae4c-95d98ff4d800">

2024-08-27 09:15 UTC, elenastoyanovaa approved these changes

2024-09-24 10:13 UTC, ivoplashkov approved these changes

2024-09-25 12:01 UTC, merged