feat(ui5-link, ui5-time-selection-clocks): add focus support for mobile
SAP/ui5-webcomponents pull request #9718
Opened 2024-08-21 11:03 UTC by didip1000

Like https://github.com/SAP/ui5-webcomponents/pull/8414, `Link` and `TimeSelectionClocks` elements can now receive focus when using keyboards on mobile devices.

Related to: https://github.com/SAP/ui5-webcomponents/issues/8322

2024-08-27 14:39 UTC, hinzzx requested changes
- There are different styles (we are looking at the text underlining) when a Link is in `focused` state and is being hovered upon;
- When the Link is focused, the text is always being changed to white, while it should be considering the color (if being overstyled, check the second example);

### Before (Correct behaviours)
![2024-08-27_17-25-58](https://github.com/user-attachments/assets/a51f1220-339d-456f-9284-39ff4cb5b6fb)

![2024-08-27_17-30-28](https://github.com/user-attachments/assets/93941a70-07df-44d8-a7c2-087cd9e5e71b)



### After
![2024-08-27_17-25-50](https://github.com/user-attachments/assets/d08208b3-5efc-422a-ad1e-38b5da6136c1)

![2024-08-27_17-30-34](https://github.com/user-attachments/assets/d18626dc-d77f-4e96-b92b-9d0ac244d31e)

2024-09-12 13:54 UTC, tsanislavgatev commented
@hinzzx He had a discussion with the Core team and we decided to proceed with the current solution, even if it removes the opportunity to overstyle the link directly when focused. The reasons discussed were that it can always be overstyled by changing the css variable value, which is the most common use case for us, and also is an edge case that will rarely be hit. Based on these two, we decided that this should not be stopper for us to continue with the implementation and review. You can proceed with the review.

2024-09-24 06:37 UTC, hinzzx approved these changes

2024-10-03 09:06 UTC, tsanislavgatev approved these changes

2024-10-08 06:16 UTC, merged