fix(ui5-multi-combobox): adjust the failing aria-describedby test
SAP/ui5-webcomponents pull request #9792
Opened 2024-09-02 12:41 UTC by ndeshev

the test is fixed to focus out the tested ui5-multi-combobox in order for the aria-describedby attribute to be updated

fixes: #9778

2024-09-02 12:57 UTC, elenastoyanovaa requested changes
I think that this is a workaround and we should fix the functionality, rather than trying to workaround the unstable test.
What is more, the "Tab" interaction was added to achieve the same - to focus out of the input, so we already tried it... Having the fact that the functionality was broken and reported 4 months ago I think that it is best to fix it. After all this is working in the MultiInput and the test is stable and does not need those workarounds in order to pass.

2024-09-03 19:22 UTC, ndeshev commented
I get your point, but the strange thing is, that I can not reproduce the failing assertion with real interaction, the hidden text is always updated to "Contains 1 token" after deleting a token (the assertion at line #1782 of this change)

2024-09-08 14:12 UTC, ndeshev commented
After our follow up conversation I uploaded a new commit fixing the issue and not modifying the test

2024-09-10 21:38 UTC, Okiana approved these changes

2024-09-13 06:26 UTC, merged