fix(uit-popover): adjust heigh when vertical-align=stretch
SAP/ui5-webcomponents pull request #9798
Opened 2024-09-03 11:42 UTC by GerganaKremenska

Popover should recieve the height of the opener if vertical-align=stretch and placment=start / end.

2024-09-04 11:21 UTC, TeodorTaushanov requested changes

2024-09-04 11:21 UTC, TeodorTaushanov commented on packages/main/src/types/PopoverVerticalAlign.ts
> +	 * If popover placement is Start or End, popover will be stretched with the height of the opener
remove it

2024-09-04 12:50 UTC, GerganaKremenska commented on packages/main/src/types/PopoverVerticalAlign.ts
> +	 * If popover placement is Start or End, popover will be stretched with the height of the opener
> remove it

done

2024-09-05 06:33 UTC, TeodorTaushanov approved these changes

2024-09-05 06:52 UTC, merged

2024-09-05 10:34 UTC, ilhan007 commented
just a reminder: downport to 1.24 is also required (as 1.x is still supported)