feat(ui5-input): enable preventing input event
SAP/ui5-webcomponents pull request #9930
Opened 2024-09-25 08:45 UTC by MapTo0

FIXES: #9884

2024-09-25 19:56 UTC, elenastoyanovaa approved these changes

2024-09-25 19:58 UTC, elenastoyanovaa requested changes
Tested the change, everything seems to work correctly. My only concern is that the reported issue is for 1.24 and you have marked the change as a feature. Please discuss the naming and downport to 1.24

2024-09-26 10:06 UTC, MapTo0 commented
Change for 1.24: https://github.com/SAP/ui5-webcomponents/pull/9946

2024-09-26 11:02 UTC, elenastoyanovaa approved these changes

2024-09-26 11:13 UTC, merged